// plugins/payment-gateway/frontend/admin/Page.vue
<script lang="ts" setup>
import {onMounted, ref} from 'vue'

import {pluginAction} from '@/utils/pluginAction'

/**
 * 支付网关（payment-gateway 插件后台页）
 *
 * 对应 `plugins/payment-gateway/frontend/admin/Page.tsx`：
 * 展示当前支付配置（提供商 / 货币 / 沙箱）+ 发起一笔测试支付 + 显示已配置的凭据。
 */
interface Settings {
  provider?: string | null
  currency?: string | null
  alipay_sandbox?: boolean | null
  alipay_app_id?: string | null
  wechat_app_id?: string | null
  stripe_secret_key?: string | null
}

const settings = ref<Settings>({})
const loading = ref(true)
const error = ref('')

const orderId = ref('')
const amount = ref('')
const paying = ref(false)
const result = ref<unknown>(null)

async function load(): Promise<void> {
  loading.value = true
  error.value = ''
  try {
    const response = await pluginAction<Settings>('payment-gateway', 'get_settings')
    settings.value = response.data ?? {}
    if (!response.success) error.value = response.error || '加载配置失败'
  } finally {
    loading.value = false
  }
}

async function testPayment(): Promise<void> {
  paying.value = true
  try {
    const response = await pluginAction('payment-gateway', 'create_payment', {
      order_id: orderId.value || `test_${Date.now()}`,
      amount: Number.parseInt(amount.value, 10) || 100,
      subject: '测试支付',
    })
    result.value = response.data
  } finally {
    paying.value = false
  }
}

onMounted(load)
</script>

<template>
  <div class="p-4">
    <div class="mb-3 flex justify-end">
      <el-button :loading="loading" size="small" @click="load">
        <Icon class="mr-1 h-3.5 w-3.5" name="refresh-cw"/>
        刷新
      </el-button>
    </div>

    <p v-if="error" class="mb-3 rounded-control bg-danger-soft px-3 py-2 text-sm text-danger">{{ error }}</p>

    <!-- 配置卡片 -->
    <div class="mb-6 grid grid-cols-1 gap-4 md:grid-cols-3">
      <div class="rounded-card border border-line bg-surface p-5">
        <div class="mb-3 flex items-center gap-3">
          <span class="flex h-10 w-10 items-center justify-center rounded-control bg-primary-soft">
            <Icon class="h-5 w-5 text-primary" name="credit-card"/>
          </span>
          <div>
            <p class="text-sm text-fg-muted">当前提供商</p>
            <p class="text-lg font-semibold text-fg">{{ settings.provider || '未配置' }}</p>
          </div>
        </div>
      </div>

      <div class="rounded-card border border-line bg-surface p-5">
        <div class="mb-3 flex items-center gap-3">
          <span class="flex h-10 w-10 items-center justify-center rounded-control bg-success-soft">
            <Icon class="h-5 w-5 text-success" name="dollar-sign"/>
          </span>
          <div>
            <p class="text-sm text-fg-muted">货币</p>
            <p class="text-lg font-semibold uppercase text-fg">{{ settings.currency || 'cny' }}</p>
          </div>
        </div>
      </div>

      <div class="rounded-card border border-line bg-surface p-5">
        <div class="mb-3 flex items-center gap-3">
          <span class="flex h-10 w-10 items-center justify-center rounded-control bg-primary-soft">
            <Icon class="h-5 w-5 text-primary" name="circle-check"/>
          </span>
          <div>
            <p class="text-sm text-fg-muted">沙箱模式</p>
            <p class="text-lg font-semibold text-fg">{{ settings.alipay_sandbox ? '开启' : '关闭' }}</p>
          </div>
        </div>
      </div>
    </div>

    <!-- 测试支付 -->
    <div class="mb-6 rounded-card border border-line bg-surface p-5">
      <h3 class="mb-4 text-sm font-semibold text-fg">测试支付</h3>
      <div class="flex flex-wrap gap-3">
        <el-input v-model="orderId" class="min-w-[200px] flex-1" placeholder="订单号（可选，自动生成）"/>
        <el-input v-model="amount" class="w-32" placeholder="金额（分）" type="number"/>
        <el-button :loading="paying" type="primary" @click="testPayment">
          <Icon class="mr-1 h-4 w-4" name="arrow-right"/>
          发起测试
        </el-button>
      </div>
      <pre
        v-if="result"
        class="mt-3 overflow-auto rounded-control bg-surface-soft p-3 text-xs text-fg-muted"
      >{{ JSON.stringify(result, null, 2) }}</pre>
    </div>

    <!-- 凭据 -->
    <div class="rounded-card border border-line bg-surface p-5">
      <h3 class="mb-3 text-sm font-semibold text-fg">支付配置</h3>

      <div v-if="loading" class="space-y-3">
        <Skeleton class="h-5 w-64"/>
        <Skeleton class="h-5 w-48"/>
      </div>

      <div v-else class="space-y-2 text-sm text-fg-muted">
        <p v-if="settings.alipay_app_id">
          支付宝 AppID：<code class="text-fg">{{ settings.alipay_app_id }}</code>
        </p>
        <p v-if="settings.wechat_app_id">
          微信 AppID：<code class="text-fg">{{ settings.wechat_app_id }}</code>
        </p>
        <p v-if="settings.stripe_secret_key">Stripe：<code class="text-fg">已配置</code></p>
        <p v-if="!settings.alipay_app_id && !settings.wechat_app_id && !settings.stripe_secret_key">
          暂未配置支付参数，请在插件设置中配置
        </p>
      </div>
    </div>
  </div>
</template>

// plugins/payment-gateway/frontend/admin/Page.tsx
'use client';

import React, {useState} from 'react';
import {useMutation, useQuery} from '@tanstack/react-query';
import {AdminShell} from '@/components/admin/AdminShell';
import {apiClient} from '@/lib/api/base-client';
import {ArrowRight, CheckCircle2, CreditCard, DollarSign, Loader2, RefreshCw} from 'lucide-react';

const PLUGIN_SLUG = 'payment-gateway';

function call(action: string, params: any = {}) {
  return apiClient.post(`/plugins/${PLUGIN_SLUG}/action`, {action, params});
}

function PaymentGatewayDashboard() {
  const [orderId, setOrderId] = useState('');
  const [amount, setAmount] = useState('');
  const [provider, setProvider] = useState('');

  const {data: settings, isLoading: loadSettings, refetch} = useQuery({
    queryKey: ['payment-gateway-settings'],
    queryFn: async () => {
      const r = await call('get_settings');
      return r.data || {};
    },
  });

  const testPaymentMut = useMutation({
    mutationFn: () => call('create_payment', {
      order_id: orderId || `test_${Date.now()}`,
      amount: parseInt(amount, 10) || 100,
      subject: '测试支付',
    }),
  });

  return (
    <AdminShell title="支付网关" actions={
      <button onClick={() => refetch()} disabled={loadSettings}
              className="flex items-center gap-1.5 px-4 py-2 border rounded-lg text-sm hover:bg-gray-50 dark:hover:bg-gray-800 disabled:opacity-50">
        <RefreshCw className={`w-4 h-4 ${loadSettings ? 'animate-spin' : ''}`}/> 刷新
      </button>
    }>
      {/* 当前配置状态 */}
      <div className="mb-6 grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-white dark:bg-gray-900 rounded-xl border p-5">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 bg-blue-100 dark:bg-blue-900/30 rounded-lg flex items-center justify-center">
              <CreditCard className="w-5 h-5 text-blue-600 dark:text-blue-400"/>
            </div>
            <div>
              <p className="text-sm text-gray-500">当前提供商</p>
              <p className="text-lg font-semibold">{settings?.provider || '未配置'}</p>
            </div>
          </div>
        </div>
        <div className="bg-white dark:bg-gray-900 rounded-xl border p-5">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 bg-green-100 dark:bg-green-900/30 rounded-lg flex items-center justify-center">
              <DollarSign className="w-5 h-5 text-green-600 dark:text-green-400"/>
            </div>
            <div>
              <p className="text-sm text-gray-500">货币</p>
              <p className="text-lg font-semibold uppercase">{settings?.currency || 'cny'}</p>
            </div>
          </div>
        </div>
        <div className="bg-white dark:bg-gray-900 rounded-xl border p-5">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 bg-purple-100 dark:bg-purple-900/30 rounded-lg flex items-center justify-center">
              <CheckCircle2 className="w-5 h-5 text-purple-600 dark:text-purple-400"/>
            </div>
            <div>
              <p className="text-sm text-gray-500">沙箱模式</p>
              <p className="text-lg font-semibold">{settings?.alipay_sandbox ? '开启' : '关闭'}</p>
            </div>
          </div>
        </div>
      </div>

      {/* 测试支付 */}
      <div className="bg-white dark:bg-gray-900 rounded-xl border p-5 mb-6">
        <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-4">测试支付</h3>
        <div className="flex flex-wrap gap-3">
          <input value={orderId} onChange={e => setOrderId(e.target.value)}
                 placeholder="订单号（可选，自动生成）"
                 className="flex-1 min-w-[200px] px-3 py-2 border rounded-lg text-sm bg-white dark:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500"/>
          <input value={amount} onChange={e => setAmount(e.target.value)}
                 placeholder="金额（分）" type="number"
                 className="w-32 px-3 py-2 border rounded-lg text-sm bg-white dark:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500"/>
          <button onClick={() => testPaymentMut.mutate()} disabled={testPaymentMut.isPending}
                  className="flex items-center gap-1.5 px-4 py-2 bg-blue-600 text-white text-sm rounded-lg hover:bg-blue-700 disabled:opacity-50">
            {testPaymentMut.isPending ? '处理中...' : <><ArrowRight className="w-4 h-4"/> 发起测试</>}
          </button>
        </div>
        {testPaymentMut.data && (
          <div className="mt-3 p-3 bg-gray-50 dark:bg-gray-800 rounded-lg text-xs">
            <pre
              className="whitespace-pre-wrap text-gray-600 dark:text-gray-400">{JSON.stringify(testPaymentMut.data, null, 2)}</pre>
          </div>
        )}
      </div>

      {/* 配置信息 */}
      <div className="bg-white dark:bg-gray-900 rounded-xl border p-5">
        <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">支付配置</h3>
        {loadSettings ? (
          <div className="flex justify-center py-8"><Loader2 className="w-6 h-6 animate-spin text-blue-500"/></div>
        ) : (
          <div className="text-sm text-gray-500 space-y-2">
            {settings?.alipay_app_id &&
              <p>支付宝 AppID: <code className="text-gray-700 dark:text-gray-300">{settings.alipay_app_id}</code></p>}
            {settings?.wechat_app_id &&
              <p>微信 AppID: <code className="text-gray-700 dark:text-gray-300">{settings.wechat_app_id}</code></p>}
            {settings?.stripe_secret_key &&
              <p>Stripe: <code className="text-gray-700 dark:text-gray-300">已配置</code></p>}
            {!settings?.alipay_app_id && !settings?.wechat_app_id && !settings?.stripe_secret_key &&
              <p>暂未配置支付参数，请在插件设置中配置</p>}
          </div>
        )}
      </div>
    </AdminShell>
  );
}

export default function PaymentGatewayPage() {
  return <PaymentGatewayDashboard/>;
}
