// frontend-astro/src/components/ui/badge.tsx
import * as React from 'react';
import {cva, type VariantProps} from 'class-variance-authority';
import {cn} from '@/lib/utils';

const badgeVariants = cva(
  'inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2',
  {variants: {variant: {default: 'border-transparent bg-primary text-primary-foreground hover:bg-primary/80', secondary: 'border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80', destructive: 'border-transparent bg-destructive text-destructive-foreground hover:bg-destructive/80', outline: 'text-foreground'}}, defaultVariants: {variant: 'default'}}
);

export interface BadgeProps extends React.HTMLAttributes<HTMLDivElement>, VariantProps<typeof badgeVariants> {}

function Badge({className, variant, ...props}: BadgeProps) {
  return <div className={cn(badgeVariants({variant}), className)} {...props} />;
}

export {Badge, badgeVariants};

// frontend/web/src/components/ui/badge/Badge.vue
<script lang="ts" setup>
import {cn} from '@/lib/utils'

const props = withDefaults(defineProps<{ variant?: 'default' | 'secondary' | 'outline'; class?: string }>(), {
  variant: 'default',
})

const VARIANTS: Record<string, string> = {
  default: 'bg-slate-900 text-white hover:bg-slate-800',
  secondary: 'bg-slate-100 text-slate-700 hover:bg-slate-200',
  outline: 'border border-slate-200 text-slate-700',
}
</script>

<template>
  <span
    :class="cn('inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium transition-colors', VARIANTS[props.variant], props.class)"
  >
    <slot/>
  </span>
</template>
