// plugins/code-snippets/frontend/admin/Page.tsx
'use client';

import React, {useState} from 'react';
import {useQuery, useMutation, useQueryClient} from '@tanstack/react-query';
import {AuthGuard} from '@/components/AuthGuard';
import {QueryProvider} from '@/components/QueryProvider';
import {AdminShell} from '@/components/admin/AdminShell';
import {apiClient} from '@/lib/api/base-client';
import {Code, Plus, Trash2, Eye, Copy, Check, X} from 'lucide-react';

const PLUGIN_SLUG = 'code-snippets';
const ACTION_URL = `/plugins/${PLUGIN_SLUG}/action`;

interface Snippet {
  id: number;
  title: string;
  code: string;
  language: string;
  description: string;
  tags: string[];
  visibility: string;
  user_id: number;
  view_count: number;
  embed_count: number;
  created_at: string;
}

interface SnippetForm {
  title: string;
  code: string;
  language: string;
  description: string;
  tags: string;
  visibility: 'public' | 'private' | 'unlisted';
}

const EMPTY_FORM: SnippetForm = {title: '', code: '', language: 'python', description: '', tags: '', visibility: 'public'};

const SUPPORTED_LANGUAGES = [
  'python', 'javascript', 'typescript', 'java', 'cpp', 'c',
  'html', 'css', 'sql', 'bash', 'json', 'yaml', 'markdown',
];

function useCurrentUser() {
  return useQuery({
    queryKey: ['current-user'],
    queryFn: async () => {
      const res = await apiClient.get('/users/me');
      return res.data || {};
    },
    staleTime: 5 * 60 * 1000,
  });
}

function SnippetEditor({snippet, onSave, onCancel}: {snippet: SnippetForm; onSave: (d: SnippetForm) => void; onCancel: () => void}) {
  const [form, setForm] = useState<SnippetForm>(snippet);
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40" onClick={onCancel}>
      <div className="bg-white dark:bg-gray-900 rounded-2xl w-full max-w-3xl max-h-[90vh] overflow-y-auto m-4 shadow-2xl border border-gray-200 dark:border-gray-800" onClick={e => e.stopPropagation()}>
        <div className="flex items-center justify-between p-6 border-b border-gray-200 dark:border-gray-800">
          <h2 className="text-lg font-bold text-gray-900 dark:text-white">{snippet.title ? 'Edit Snippet' : 'New Snippet'}</h2>
          <button onClick={onCancel} className="p-2 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg"><X className="w-5 h-5 text-gray-400"/></button>
        </div>
        <div className="p-6 space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Title</label>
            <input type="text" value={form.title} onChange={e => setForm({...form, title: e.target.value})}
                   className="w-full px-3 py-2 border border-gray-200 dark:border-gray-700 rounded-xl bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500"/>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Language</label>
              <select value={form.language} onChange={e => setForm({...form, language: e.target.value})}
                      className="w-full px-3 py-2 border border-gray-200 dark:border-gray-700 rounded-xl bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm">
                {SUPPORTED_LANGUAGES.map(l => <option key={l} value={l}>{l}</option>)}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Visibility</label>
              <select value={form.visibility} onChange={e => setForm({...form, visibility: e.target.value as any})}
                      className="w-full px-3 py-2 border border-gray-200 dark:border-gray-700 rounded-xl bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm">
                <option value="public">Public</option>
                <option value="private">Private</option>
                <option value="unlisted">Unlisted</option>
              </select>
            </div>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Description</label>
            <input type="text" value={form.description} onChange={e => setForm({...form, description: e.target.value})}
                   className="w-full px-3 py-2 border border-gray-200 dark:border-gray-700 rounded-xl bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm"/>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Tags (comma-separated)</label>
            <input type="text" value={form.tags} onChange={e => setForm({...form, tags: e.target.value})}
                   placeholder="e.g. python, tutorial, beginner"
                   className="w-full px-3 py-2 border border-gray-200 dark:border-gray-700 rounded-xl bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm"/>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Code</label>
            <textarea value={form.code} onChange={e => setForm({...form, code: e.target.value})} rows={12}
                      className="w-full px-3 py-2 border border-gray-200 dark:border-gray-700 rounded-xl bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm font-mono"/>
          </div>
        </div>
        <div className="flex items-center justify-end gap-3 p-6 border-t border-gray-200 dark:border-gray-800">
          <button onClick={onCancel} className="px-4 py-2 text-sm text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-xl transition-colors">Cancel</button>
          <button onClick={() => onSave(form)} className="px-6 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-xl transition-colors">{snippet.title ? 'Save' : 'Create'}</button>
        </div>
      </div>
    </div>
  );
}

function SnippetManager() {
  const queryClient = useQueryClient();
  const [showEditor, setShowEditor] = useState(false);
  const [editingSnippet, setEditingSnippet] = useState<SnippetForm>(EMPTY_FORM);
  const [copiedId, setCopiedId] = useState<number | null>(null);
  const [searchQuery, setSearchQuery] = useState('');

  const {data: user} = useCurrentUser();
  const userId = (user as any)?.id || 0;

  const {data: snippets = [], isLoading} = useQuery({
    queryKey: ['code-snippets', userId],
    queryFn: () => {
      if (!userId) return [];
      return import('../api').then(m => m.SnippetService.list(userId));
    },
    enabled: !!userId,
  });

  const createMutation = useMutation({
    mutationFn: (form: SnippetForm) =>
      import('../api').then(m => m.SnippetService.create(
        {...form, tags: form.tags.split(',').map(t => t.trim()).filter(Boolean)}, userId)),
    onSuccess: () => { queryClient.invalidateQueries({queryKey: ['code-snippets']}); setShowEditor(false); setEditingSnippet(EMPTY_FORM); },
  });

  const deleteMutation = useMutation({
    mutationFn: (id: number) => import('../api').then(m => m.SnippetService.delete(id, userId)),
    onSuccess: () => queryClient.invalidateQueries({queryKey: ['code-snippets']}),
  });

  const copyEmbedCode = async (snippet: Snippet) => {
    const embed = `[snippet:${snippet.id}]`;
    try { await navigator.clipboard.writeText(embed); setCopiedId(snippet.id); setTimeout(() => setCopiedId(null), 2000); } catch {}
  };

  const filtered = snippets.filter((s: Snippet) =>
    !searchQuery || s.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
    s.tags?.some(t => t.toLowerCase().includes(searchQuery.toLowerCase())));

  return (
    <AdminShell title="Snippets" actions={
      <button onClick={() => { setEditingSnippet(EMPTY_FORM); setShowEditor(true); }}
              className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-xl transition-colors">
        <Plus className="w-4 h-4"/> New Snippet
      </button>
    }>
      <div className="mb-6">
        <input type="text" placeholder="Search snippets..." value={searchQuery} onChange={e => setSearchQuery(e.target.value)}
               className="w-full max-w-md px-4 py-2 border border-gray-200 dark:border-gray-700 rounded-xl bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm"/>
      </div>
      {isLoading ? (
        <div className="space-y-3">{[1,2,3].map(i => <div key={i} className="h-20 bg-gray-100 dark:bg-gray-800 rounded-xl animate-pulse"/>)}</div>
      ) : filtered.length === 0 ? (
        <div className="text-center py-20 text-gray-400">
          <Code className="w-12 h-12 mx-auto mb-4 opacity-50"/>
          <p className="text-lg font-medium text-gray-500 dark:text-gray-400 mb-1">No snippets yet</p>
          <p className="text-sm">Click "New Snippet" to create one</p>
        </div>
      ) : (
        <div className="space-y-3">
          {filtered.map((snippet: Snippet) => (
            <div key={snippet.id} className="p-4 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-xl hover:border-gray-300 dark:hover:border-gray-700 transition-colors">
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-3">
                  <Code className="w-4 h-4 text-blue-500"/>
                  <h3 className="font-semibold text-gray-900 dark:text-white text-sm">{snippet.title}</h3>
                  <span className="text-xs px-2 py-0.5 bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 rounded-full">{snippet.language}</span>
                  {snippet.visibility !== 'public' && <span className="text-xs px-2 py-0.5 bg-gray-100 dark:bg-gray-800 text-gray-500 rounded-full">{snippet.visibility}</span>}
                </div>
              </div>
              {snippet.description && <p className="text-sm text-gray-500 dark:text-gray-400 mb-2 line-clamp-1">{snippet.description}</p>}
              {snippet.tags && snippet.tags.length > 0 && (
                <div className="flex gap-1.5 mb-2 flex-wrap">
                  {snippet.tags.map((tag: string) => <span key={tag} className="text-xs px-2 py-0.5 bg-gray-100 dark:bg-gray-800 text-gray-500 rounded-full">{tag}</span>)}
                </div>
              )}
              <div className="flex items-center justify-between text-xs text-gray-400">
                <div className="flex items-center gap-3">
                  <span className="flex items-center gap-1"><Eye className="w-3 h-3"/>{snippet.view_count}</span>
                  <span className="flex items-center gap-1"><Code className="w-3 h-3"/>{snippet.embed_count}</span>
                  <span>{snippet.created_at ? new Date(snippet.created_at).toLocaleDateString() : ''}</span>
                </div>
                <div className="flex items-center gap-2">
                  <button onClick={() => copyEmbedCode(snippet)} className="p-1.5 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg transition-colors" title="Copy embed [snippet:N]">
                    {copiedId === snippet.id ? <Check className="w-4 h-4 text-green-500"/> : <Copy className="w-4 h-4"/>}
                  </button>
                  <button onClick={() => deleteMutation.mutate(snippet.id)} className="p-1.5 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg transition-colors text-gray-400 hover:text-red-500" title="Delete">
                    <Trash2 className="w-4 h-4"/>
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
      {showEditor && (
        <SnippetEditor snippet={editingSnippet}
                       onSave={data => createMutation.mutate(data)}
                       onCancel={() => { setShowEditor(false); setEditingSnippet(EMPTY_FORM); }}/>
      )}
    </AdminShell>
  );
}

export default function AdminCodeSnippets() {
  return <AuthGuard><QueryProvider><SnippetManager/></QueryProvider></AuthGuard>;
}

// plugins/code-snippets/frontend/admin/Page.vue
<script lang="ts" setup>
import {computed, onMounted, reactive, ref} from 'vue'

import {ElMessage, ElMessageBox} from '@/utils/feedback'
import {pluginAction} from '@/utils/pluginAction'
import {useUserStore} from '@/store/modules/user'

const {t} = useI18n()

/**
 * 代码片段（code-snippets 插件后台页）
 *
 * 对应 `plugins/code-snippets/frontend/admin/Page.tsx`：
 * 当前用户的片段列表 + 本地搜索 + 新建弹窗 + 复制嵌入标记 `[snippet:N]` + 删除。
 *
 * 与 astro 版的两点差异：
 *  1. 原实现额外请求 `/api/v2/users/me` 拿用户 ID；这里直接用 Pinia 的
 *     `useUserStore().userInfo`（后台本来就已加载），少一次请求。
 *  2. 原实现只实现了「新建」，编辑弹窗虽叫 `SnippetEditor` 但只用于创建；
 *     这里保持同样范围（活动 `update_snippet` 接口仍在后端，需要时可补编辑）。
 */
interface Snippet {
  id: number
  title: string
  code: string
  language: string
  description?: string | null
  tags?: string[] | null
  visibility?: string | null
  view_count?: number | null
  embed_count?: number | null
  created_at?: string | null
}

interface SnippetForm {
  title: string
  code: string
  language: string
  description: string
  tags: string
  visibility: 'public' | 'private' | 'unlisted'
}

const SUPPORTED_LANGUAGES = [
  'python', 'javascript', 'typescript', 'java', 'cpp', 'c',
  'html', 'css', 'sql', 'bash', 'json', 'yaml', 'markdown',
]

const userStore = useUserStore()
const userId = computed(() => userStore.userInfo?.id ?? 0)

const loading = ref(false)
const error = ref('')
const snippets = ref<Snippet[]>([])
const searchQuery = ref('')
const copiedId = ref<number | null>(null)

const editorOpen = ref(false)
const saving = ref(false)
const form = reactive<SnippetForm>(emptyForm())

function emptyForm(): SnippetForm {
  return {title: '', code: '', language: 'python', description: '', tags: '', visibility: 'public'}
}

const filtered = computed(() => {
  const query = searchQuery.value.trim().toLowerCase()
  if (!query) return snippets.value
  return snippets.value.filter(
    (item) =>
      item.title?.toLowerCase().includes(query) ||
      item.tags?.some((tag) => tag.toLowerCase().includes(query)),
  )
})

async function loadSnippets(): Promise<void> {
  if (!userId.value) return
  loading.value = true
  error.value = ''
  try {
    const result = await pluginAction<{ data?: Snippet[] } | Snippet[]>(
      'code-snippets',
      'get_user_snippets',
      {user_id: userId.value, limit: 100, offset: 0},
    )
    const payload = result.data
    snippets.value = Array.isArray(payload) ? payload : (payload?.data ?? [])
    if (!result.success) error.value = result.error || t('admin.pluginPages.common.loadFailed')
  } finally {
    loading.value = false
  }
}

function openEditor(): void {
  Object.assign(form, emptyForm())
  editorOpen.value = true
}

async function saveSnippet(): Promise<void> {
  if (!form.title.trim() || !userId.value) return
  saving.value = true
  try {
    const result = await pluginAction('code-snippets', 'create_snippet', {
      title: form.title,
      code: form.code,
      language: form.language,
      description: form.description,
      visibility: form.visibility,
      tags: form.tags
        .split(',')
        .map((tag) => tag.trim())
        .filter(Boolean),
      user_id: userId.value,
    })
    if (result.success) {
      ElMessage.success(t('admin.pluginPages.codeSnippets.created'))
      editorOpen.value = false
      await loadSnippets()
    } else {
      ElMessage.error(result.error || t('admin.pluginPages.common.createFailed'))
    }
  } finally {
    saving.value = false
  }
}

async function removeSnippet(snippet: Snippet): Promise<void> {
  await ElMessageBox.confirm(t('admin.pluginPages.common.confirmDeleteNamed', {name: snippet.title}), t('admin.common.notice'), {type: 'warning'})
  const result = await pluginAction('code-snippets', 'delete_snippet', {
    snippet_id: snippet.id,
    user_id: userId.value,
  })
  if (result.success) {
    ElMessage.success(t('admin.common.deleted'))
    await loadSnippets()
  } else {
    ElMessage.error(result.error || t('admin.pluginPages.common.deleteFailed'))
  }
}

/** 复制嵌入标记，供文章正文引用 */
async function copyEmbed(snippet: Snippet): Promise<void> {
  try {
    await navigator.clipboard.writeText(`[snippet:${snippet.id}]`)
    copiedId.value = snippet.id
    window.setTimeout(() => {
      copiedId.value = null
    }, 2000)
    ElMessage.success(t('admin.pluginPages.codeSnippets.embedCopied'))
  } catch {
    ElMessage.warning(t('admin.pluginPages.common.copyFailed'))
  }
}

function formatDate(value?: string | null): string {
  if (!value) return ''
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? '' : date.toLocaleDateString()
}

onMounted(loadSnippets)
</script>

<template>
  <div class="p-4">
    <div class="mb-4 flex flex-wrap items-center gap-3">
      <el-input v-model="searchQuery" :placeholder="t('admin.pluginPages.common.searchPlaceholder')" class="max-w-md"/>
      <el-button class="ml-auto" type="primary" @click="openEditor">
        <Icon class="mr-1 h-4 w-4" name="plus"/>
        {{ t('admin.pluginPages.codeSnippets.create') }}
      </el-button>
    </div>

    <p v-if="error" class="mb-3 rounded-control bg-danger-soft px-3 py-2 text-sm text-danger">{{ error }}</p>

    <div v-if="loading" class="space-y-3">
      <Skeleton v-for="i in 3" :key="i" class="h-20 w-full"/>
    </div>

    <EmptyState
      v-else-if="!filtered.length"
      :description="searchQuery ? t('admin.pluginPages.common.tryAnotherKeyword') : t('admin.pluginPages.codeSnippets.emptyDesc')"
      :title="searchQuery ? t('admin.pluginPages.common.noMatch') : t('admin.pluginPages.codeSnippets.emptyTitle')"
    />

    <div v-else class="space-y-3">
      <div
        v-for="snippet in filtered"
        :key="snippet.id"
        class="rounded-card border border-line bg-surface p-4 transition-colors hover:border-line-strong"
      >
        <div class="mb-2 flex items-center gap-3">
          <Icon class="h-4 w-4 text-primary" name="code"/>
          <h3 class="text-sm font-semibold text-fg">{{ snippet.title }}</h3>
          <span class="rounded-pill bg-primary-soft px-2 py-0.5 text-xs text-primary">{{ snippet.language }}</span>
          <span
            v-if="snippet.visibility && snippet.visibility !== 'public'"
            class="rounded-pill bg-surface-soft px-2 py-0.5 text-xs text-fg-muted"
          >{{ snippet.visibility }}</span>
        </div>

        <p v-if="snippet.description" class="mb-2 line-clamp-1 text-sm text-fg-muted">{{ snippet.description }}</p>

        <div v-if="snippet.tags?.length" class="mb-2 flex flex-wrap gap-1.5">
          <span
            v-for="tag in snippet.tags"
            :key="tag"
            class="rounded-pill bg-surface-soft px-2 py-0.5 text-xs text-fg-muted"
          >{{ tag }}</span>
        </div>

        <div class="flex items-center justify-between text-xs text-fg-subtle">
          <div class="flex items-center gap-3">
            <span class="flex items-center gap-1">
              <Icon class="h-3 w-3" name="eye"/>{{ snippet.view_count ?? 0 }}
            </span>
            <span class="flex items-center gap-1">
              <Icon class="h-3 w-3" name="code"/>{{ snippet.embed_count ?? 0 }}
            </span>
            <span>{{ formatDate(snippet.created_at) }}</span>
          </div>
          <div class="flex items-center gap-1">
            <el-button :title="t('admin.pluginPages.codeSnippets.copyEmbed')" link @click="copyEmbed(snippet)">
              <Icon
                :class="copiedId === snippet.id ? 'text-success' : 'text-fg-subtle'"
                :name="copiedId === snippet.id ? 'check' : 'copy'"
                class="h-4 w-4"
              />
            </el-button>
            <el-button :title="t('admin.common.delete')" link type="danger" @click="removeSnippet(snippet)">
              <Icon class="h-4 w-4" name="trash-2"/>
            </el-button>
          </div>
        </div>
      </div>
    </div>

    <!-- 新建片段 -->
    <el-dialog v-model="editorOpen" :title="t('admin.pluginPages.codeSnippets.createTitle')" width="720px">
      <div class="space-y-4">
        <div>
          <label class="mb-1 block text-sm font-medium text-fg">{{ t('admin.pluginPages.common.fieldTitle') }}</label>
          <el-input v-model="form.title" :placeholder="t('admin.pluginPages.codeSnippets.titlePlaceholder')"/>
        </div>

        <div class="grid grid-cols-2 gap-4">
          <div>
            <label class="mb-1 block text-sm font-medium text-fg">{{
                t('admin.pluginPages.codeSnippets.language')
              }}</label>
            <el-select v-model="form.language" class="w-full">
              <el-option v-for="lang in SUPPORTED_LANGUAGES" :key="lang" :label="lang" :value="lang"/>
            </el-select>
          </div>
          <div>
            <label class="mb-1 block text-sm font-medium text-fg">{{
                t('admin.pluginPages.common.fieldVisibility')
              }}</label>
            <el-select v-model="form.visibility" class="w-full">
              <el-option :label="t('admin.content.media.publicLabel')" value="public"/>
              <el-option :label="t('admin.content.media.privateLabel')" value="private"/>
              <el-option :label="t('admin.pluginPages.common.unlisted')" value="unlisted"/>
            </el-select>
          </div>
        </div>

        <div>
          <label class="mb-1 block text-sm font-medium text-fg">{{ t('admin.common.description') }}</label>
          <el-input v-model="form.description"/>
        </div>

        <div>
          <label class="mb-1 block text-sm font-medium text-fg">{{
              t('admin.pluginPages.codeSnippets.tagsHint')
            }}</label>
          <el-input v-model="form.tags" :placeholder="t('admin.pluginPages.codeSnippets.tagsPlaceholder')"/>
        </div>

        <div>
          <label class="mb-1 block text-sm font-medium text-fg">{{ t('admin.pluginPages.codeSnippets.code') }}</label>
          <el-input v-model="form.code" :rows="12" type="textarea"/>
        </div>
      </div>

      <template #footer>
        <el-button @click="editorOpen = false">{{ t('admin.common.cancel') }}</el-button>
        <el-button :disabled="!form.title.trim()" :loading="saving" type="primary" @click="saveSnippet">
          {{ t('admin.common.create') }}
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>
