// frontend/web/src/components/site/audio/DesktopLyrics.vue
<script lang="ts" setup>
import {computed, onBeforeUnmount, onMounted, reactive, ref, watch} from 'vue'

import {type LyricLine, tokenizeText} from './helpers'

/**
 * 桌面歌词浮层
 *
 * 对应 astro 版 `components/audio/DesktopLyrics.tsx`：页面右上角（可拖拽）的
 * 独立歌词窗，带渐变配色、字体、字号、不透明度、宽度与入场/出场动画设置，
 * 全部持久化到 localStorage（键 `fastblog_desktop_lyrics`，与原来一致）。
 *
 * 与 astro 版的两点实现差异（行为等价）：
 *  1. 原实现用 framer-motion 的 variants 做入场/出场，这里改用 Vue 的
 *     `<Transition>` + 按预设生成的 CSS keyframes，**不引入动画库**。
 *  2. 原实现的横向滚动（长行跟随当前高亮字平移）用 `transform` 平滑逼近，
 *     这里同样用 `requestAnimationFrame` 逼近，手感一致。
 */

type AnimPreset = 'fade-up' | 'fade-scale' | 'slide-left' | 'slide-right' | 'typewriter'

interface LyricsSettings {
  x: number
  y: number
  fontSize: number
  fontFamily: string
  opacity: number
  gradientId: string
  boxWidth: number
  entryAnim: AnimPreset
  exitAnim: AnimPreset
}

const GRADIENTS: Array<{
  id: string
  label: string
  from: string
  via: string
  to: string
  shadow: string
}> = [
  {id: 'purple-pink', label: '紫粉', from: '#a855f7', via: '#d946ef', to: '#ec4899', shadow: 'rgba(168,85,247,0.5)'},
  {id: 'cyan-blue', label: '青蓝', from: '#06b6d4', via: '#3b82f6', to: '#6366f1', shadow: 'rgba(59,130,246,0.5)'},
  {id: 'green-emerald', label: '翠绿', from: '#34d399', via: '#10b981', to: '#059669', shadow: 'rgba(16,185,129,0.5)'},
  {id: 'orange-rose', label: '暖橙', from: '#fb923c', via: '#f43f5e', to: '#e11d48', shadow: 'rgba(244,63,94,0.5)'},
  {id: 'white-glow', label: '白辉', from: '#ffffff', via: '#e2e8f0', to: '#94a3b8', shadow: 'rgba(255,255,255,0.4)'},
  {id: 'gold-amber', label: '金色', from: '#fbbf24', via: '#f59e0b', to: '#d97706', shadow: 'rgba(245,158,11,0.5)'},
]

const FONTS: Array<{ value: string; label: string }> = [
  {value: 'system-ui, sans-serif', label: '系统'},
  {value: '"PingFang SC", "Microsoft YaHei", sans-serif', label: '雅黑'},
  {value: '"Noto Sans SC", sans-serif', label: 'Noto'},
  {value: '"Songti SC", "SimSun", serif', label: '宋体'},
  {value: '"STKaiti", "KaiTi", serif', label: '楷体'},
  {value: 'monospace', label: '等宽'},
]

const ANIM_PRESETS: Array<{ value: AnimPreset; label: string; desc: string }> = [
  {value: 'fade-up', label: '淡入上移', desc: 'opacity 0→1 + y 20→0'},
  {value: 'fade-scale', label: '淡入缩放', desc: 'opacity 0→1 + scale 0.8→1'},
  {value: 'slide-left', label: '右侧滑入', desc: 'x 40→0 + opacity'},
  {value: 'slide-right', label: '左侧滑入', desc: 'x -40→0 + opacity'},
  {value: 'typewriter', label: '打字机', desc: 'clipPath 逐字展开'},
]

const LS_KEY = 'fastblog_desktop_lyrics'

const DEFAULT_SETTINGS: LyricsSettings = {
  x: 50,
  y: 50,
  fontSize: 18,
  fontFamily: 'system-ui, sans-serif',
  opacity: 90,
  gradientId: 'purple-pink',
  boxWidth: 520,
  entryAnim: 'fade-up',
  exitAnim: 'fade-scale',
}

const props = withDefaults(
  defineProps<{
    lyrics?: LyricLine[]
    activeLineIndex?: number
    karaokeProgress?: number
    visible?: boolean
  }>(),
  {lyrics: () => [], activeLineIndex: -1, karaokeProgress: 0, visible: false},
)

const emit = defineEmits<{ (e: 'visibility-change', visible: boolean): void }>()

function loadSettings(): LyricsSettings {
  try {
    const raw = localStorage.getItem(LS_KEY)
    return raw ? {...DEFAULT_SETTINGS, ...(JSON.parse(raw) as Partial<LyricsSettings>)} : {...DEFAULT_SETTINGS}
  } catch {
    return {...DEFAULT_SETTINGS}
  }
}

const settings = reactive<LyricsSettings>(loadSettings())
const showSettings = ref(false)

/** 设置变更即持久化（与 astro 版一致） */
watch(
  () => ({...settings}),
  (value) => {
    try {
      localStorage.setItem(LS_KEY, JSON.stringify(value))
    } catch {
      // 隐私模式下忽略
    }
  },
  {deep: true},
)

const gradient = computed(
  () => GRADIENTS.find((item) => item.id === settings.gradientId) ?? GRADIENTS[0]!,
)

const currentLyric = computed<LyricLine | null>(
  () => props.lyrics[props.activeLineIndex] ?? null,
)

const tokens = computed(() => (currentLyric.value ? tokenizeText(currentLyric.value.text) : []))

const highlightCount = computed(() =>
  Math.floor(tokens.value.length * props.karaokeProgress),
)

/* ---------------------------------------------------------------- 横向滚动 */

const textRef = ref<HTMLElement | null>(null)
const scrollOffset = ref(0)
let rafId = 0

function tickScroll(): void {
  const textEl = textRef.value
  if (!textEl) {
    scrollOffset.value = 0
    return
  }

  const containerWidth = settings.boxWidth
  const textWidth = textEl.scrollWidth

  if (textWidth <= containerWidth || highlightCount.value <= 0) {
    scrollOffset.value *= 0.85
    if (Math.abs(scrollOffset.value) < 0.5) scrollOffset.value = 0
    return
  }

  const avgTokenWidth = textWidth / Math.max(tokens.value.length, 1)
  const highlightCenter = highlightCount.value * avgTokenWidth
  const maxOffset = Math.max(0, textWidth - containerWidth)
  const target = Math.min(Math.max(0, highlightCenter - containerWidth / 2), maxOffset)

  // 平滑逼近（原实现同样用 0.15 的插值系数）
  scrollOffset.value += (target - scrollOffset.value) * 0.15
}

function loop(): void {
  if (!props.visible) return
  tickScroll()
  rafId = window.requestAnimationFrame(loop)
}

watch(
  () => props.visible,
  (visible) => {
    window.cancelAnimationFrame(rafId)
    if (visible) {
      scrollOffset.value = 0
      rafId = window.requestAnimationFrame(loop)
    }
  },
  {immediate: true},
)

/* ---------------------------------------------------------------- 拖拽 */

const dragging = ref(false)
let drag: { startX: number; startY: number; origX: number; origY: number; moved: boolean } | null = null

function onPointerDown(event: PointerEvent): void {
  if (showSettings.value) return
  drag = {
    startX: event.clientX,
    startY: event.clientY,
    origX: settings.x,
    origY: settings.y,
    moved: false,
  }
  ;(event.currentTarget as HTMLElement).setPointerCapture?.(event.pointerId)
}

function onPointerMove(event: PointerEvent): void {
  if (!drag) return
  const dx = event.clientX - drag.startX
  const dy = event.clientY - drag.startY
  if (Math.abs(dx) > 3 || Math.abs(dy) > 3) {
    drag.moved = true
    dragging.value = true
  }
  if (!drag.moved) return
  settings.x = Math.max(0, Math.min(95, drag.origX + (dx / window.innerWidth) * 100))
  settings.y = Math.max(0, Math.min(90, drag.origY + (dy / window.innerHeight) * 100))
}

function onPointerUp(): void {
  drag = null
  dragging.value = false
}

/* ---------------------------------------------------------------- 交互 */

function stopEvent(event: Event): void {
  event.stopPropagation()
}

function resetPosition(): void {
  settings.x = DEFAULT_SETTINGS.x
  settings.y = DEFAULT_SETTINGS.y
}

function resetAll(): void {
  Object.assign(settings, DEFAULT_SETTINGS)
  showSettings.value = false
}

function onKeydown(event: KeyboardEvent): void {
  if (event.key !== 'Escape' || !props.visible) return
  event.stopPropagation()
  if (showSettings.value) showSettings.value = false
  else emit('visibility-change', false)
}

/** 当前行的入场/出场动画名（对应 astro 版的 entry/exit variants） */
const transitionName = computed(() => `lyric-${settings.entryAnim}`)

onMounted(() => window.addEventListener('keydown', onKeydown, true))

onBeforeUnmount(() => {
  window.removeEventListener('keydown', onKeydown, true)
  window.cancelAnimationFrame(rafId)
})
</script>

<template>
  <div v-if="visible" class="pointer-events-none fixed inset-0 z-[80]">
    <!-- 歌词条 -->
    <div
      :style="{
        left: `${settings.x}%`,
        top: `${settings.y}%`,
        width: `${settings.boxWidth}px`,
        transform: 'translate(-50%, -50%)',
        opacity: settings.opacity / 100,
        padding: '14px 18px',
      }"
      class="pointer-events-auto absolute cursor-move select-none rounded-2xl border border-white/10 bg-black/70 shadow-2xl backdrop-blur-xl"
      @pointercancel="onPointerUp"
      @pointerdown="onPointerDown"
      @pointermove="onPointerMove"
      @pointerup="onPointerUp"
    >
      <!-- 工具条：拖拽时显示，避免遮挡 -->
      <div
        v-if="!dragging"
        class="mb-2 flex items-center justify-between gap-2 text-[11px] text-white/40"
      >
        <span>桌面歌词</span>
        <div class="flex items-center gap-1">
          <button class="rounded px-1.5 py-0.5 hover:bg-white/10 hover:text-white/80" type="button"
                  @click.stop="showSettings = !showSettings">
            设置
          </button>
          <button class="rounded px-1.5 py-0.5 hover:bg-white/10 hover:text-white/80" type="button"
                  @click.stop="emit('visibility-change', false)">
            关闭
          </button>
        </div>
      </div>

      <!-- 歌词正文 -->
      <Transition :name="transitionName" mode="out-in">
        <div
          v-if="currentLyric"
          :key="props.activeLineIndex"
          :style="{
            fontFamily: settings.fontFamily,
            fontSize: `${settings.fontSize}px`,
            lineHeight: 1.5,
          }"
          class="overflow-hidden whitespace-nowrap text-center font-bold"
        >
          <div
            ref="textRef"
            :style="{
              transform: `translateX(${-scrollOffset}px)`,
              transition: dragging ? 'none' : 'transform 120ms linear',
            }"
            class="inline-block"
          >
            <span
              v-for="(token, index) in tokens"
              :key="index"
              :style="
                index < highlightCount
                  ? {
                      backgroundImage: `linear-gradient(to right, ${gradient.from}, ${gradient.via}, ${gradient.to})`,
                      WebkitBackgroundClip: 'text',
                      backgroundClip: 'text',
                      color: 'transparent',
                      filter: `drop-shadow(0 0 10px ${gradient.shadow})`,
                    }
                  : {color: 'rgba(255,255,255,0.5)'}
              "
            >{{ token === ' ' ? ' ' : token }}</span>
          </div>
        </div>

        <div v-else class="py-3 text-center text-sm text-white/40">暂无歌词</div>
      </Transition>

      <!-- 设置面板 -->
      <div
        v-if="showSettings"
        class="mt-3 space-y-3 border-t border-white/10 pt-3 text-[11px] text-white/60"
        @pointerdown.stop
      >
        <div>
          <p class="mb-1.5">配色</p>
          <div class="flex flex-wrap gap-1.5">
            <button
              v-for="item in GRADIENTS"
              :key="item.id"
              :class="item.id === settings.gradientId ? 'ring-2 ring-white/60' : 'ring-1 ring-white/15'"
              :style="{backgroundImage: `linear-gradient(to right, ${item.from}, ${item.via}, ${item.to})`}"
              :title="item.label"
              class="h-6 w-6 rounded-full"
              type="button"
              @click="settings.gradientId = item.id"
            />
          </div>
        </div>

        <div class="grid grid-cols-2 gap-2">
          <label class="flex flex-col gap-1">
            字号 {{ settings.fontSize }}px
            <input v-model.number="settings.fontSize" class="w-full" max="48" min="12" step="1" type="range">
          </label>
          <label class="flex flex-col gap-1">
            不透明度 {{ settings.opacity }}%
            <input v-model.number="settings.opacity" class="w-full" max="100" min="20" step="1" type="range">
          </label>
          <label class="flex flex-col gap-1">
            宽度 {{ settings.boxWidth }}px
            <input v-model.number="settings.boxWidth" class="w-full" max="1200" min="280" step="20" type="range">
          </label>
          <label class="flex flex-col gap-1">
            字体
            <select v-model="settings.fontFamily" class="w-full rounded bg-white/10 px-1 py-0.5">
              <option v-for="font in FONTS" :key="font.value" :value="font.value">{{ font.label }}</option>
            </select>
          </label>
          <label class="flex flex-col gap-1">
            入场动画
            <select v-model="settings.entryAnim" class="w-full rounded bg-white/10 px-1 py-0.5">
              <option v-for="preset in ANIM_PRESETS" :key="preset.value" :value="preset.value">{{
                  preset.label
                }}
              </option>
            </select>
          </label>
          <label class="flex flex-col gap-1">
            出场动画
            <select v-model="settings.exitAnim" class="w-full rounded bg-white/10 px-1 py-0.5">
              <option v-for="preset in ANIM_PRESETS" :key="preset.value" :value="preset.value">{{
                  preset.label
                }}
              </option>
            </select>
          </label>
        </div>

        <div class="flex justify-end gap-2 pt-1">
          <button class="rounded border border-white/15 px-2 py-1 hover:bg-white/10" type="button"
                  @click="resetPosition">重置位置
          </button>
          <button class="rounded border border-white/15 px-2 py-1 hover:bg-white/10" type="button" @click="resetAll">
            恢复默认
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
/* 入场动画（对应 astro 版 entryVariants 的 5 种预设） */
.lyric-fade-up-enter-from {
  opacity: 0;
  transform: translateY(20px);
  filter: blur(4px);
}

.lyric-fade-scale-enter-from {
  opacity: 0;
  transform: scale(0.8);
  filter: blur(3px);
}

.lyric-slide-left-enter-from {
  opacity: 0;
  transform: translateX(40px);
}

.lyric-slide-right-enter-from {
  opacity: 0;
  transform: translateX(-40px);
}

.lyric-typewriter-enter-from {
  opacity: 0;
  clip-path: inset(0 100% 0 0);
}

.lyric-fade-up-enter-active,
.lyric-fade-scale-enter-active,
.lyric-slide-left-enter-active,
.lyric-slide-right-enter-active,
.lyric-typewriter-enter-active {
  transition: all 320ms ease;
}

/* 出场统一为轻微淡出，避免不同预设交错时抖动 */
.lyric-fade-up-leave-to,
.lyric-fade-scale-leave-to,
.lyric-slide-left-leave-to,
.lyric-slide-right-leave-to,
.lyric-typewriter-leave-to {
  opacity: 0;
}

.lyric-fade-up-leave-active,
.lyric-fade-scale-leave-active,
.lyric-slide-left-leave-active,
.lyric-slide-right-leave-active,
.lyric-typewriter-leave-active {
  transition: opacity 200ms ease;
}

@media (prefers-reduced-motion: reduce) {
  [class*='lyric-'][class*='-enter-active'],
  [class*='lyric-'][class*='-leave-active'] {
    transition: none;
  }
}
</style>

// frontend-astro/src/components/audio/DesktopLyrics.tsx
'use client';

import React, {useCallback, useEffect, useRef, useState, useMemo} from 'react';
import {motion, AnimatePresence} from 'framer-motion';

/* ---------- Types ---------- */

interface LyricLine {
  time: number;
  text: string;
}

type AnimPreset = 'fade-up' | 'fade-scale' | 'slide-left' | 'slide-right' | 'typewriter';

interface LyricsSettings {
  x: number;
  y: number;
  fontSize: number;
  fontFamily: string;
  opacity: number;
  gradientId: string;
  boxWidth: number;           // 容器宽度 px
  entryAnim: AnimPreset;      // 入场动画预设
  exitAnim: AnimPreset;       // 退场动画预设
}

const GRADIENTS: { id: string; label: string; from: string; via: string; to: string; shadow: string }[] = [
  {id: 'purple-pink', label: '紫粉', from: '#a855f7', via: '#d946ef', to: '#ec4899', shadow: 'rgba(168,85,247,0.5)'},
  {id: 'cyan-blue', label: '青蓝', from: '#06b6d4', via: '#3b82f6', to: '#6366f1', shadow: 'rgba(59,130,246,0.5)'},
  {id: 'green-emerald', label: '翠绿', from: '#34d399', via: '#10b981', to: '#059669', shadow: 'rgba(16,185,129,0.5)'},
  {id: 'orange-rose', label: '暖橙', from: '#fb923c', via: '#f43f5e', to: '#e11d48', shadow: 'rgba(244,63,94,0.5)'},
  {id: 'white-glow', label: '白辉', from: '#ffffff', via: '#e2e8f0', to: '#94a3b8', shadow: 'rgba(255,255,255,0.4)'},
  {id: 'gold-amber', label: '金色', from: '#fbbf24', via: '#f59e0b', to: '#d97706', shadow: 'rgba(245,158,11,0.5)'},
];

const FONTS: { value: string; label: string }[] = [
  {value: 'system-ui, sans-serif', label: '系统'},
  {value: '"PingFang SC", "Microsoft YaHei", sans-serif', label: '雅黑'},
  {value: '"Noto Sans SC", sans-serif', label: 'Noto'},
  {value: '"Songti SC", "SimSun", serif', label: '宋体'},
  {value: '"STKaiti", "KaiTi", serif', label: '楷体'},
  {value: 'monospace', label: '等宽'},
];

const ANIM_PRESETS: { value: AnimPreset; label: string; desc: string }[] = [
  {value: 'fade-up', label: '淡入上移', desc: 'opacity 0→1 + y 16→0'},
  {value: 'fade-scale', label: '淡入缩放', desc: 'opacity 0→1 + scale 0.8→1'},
  {value: 'slide-left', label: '右侧滑入', desc: 'x 40→0 + opacity'},
  {value: 'slide-right', label: '左侧滑入', desc: 'x -40→0 + opacity'},
  {value: 'typewriter', label: '打字机', desc: 'clipPath 逐字展开'},
];

const LS_KEY = 'fastblog_desktop_lyrics';
const DEFAULT_SETTINGS: LyricsSettings = {
  x: 50, y: 50, fontSize: 18, fontFamily: 'system-ui, sans-serif', opacity: 90, gradientId: 'purple-pink',
  boxWidth: 520, entryAnim: 'fade-up', exitAnim: 'fade-scale',
};

function loadSettings(): LyricsSettings {
  try {
    const raw = localStorage.getItem(LS_KEY);
    return raw ? {...DEFAULT_SETTINGS, ...JSON.parse(raw)} : DEFAULT_SETTINGS;
  } catch { return DEFAULT_SETTINGS; }
}

function saveSettings(s: LyricsSettings) {
  localStorage.setItem(LS_KEY, JSON.stringify(s));
}

/* ---------- Tokenize (shared) ---------- */

function tokenizeText(text: string): string[] {
  const tokens: string[] = [];
  let buf = '';
  for (const ch of text) {
    const isCJK = /[\u4e00-\u9fff\u3400-\u4dbf\uf900-\ufaff]/.test(ch);
    if (isCJK) {
      if (buf) { tokens.push(buf); buf = ''; }
      tokens.push(ch);
    } else if (ch === ' ') {
      if (buf) { tokens.push(buf); buf = ''; }
      tokens.push(' ');
    } else {
      buf += ch;
    }
  }
  if (buf) tokens.push(buf);
  return tokens;
}

/* ---------- Entry / Exit animation variants ---------- */

function entryVariants(preset: AnimPreset) {
  switch (preset) {
    case 'fade-up':
      return {initial: {opacity: 0, y: 20, filter: 'blur(4px)'}, animate: {opacity: 1, y: 0, filter: 'blur(0px)'}};
    case 'fade-scale':
      return {initial: {opacity: 0, scale: 0.8, filter: 'blur(3px)'}, animate: {opacity: 1, scale: 1, filter: 'blur(0px)'}};
    case 'slide-left':
      return {initial: {opacity: 0, x: 40}, animate: {opacity: 1, x: 0}};
    case 'slide-right':
      return {initial: {opacity: 0, x: -40}, animate: {opacity: 1, x: 0}};
    case 'typewriter':
      return {initial: {opacity: 0, clipPath: 'inset(0 100% 0 0)'}, animate: {opacity: 1, clipPath: 'inset(0 0% 0 0)'}};
  }
}

function exitVariants(preset: AnimPreset) {
  switch (preset) {
    case 'fade-up':
      return {exit: {opacity: 0, y: -16, scale: 0.95, filter: 'blur(3px)'}};
    case 'fade-scale':
      return {exit: {opacity: 0, scale: 0.85, filter: 'blur(4px)'}};
    case 'slide-left':
      return {exit: {opacity: 0, x: -30}};
    case 'slide-right':
      return {exit: {opacity: 0, x: 30}};
    case 'typewriter':
      return {exit: {opacity: 0, clipPath: 'inset(0 0% 0 100%)'}};
  }
}

/* ========== Settings Panel ========== */

const SettingsPanel: React.FC<{
  settings: LyricsSettings;
  onChange: (s: LyricsSettings) => void;
  onClose: () => void;
  prevLyric: string | null;
  nextLyric: string | null;
}> = ({settings, onChange, onClose, prevLyric, nextLyric}) => {
  return (
      <motion.div
          initial={{opacity: 0, y: 10, scale: 0.95}}
          animate={{opacity: 1, y: 0, scale: 1}}
          exit={{opacity: 0, y: 10, scale: 0.95}}
          className="fixed bottom-6 right-6 z-[70] bg-neutral-900/95 backdrop-blur-2xl rounded-2xl border border-white/10 shadow-2xl p-4 w-80 max-h-[80vh] overflow-y-auto"
          onClick={e => e.stopPropagation()}
      >
        <div className="flex items-center justify-between mb-3">
          <span className="text-white text-sm font-semibold">桌面歌词设置</span>
          <button onClick={onClose} className="w-6 h-6 rounded-full bg-white/10 hover:bg-white/20 flex items-center justify-center text-white/50 text-xs">✕</button>
        </div>

        {/* ── 容器宽度 ── */}
        <div className="mb-3">
          <label className="text-white/50 text-xs block mb-1">歌词框宽度 ({settings.boxWidth}px)</label>
          <input type="range" min={260} max={900} step={10} value={settings.boxWidth}
                 onChange={e => onChange({...settings, boxWidth: parseInt(e.target.value)})}
                 className="w-full h-1 bg-white/20 rounded-full appearance-none cursor-pointer accent-purple-500"
                 style={{background: `linear-gradient(to right, #a855f7 ${(settings.boxWidth-260)/(900-260)*100}%, rgba(255,255,255,0.15) ${(settings.boxWidth-260)/(900-260)*100}%)`}}
          />
          <div className="flex justify-between text-[10px] text-white/30 mt-0.5"><span>260</span><span>900</span></div>
        </div>

        {/* ── 字号 ── */}
        <div className="mb-3">
          <label className="text-white/50 text-xs block mb-1">字号</label>
          <div className="flex items-center gap-2">
            <button onClick={() => onChange({...settings, fontSize: Math.max(12, settings.fontSize - 1)})}
                    className="w-8 h-8 rounded-lg bg-white/10 hover:bg-white/20 text-white/80 text-sm font-bold">A−</button>
            <span className="text-white text-sm text-center w-10 tabular-nums">{settings.fontSize}</span>
            <button onClick={() => onChange({...settings, fontSize: Math.min(40, settings.fontSize + 1)})}
                    className="w-8 h-8 rounded-lg bg-white/10 hover:bg-white/20 text-white/80 text-sm font-bold">A+</button>
          </div>
        </div>

        {/* ── 字体 ── */}
        <div className="mb-3">
          <label className="text-white/50 text-xs block mb-1">字体</label>
          <div className="flex flex-wrap gap-1.5">
            {FONTS.map(f => (
                <button key={f.value}
                        onClick={() => onChange({...settings, fontFamily: f.value})}
                        className={`px-3 py-1.5 rounded-lg text-xs transition-colors ${
                            settings.fontFamily === f.value
                                ? 'bg-purple-600/40 text-purple-300 border border-purple-500/40'
                                : 'bg-white/10 hover:bg-white/20 text-white/70 border border-transparent'
                        }`}
                        style={{fontFamily: f.value}}
                >{f.label}</button>
            ))}
          </div>
        </div>

        {/* ── 高亮颜色 ── */}
        <div className="mb-3">
          <label className="text-white/50 text-xs block mb-1">高亮颜色</label>
          <div className="flex flex-wrap gap-1.5">
            {GRADIENTS.map(g => (
                <button key={g.id}
                        onClick={() => onChange({...settings, gradientId: g.id})}
                        className={`w-7 h-7 rounded-full transition-all ${
                            settings.gradientId === g.id ? 'ring-2 ring-white scale-110' : ''
                        }`}
                        style={{background: `linear-gradient(135deg, ${g.from}, ${g.via}, ${g.to})`}}
                        title={g.label}
                />
            ))}
          </div>
        </div>

        {/* ── 透明度 ── */}
        <div className="mb-3">
          <label className="text-white/50 text-xs block mb-1">透明度 ({settings.opacity}%)</label>
          <input type="range" min={30} max={100} value={settings.opacity}
                 onChange={e => onChange({...settings, opacity: parseInt(e.target.value)})}
                 className="w-full h-1 bg-white/20 rounded-full appearance-none cursor-pointer accent-purple-500"
                 style={{background: `linear-gradient(to right, #a855f7 ${settings.opacity}%, rgba(255,255,255,0.15) ${settings.opacity}%)`}}
          />
        </div>

        {/* ── 入场动画 ── */}
        <div className="mb-3">
          <label className="text-white/50 text-xs block mb-1">入场动画</label>
          <div className="grid grid-cols-2 gap-1.5">
            {ANIM_PRESETS.map(a => (
                <button key={a.value}
                        onClick={() => onChange({...settings, entryAnim: a.value})}
                        className={`px-2 py-1.5 rounded-lg text-xs transition-colors text-left ${
                            settings.entryAnim === a.value
                                ? 'bg-purple-600/40 text-purple-300 border border-purple-500/40'
                                : 'bg-white/10 hover:bg-white/20 text-white/60 border border-transparent'
                        }`}
                >
                  <div className="font-medium">{a.label}</div>
                  <div className="text-[10px] opacity-60 mt-0.5">{a.desc}</div>
                </button>
            ))}
          </div>
        </div>

        {/* ── 退场动画 ── */}
        <div className="mb-3">
          <label className="text-white/50 text-xs block mb-1">退场动画</label>
          <div className="grid grid-cols-2 gap-1.5">
            {ANIM_PRESETS.map(a => (
                <button key={a.value}
                        onClick={() => onChange({...settings, exitAnim: a.value})}
                        className={`px-2 py-1.5 rounded-lg text-xs transition-colors text-left ${
                            settings.exitAnim === a.value
                                ? 'bg-purple-600/40 text-purple-300 border border-purple-500/40'
                                : 'bg-white/10 hover:bg-white/20 text-white/60 border border-transparent'
                        }`}
                >
                  <div className="font-medium">{a.label}</div>
                  <div className="text-[10px] opacity-60 mt-0.5">{a.desc}</div>
                </button>
            ))}
          </div>
        </div>

        {/* ── 歌词预览 ── */}
        <div className="border-t border-white/10 pt-3 mt-1">
          <label className="text-white/50 text-xs block mb-2">预览</label>
          <div className="space-y-2 text-center" style={{fontFamily: settings.fontFamily}}>
            {prevLyric && (
                <p className="text-white/30 text-xs truncate" style={{fontSize: settings.fontSize - 4}}>{prevLyric}</p>
            )}
            {nextLyric && (
                <p className="text-white/60 text-sm truncate" style={{fontSize: settings.fontSize}}>{nextLyric}</p>
            )}
          </div>
        </div>
      </motion.div>
  );
};

/* ========== DesktopLyrics ========== */

const DesktopLyrics: React.FC<{
  lyrics: LyricLine[];
  activeLineIndex: number;
  karaokeProgress: number;
  visible: boolean;
  onVisibilityChange: (v: boolean) => void;
}> = ({lyrics, activeLineIndex, karaokeProgress, visible, onVisibilityChange}) => {
  const [settings, setSettings] = useState<LyricsSettings>(loadSettings);
  const [showSettings, setShowSettings] = useState(false);
  const [prevActiveIndex, setPrevActiveIndex] = useState(-1);
  const containerRef = useRef<HTMLDivElement>(null);
  const textRef = useRef<HTMLDivElement>(null);
  const [scrollOffset, setScrollOffset] = useState(0);
  const dragRef = useRef<{startX: number; startY: number; origX: number; origY: number; dragging: boolean} | null>(null);

  useEffect(() => { saveSettings(settings); }, [settings]);

  // 跟踪上一行索引
  useEffect(() => {
    if (activeLineIndex >= 0 && activeLineIndex !== prevActiveIndex) {
      setPrevActiveIndex(activeLineIndex);
      setScrollOffset(0); // 换行时重置滚动
    }
  }, [activeLineIndex, prevActiveIndex]);

  // ESC
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        if (showSettings) setShowSettings(false);
        else onVisibilityChange(false);
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [showSettings, onVisibilityChange]);

  // ── Karaoke 横向滚动 ──
  // 根据 karaokeProgress 计算 translateX，使当前高亮词始终位于容器中心
  useEffect(() => {
    if (!textRef.current || !containerRef.current) return;
    const textEl = textRef.current;
    const containerWidth = settings.boxWidth;
    const textWidth = textEl.scrollWidth;

    if (textWidth <= containerWidth) {
      setScrollOffset(0);
      return;
    }

    const tokens = currentLyric ? tokenizeText(currentLyric.text) : [];
    if (!tokens.length) { setScrollOffset(0); return; }

    // 找到当前高亮 token 的位置（累计宽度）
    const highlightCount = Math.floor(tokens.length * karaokeProgress);
    if (highlightCount <= 0) { setScrollOffset(0); return; }

    // 估算每个 token 的平均宽度（基于总宽度）
    const avgTokenWidth = textWidth / tokens.length;
    const highlightCenter = highlightCount * avgTokenWidth;
    const targetOffset = Math.max(0, highlightCenter - containerWidth / 2);

    // 限制不能超出文本范围
    const maxOffset = Math.max(0, textWidth - containerWidth);
    const clamped = Math.min(targetOffset, maxOffset);

    // 平滑滚动
    setScrollOffset(prev => {
      const diff = clamped - prev;
      if (Math.abs(diff) < 2) return clamped;
      return prev + diff * 0.15; // lerp
    });
  });

  // 拖拽
  const onPointerDown = useCallback((e: React.PointerEvent) => {
    dragRef.current = {
      startX: e.clientX, startY: e.clientY,
      origX: settings.x, origY: settings.y,
      dragging: false,
    };
    (e.target as HTMLElement).setPointerCapture(e.pointerId);
  }, [settings.x, settings.y]);

  const onPointerMove = useCallback((e: React.PointerEvent) => {
    if (!dragRef.current) return;
    const dx = e.clientX - dragRef.current.startX;
    const dy = e.clientY - dragRef.current.startY;
    if (Math.abs(dx) > 3 || Math.abs(dy) > 3) dragRef.current.dragging = true;
    setSettings(s => ({
      ...s,
      x: Math.max(0, Math.min(95, dragRef.current!.origX + dx / window.innerWidth * 100)),
      y: Math.max(0, Math.min(90, dragRef.current!.origY + dy / window.innerHeight * 100)),
    }));
  }, []);

  const onPointerUp = useCallback(() => { dragRef.current = null; }, []);

  if (!visible || !lyrics.length) return null;

  const currentLyric = activeLineIndex >= 0 ? lyrics[activeLineIndex] : null;
  const prevLyric = activeLineIndex > 0 ? lyrics[activeLineIndex - 1] : null;
  const nextLyric = activeLineIndex >= 0 && activeLineIndex + 1 < lyrics.length ? lyrics[activeLineIndex + 1] : null;
  const gradient = GRADIENTS.find(g => g.id === settings.gradientId) ?? GRADIENTS[0];

  // 当前行高亮 tokens
  const highlightedTokens = useMemo(() => {
    if (!currentLyric) return [];
    const tokens = tokenizeText(currentLyric.text);
    const highlightCount = Math.floor(tokens.length * karaokeProgress);
    return tokens.map((t, i) => ({
      token: t,
      highlighted: i < highlightCount,
      transitioning: i === highlightCount - 1 && karaokeProgress < 1,
      clipProgress: i === highlightCount - 1 && karaokeProgress < 1
          ? (karaokeProgress * tokens.length - i)
          : (i < highlightCount ? 1 : 0),
    }));
  }, [currentLyric, karaokeProgress]);

  const entryV = entryVariants(settings.entryAnim);
  const exitV = exitVariants(settings.exitAnim);
  const entryTrans = {duration: 0.4, ease: [0.16, 1, 0.3, 1]};
  const exitTrans = {duration: 0.35, ease: 'easeOut'};
  const nextTrans = {duration: 0.4, delay: 0.15, ease: 'easeOut'};

  return (
      <>
        {/* ── 歌词容器（固定宽，可拖拽） ── */}
        <motion.div
            ref={containerRef}
            className="fixed z-[65] select-none touch-none"
            style={{
              left: `${settings.x}%`,
              top: `${settings.y}%`,
              transform: 'translate(-50%, -50%)',
            }}
            initial={{opacity: 0, scale: 0.9}}
            animate={{opacity: settings.opacity / 100, scale: 1}}
            transition={{duration: 0.25}}
            onPointerDown={onPointerDown}
            onPointerMove={onPointerMove}
            onPointerUp={onPointerUp}
            onDoubleClick={() => onVisibilityChange(false)}
        >
          <div
              className="bg-black/55 backdrop-blur-2xl rounded-2xl px-6 py-5 border border-white/8 shadow-2xl text-center leading-relaxed cursor-grab active:cursor-grabbing transition-shadow hover:shadow-purple-500/5 overflow-hidden"
              style={{
                width: `${settings.boxWidth}px`,
                minWidth: '260px',
                maxWidth: '900px',
              }}
          >
            {/* 上一行 */}
            <AnimatePresence mode="popLayout">
              {prevLyric && activeLineIndex > 0 && prevActiveIndex === activeLineIndex - 1 && (
                  <motion.p
                      key={`prev-${activeLineIndex}`}
                      initial={{opacity: 1, y: 0}}
                      animate={{opacity: 0.25, y: -8}}
                      exit={{opacity: 0, ...exitV.exit, transition: exitTrans}}
                      transition={{duration: 0.35, ease: 'easeOut'}}
                      className="text-white/40 text-sm truncate mb-2"
                      style={{fontSize: Math.max(12, settings.fontSize - 4), fontFamily: settings.fontFamily}}
                  >
                    {prevLyric.text}
                  </motion.p>
              )}
            </AnimatePresence>

            {/* 当前行（横向滚动容器） */}
            <div className="relative overflow-hidden" style={{height: `${settings.fontSize * 1.6}px`}}>
              <motion.div
                  ref={textRef}
                  key={`curr-${activeLineIndex}`}
                  initial={{...entryV.initial}}
                  animate={{...entryV.animate, x: -scrollOffset}}
                  exit={{...exitV.exit, transition: exitTrans}}
                  transition={entryTrans}
                  className="absolute inset-0 flex items-center justify-center font-bold tracking-wide whitespace-nowrap"
                  style={{fontFamily: settings.fontFamily, fontSize: `${settings.fontSize}px`}}
              >
                {currentLyric ? (
                    highlightedTokens.map((item, ti) => {
                      if (item.token === ' ') return <span key={ti} className="inline-block" style={{width: '0.3em'}}>&nbsp;</span>;
                      return (
                          <span key={ti} className="relative inline-block mx-[0.5px]">
                        <span className={item.highlighted ? 'text-transparent' : 'text-white/60'}>{item.token}</span>
                            {item.highlighted && (
                                <span className="absolute inset-0 bg-clip-text text-transparent"
                                      style={{
                                        background: `linear-gradient(135deg, ${gradient.from}, ${gradient.via}, ${gradient.to})`,
                                        WebkitBackgroundClip: 'text',
                                        filter: `drop-shadow(0 0 ${settings.fontSize > 20 ? 12 : 8}px ${gradient.shadow})`,
                                      }}
                                >{item.token}</span>
                            )}
                            {item.transitioning && (
                                <span className="absolute inset-0 overflow-hidden" style={{color: 'transparent'}}>
                              <span className="absolute inset-0 bg-clip-text text-transparent"
                                    style={{
                                      background: `linear-gradient(135deg, ${gradient.from}, ${gradient.via}, ${gradient.to})`,
                                      WebkitBackgroundClip: 'text',
                                      clipPath: `inset(0 ${(1 - item.clipProgress) * 100}% 0 0)`,
                                      filter: `drop-shadow(0 0 ${settings.fontSize > 20 ? 14 : 10}px ${gradient.shadow})`,
                                    }}
                              >{item.token}</span>
                            </span>
                            )}
                      </span>
                      );
                    })
                ) : (
                    <span className="text-white/30">等待播放...</span>
                )}
              </motion.div>
            </div>

            {/* 下一行 */}
            <AnimatePresence mode="popLayout">
              {nextLyric && activeLineIndex >= 0 && (
                  <motion.p
                      key={`next-${activeLineIndex}`}
                      initial={{opacity: 0, y: 12}}
                      animate={{opacity: 0.3, y: 6}}
                      exit={{opacity: 0, y: 20}}
                      transition={nextTrans}
                      className="text-white/25 text-sm truncate mt-2"
                      style={{fontSize: Math.max(11, settings.fontSize - 6), fontFamily: settings.fontFamily}}
                  >
                    {nextLyric.text}
                  </motion.p>
              )}
            </AnimatePresence>
          </div>

          {/* ── 悬停控制条 ── */}
          <div className="flex items-center justify-center gap-2 mt-2 opacity-0 hover:opacity-100 transition-opacity duration-200" style={{pointerEvents: 'auto'}}>
            <button onClick={() => onVisibilityChange(false)}
                    className="w-7 h-7 rounded-full bg-black/50 backdrop-blur border border-white/10 hover:bg-white/15 flex items-center justify-center text-white/50 text-xs transition-colors"
                    title="关闭桌面歌词">✕</button>
            <button onClick={() => setShowSettings(v => !v)}
                    className={`w-7 h-7 rounded-full backdrop-blur border flex items-center justify-center text-xs transition-colors ${
                        showSettings ? 'bg-purple-600/40 border-purple-500/40 text-purple-300' : 'bg-black/50 border-white/10 hover:bg-white/15 text-white/50'
                    }`}
                    title="歌词设置">
              <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.066 2.573c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.573 1.066c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.066-2.573c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"/>
                <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>
              </svg>
            </button>
          </div>
        </motion.div>

        {/* ── 设置面板 ── */}
        <AnimatePresence>
          {showSettings && (
              <SettingsPanel
                  settings={settings}
                  onChange={setSettings}
                  onClose={() => setShowSettings(false)}
                  prevLyric={prevLyric?.text ?? null}
                  nextLyric={nextLyric?.text ?? null}
              />
          )}
        </AnimatePresence>
      </>
  );
};

export default DesktopLyrics;
export {tokenizeText, GRADIENTS, FONTS, ANIM_PRESETS};
export type {LyricsSettings, LyricLine, AnimPreset};
