// plugins/compliance-audit/frontend/admin/Page.tsx
'use client';

import React, {useState} from 'react';
import {useMutation, useQuery} from '@tanstack/react-query';
import {AdminShell} from '@/components/admin/AdminShell';
import {apiClient} from '@/lib/api/base-client';
import {CheckCircle2, Loader2, RefreshCw, Shield, ShieldAlert, ShieldCheck, XCircle} from 'lucide-react';

const PLUGIN_SLUG = 'compliance-audit';

function call(action: string, params: any = {}) {
  return apiClient.post(`/plugins/${PLUGIN_SLUG}/action`, {action, params});
}

interface CheckItem {
  id: number;
  name: string;
  status: 'compliant' | 'non-compliant' | 'not_audited';
  detail: string;
}

interface AuditReport {
  overall_status: string;
  checked_at: string;
  checks: CheckItem[];
}

function ComplianceAuditDashboard() {
  const [userId, setUserId] = useState('');

  const {data: report, isLoading, refetch} = useQuery({
    queryKey: ['compliance-audit'],
    queryFn: async () => {
      const r = await call('check_pci_dss');
      return r.data as AuditReport;
    },
  });

  const auditUserMut = useMutation({
    mutationFn: () => call('check_gdpr', {user_data: {user_id: parseInt(userId, 10) || 0}}),
    onSuccess: () => refetch(),
  });

  const statusIcon = (status: string) => {
    switch (status) {
      case 'compliant':
        return <CheckCircle2 className="w-5 h-5 text-green-500"/>;
      case 'non-compliant':
        return <XCircle className="w-5 h-5 text-red-500"/>;
      default:
        return <Shield className="w-5 h-5 text-gray-400"/>;
    }
  };

  const statusLabel = (status: string) => {
    switch (status) {
      case 'compliant':
        return '合规';
      case 'non-compliant':
        return '不合规';
      default:
        return '未审计';
    }
  };

  const statusColor = (status: string) => {
    switch (status) {
      case 'compliant':
        return 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400';
      case 'non-compliant':
        return 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400';
      default:
        return 'bg-gray-100 text-gray-500 dark:bg-gray-800 dark:text-gray-400';
    }
  };

  return (
    <AdminShell title="合规审计" actions={
      <button onClick={() => refetch()} disabled={isLoading}
              className="flex items-center gap-1.5 px-4 py-2 border rounded-lg text-sm hover:bg-gray-50 dark:hover:bg-gray-800 disabled:opacity-50">
        <RefreshCw className={`w-4 h-4 ${isLoading ? 'animate-spin' : ''}`}/> 重新审计
      </button>
    }>
      {/* 总体状态 */}
      <div
        className={`mb-6 p-5 rounded-xl border ${report?.overall_status === 'compliant' ? 'bg-green-50 dark:bg-green-900/10 border-green-200 dark:border-green-800' : 'bg-red-50 dark:bg-red-900/10 border-red-200 dark:border-red-800'}`}>
        <div className="flex items-center gap-3">
          {report?.overall_status === 'compliant'
            ? <ShieldCheck className="w-8 h-8 text-green-600 dark:text-green-400"/>
            : <ShieldAlert className="w-8 h-8 text-red-600 dark:text-red-400"/>}
          <div>
            <p className="text-lg font-semibold">
              整体状态：{report?.overall_status === 'compliant' ? '合规' : '不合规'}
            </p>
            <p
              className="text-sm text-gray-500">审计时间：{report?.checked_at ? new Date(report.checked_at).toLocaleString() : '—'}</p>
          </div>
        </div>
      </div>

      {/* 审计项目列表 */}
      {isLoading ? (
        <div className="flex justify-center py-16"><Loader2 className="w-8 h-8 animate-spin text-blue-500"/></div>
      ) : !report?.checks?.length ? (
        <div className="text-center py-16 text-gray-400">
          <Shield className="w-12 h-12 mx-auto mb-4 opacity-50"/>
          <p className="text-sm">暂无审计数据</p>
        </div>
      ) : (
        <div className="bg-white dark:bg-gray-900 rounded-xl border overflow-hidden">
          <div className="divide-y dark:divide-gray-800">
            {report.checks.map((check) => (
              <div key={check.id} className="flex items-start gap-4 px-5 py-4">
                {statusIcon(check.status)}
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-gray-900 dark:text-white">{check.name}</p>
                  <p className="text-xs text-gray-400 mt-0.5">{check.detail}</p>
                </div>
                <span
                  className={`px-2.5 py-0.5 rounded-full text-xs font-medium whitespace-nowrap ${statusColor(check.status)}`}>
                  {statusLabel(check.status)}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* 用户审计输入 */}
      <div className="mt-6 p-5 bg-white dark:bg-gray-900 rounded-xl border">
        <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">审计特定用户数据</h3>
        <div className="flex gap-3">
          <input value={userId} onChange={e => setUserId(e.target.value)}
                 placeholder="输入用户ID"
                 className="flex-1 max-w-xs px-3 py-2 border rounded-lg text-sm bg-white dark:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500"/>
          <button onClick={() => auditUserMut.mutate()} disabled={auditUserMut.isPending || !userId}
                  className="px-4 py-2 bg-blue-600 text-white text-sm rounded-lg hover:bg-blue-700 disabled:opacity-50">
            {auditUserMut.isPending ? '审计中...' : '审计'}
          </button>
        </div>
        {auditUserMut.data && (
          <div className="mt-3 p-3 bg-gray-50 dark:bg-gray-800 rounded-lg text-xs text-gray-600 dark:text-gray-400">
            <pre className="whitespace-pre-wrap">{JSON.stringify(auditUserMut.data, null, 2)}</pre>
          </div>
        )}
      </div>
    </AdminShell>
  );
}

export default function ComplianceAuditPage() {
  return <ComplianceAuditDashboard/>;
}

// plugins/compliance-audit/frontend/admin/Page.vue
<script lang="ts" setup>
import {computed, onMounted, ref} from 'vue'

import {pluginAction} from '@/utils/pluginAction'

/**
 * 合规审计（compliance-audit 插件后台页）
 *
 * 对应 `plugins/compliance-audit/frontend/admin/Page.tsx`：
 * 默认跑一次 PCI-DSS 检查，另可按用户 ID 单独跑一遍 GDPR 检查。
 */
interface CheckItem {
  id: number
  name: string
  status: 'compliant' | 'non-compliant' | 'not_audited' | string
  detail: string
}

interface AuditReport {
  overall_status: string
  checked_at: string
  checks: CheckItem[]
}

const loading = ref(true)
const error = ref('')
const report = ref<AuditReport | null>(null)

const userId = ref('')
const auditing = ref(false)
const auditResult = ref<unknown>(null)

const isCompliant = computed(() => report.value?.overall_status === 'compliant')

async function loadReport(): Promise<void> {
  loading.value = true
  error.value = ''
  try {
    const result = await pluginAction<AuditReport>('compliance-audit', 'check_pci_dss')
    report.value = result.data
    if (!result.success) error.value = result.error || '审计失败'
  } finally {
    loading.value = false
  }
}

async function auditUser(): Promise<void> {
  const id = Number.parseInt(userId.value, 10) || 0
  if (!id) return
  auditing.value = true
  try {
    const result = await pluginAction('compliance-audit', 'check_gdpr', {user_data: {user_id: id}})
    auditResult.value = result.data
    await loadReport()
  } finally {
    auditing.value = false
  }
}

function statusIcon(status: string): string {
  if (status === 'compliant') return 'circle-check'
  if (status === 'non-compliant') return 'circle-x'
  return 'shield'
}

function statusLabel(status: string): string {
  if (status === 'compliant') return '合规'
  if (status === 'non-compliant') return '不合规'
  return '未审计'
}

function statusColor(status: string): string {
  if (status === 'compliant') return 'text-success'
  if (status === 'non-compliant') return 'text-danger'
  return 'text-fg-subtle'
}

function statusBadge(status: string): string {
  if (status === 'compliant') return 'bg-success-soft text-success'
  if (status === 'non-compliant') return 'bg-danger-soft text-danger'
  return 'bg-surface-soft text-fg-muted'
}

function formatTime(value?: string): string {
  if (!value) return '—'
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? '—' : date.toLocaleString()
}

onMounted(loadReport)
</script>

<template>
  <div class="p-4">
    <div class="mb-3 flex items-center justify-end">
      <el-button :loading="loading" size="small" @click="loadReport">
        <Icon class="mr-1 h-3.5 w-3.5" name="refresh-cw"/>
        重新审计
      </el-button>
    </div>

    <p v-if="error" class="mb-3 rounded-control bg-danger-soft px-3 py-2 text-sm text-danger">{{ error }}</p>

    <!-- 总体状态 -->
    <div
      :class="isCompliant ? 'border-success bg-success-soft' : 'border-danger bg-danger-soft'"
      class="mb-6 rounded-card border p-5"
    >
      <div class="flex items-center gap-3">
        <Icon
          :class="isCompliant ? 'text-success' : 'text-danger'"
          :name="isCompliant ? 'shield-check' : 'shield-alert'"
          class="h-8 w-8"
        />
        <div>
          <p class="text-lg font-semibold text-fg">整体状态：{{ isCompliant ? '合规' : '不合规' }}</p>
          <p class="text-sm text-fg-muted">审计时间：{{ formatTime(report?.checked_at) }}</p>
        </div>
      </div>
    </div>

    <!-- 审计项 -->
    <div v-if="loading" class="space-y-3">
      <Skeleton v-for="i in 4" :key="i" class="h-16 w-full"/>
    </div>

    <EmptyState
      v-else-if="!report?.checks?.length"
      description="点击右上角「重新审计」触发一次检查"
      title="暂无审计数据"
    />

    <div v-else class="overflow-hidden rounded-card border border-line bg-surface">
      <div class="divide-y divide-line">
        <div v-for="check in report.checks" :key="check.id" class="flex items-start gap-4 px-5 py-4">
          <Icon :class="statusColor(check.status)" :name="statusIcon(check.status)" class="mt-0.5 h-5 w-5 shrink-0"/>
          <div class="min-w-0 flex-1">
            <p class="text-sm font-medium text-fg">{{ check.name }}</p>
            <p class="mt-0.5 text-xs text-fg-subtle">{{ check.detail }}</p>
          </div>
          <span
            :class="statusBadge(check.status)"
            class="whitespace-nowrap rounded-pill px-2.5 py-0.5 text-xs font-medium"
          >{{ statusLabel(check.status) }}</span>
        </div>
      </div>
    </div>

    <!-- 按用户审计 -->
    <div class="mt-6 rounded-card border border-line bg-surface p-5">
      <h3 class="mb-3 text-sm font-semibold text-fg">审计特定用户数据</h3>
      <div class="flex gap-3">
        <el-input v-model="userId" class="max-w-xs" placeholder="输入用户 ID" @keyup.enter="auditUser"/>
        <el-button :disabled="!userId" :loading="auditing" type="primary" @click="auditUser">
          {{ auditing ? '审计中…' : '审计' }}
        </el-button>
      </div>
      <pre
        v-if="auditResult"
        class="mt-3 overflow-auto rounded-control bg-surface-soft p-3 text-xs text-fg-muted"
      >{{ JSON.stringify(auditResult, null, 2) }}</pre>
    </div>
  </div>
</template>
