// frontend-astro/src/components/pages/admin/media/AdminMediaPreview.tsx
'use client';

import React, { useEffect, useMemo } from 'react';
import FsLightbox from 'fslightbox-react';
import FileViewer from '@flyfish-group/file-viewer-react';
import type { MediaFileItem } from './MediaTypes';
import { getFullMediaUrl, formatBytes } from '@/lib/utils';
import {
  X,
  ChevronLeft,
  ChevronRight,
  Edit3,
  ExternalLink,
  Image as ImageIcon,
  Music,
  Video,
  FileText,
} from 'lucide-react';

interface AdminMediaPreviewProps {
  files: MediaFileItem[];
  activeFile: MediaFileItem;
  onClose: () => void;
  onNavigate?: (file: MediaFileItem) => void;
  onEdit?: (file: MediaFileItem) => void;
}

function getTypeIcon(mime: string) {
  if (mime.startsWith('image/')) return ImageIcon;
  if (mime.startsWith('video/')) return Video;
  if (mime.startsWith('audio/')) return Music;
  return FileText;
}

/**
 * AdminMediaPreview — 后台全类型预览组件
 *
 * - image/* → FsLightbox 全屏画廊
 * - 其他 → FileViewer 模态框（含底部缩略图导航）
 * - 图片额外提供 "编辑" 入口跳转 ImageEditorModal
 */
export function AdminMediaPreview({
  files,
  activeFile,
  onClose,
  onNavigate,
  onEdit,
}: AdminMediaPreviewProps) {
  const mime = activeFile?.mime_type || '';
  const isImage = mime.startsWith('image/');
  const isVideo = mime.startsWith('video/');
  const isAudio = mime.startsWith('audio/');
  const fullUrl = getFullMediaUrl(activeFile?.url);
  const currentIndex = files.findIndex((f) => f.id === activeFile?.id);
  const prevFile = currentIndex > 0 ? files[currentIndex - 1] : null;
  const nextFile =
    currentIndex < files.length - 1 ? files[currentIndex + 1] : null;

  // ESC 关闭
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [onClose]);

  // ← → 导航
  useEffect(() => {
    if (!onNavigate) return;
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'ArrowLeft' && prevFile) onNavigate(prevFile);
      if (e.key === 'ArrowRight' && nextFile) onNavigate(nextFile);
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [onNavigate, prevFile, nextFile]);

  // ── 图片：FsLightbox ──
  if (isImage) {
    const imageFiles = files.filter((f) =>
      f.mime_type?.startsWith('image/'),
    );
    const sources = imageFiles.map((f) =>
      getFullMediaUrl(f.thumbnail_url || f.url),
    );
    const srcIndex = imageFiles.findIndex((f) => f.id === activeFile.id);

    return (
      <FsLightbox
        key={`admin-image-${activeFile.id}`}
        openOnMount
        toggler={false}
        sources={sources}
        sourceIndex={Math.max(0, srcIndex)}
        onClose={onClose}
      />
    );
  }

  // ── 非图片：FileViewer 模态框 ──
  return (
    <div
      className="fixed inset-0 z-50 bg-black/95 flex flex-col"
      onClick={onClose}
    >
      {/* 顶部信息栏 */}
      <div
        className="flex items-center justify-between px-4 py-2.5 bg-black/50 backdrop-blur-sm flex-shrink-0 border-b border-white/5"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center gap-3 min-w-0">
          {React.createElement(getTypeIcon(mime), {
            className: 'w-4 h-4 text-white/50 flex-shrink-0',
          })}
          <span className="text-white/90 text-sm font-medium truncate max-w-xs sm:max-w-md">
            {activeFile.original_filename}
          </span>
          {files.length > 1 && (
            <span className="text-white/40 text-xs flex-shrink-0 hidden sm:inline">
              {currentIndex + 1} / {files.length}
            </span>
          )}
          <span className="text-white/30 text-[10px] flex-shrink-0 bg-white/10 px-1.5 py-0.5 rounded hidden sm:inline">
            {mime}
          </span>
          {activeFile.file_size ? (
            <span className="text-white/30 text-xs flex-shrink-0 hidden md:inline">
              {formatBytes(activeFile.file_size)}
            </span>
          ) : null}
        </div>
        <div className="flex items-center gap-1">
          {/* 编辑图片按钮 — 仅图片类型 */}
          {isImage && onEdit && (
            <button
              onClick={() => onEdit(activeFile)}
              className="p-1.5 rounded-lg hover:bg-white/10 text-white/40 hover:text-white/80 transition-colors"
              title="编辑图片"
            >
              <Edit3 className="w-4 h-4" />
            </button>
          )}
          {/* 复制链接 */}
          <button
            onClick={() => navigator.clipboard.writeText(fullUrl)}
            className="p-1.5 rounded-lg hover:bg-white/10 text-white/40 hover:text-white/80 transition-colors"
            title="复制文件链接"
          >
            <ExternalLink className="w-4 h-4" />
          </button>
          {/* 关闭 */}
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg hover:bg-white/10 text-white/60 hover:text-white transition-colors"
            title="关闭 (Esc)"
          >
            <X className="w-5 h-5" />
          </button>
        </div>
      </div>

      {/* 预览内容区 */}
      <div
        className="flex-1 flex items-center justify-center min-h-0 relative"
        onClick={(e) => e.stopPropagation()}
      >
        {prevFile && onNavigate && (
          <button
            onClick={() => onNavigate(prevFile)}
            className="absolute left-2 top-1/2 -translate-y-1/2 z-10 p-2 rounded-full bg-black/40 hover:bg-black/60 text-white/60 hover:text-white transition-all opacity-0 hover:opacity-100"
            title="上一个 (←)"
          >
            <ChevronLeft className="w-6 h-6" />
          </button>
        )}

        <div className="w-full h-full">
          <FileViewer
            url={fullUrl}
            options={{
              theme: 'dark',
              toolbar: { position: 'bottom-right' },
            }}
          />
        </div>

        {nextFile && onNavigate && (
          <button
            onClick={() => onNavigate(nextFile)}
            className="absolute right-2 top-1/2 -translate-y-1/2 z-10 p-2 rounded-full bg-black/40 hover:bg-black/60 text-white/60 hover:text-white transition-all opacity-0 hover:opacity-100"
            title="下一个 (→)"
          >
            <ChevronRight className="w-6 h-6" />
          </button>
        )}
      </div>

      {/* 底部缩略图导航 */}
      {files.length > 1 && (
        <div
          className="h-16 sm:h-20 bg-black/40 backdrop-blur-sm border-t border-white/5 flex-shrink-0 flex items-center px-3 gap-2 overflow-x-auto"
          onClick={(e) => e.stopPropagation()}
          style={{ scrollbarWidth: 'thin', scrollbarColor: 'rgba(255,255,255,0.1) transparent' }}
        >
          {files.map((f) => {
            const isActive = f.id === activeFile.id;
            const fMime = f.mime_type || '';
            const isImg = fMime.startsWith('image/');
            const thumbSrc =
              isImg && f.thumbnail_url
                ? getFullMediaUrl(f.thumbnail_url)
                : null;

            return (
              <button
                key={f.id}
                onClick={() => onNavigate?.(f)}
                className={`flex-shrink-0 w-12 h-10 sm:w-16 sm:h-14 rounded-lg overflow-hidden border-2 transition-all ${
                  isActive
                    ? 'border-blue-500 ring-2 ring-blue-500/30 scale-105'
                    : 'border-white/10 hover:border-white/30 opacity-50 hover:opacity-90'
                }`}
                title={f.original_filename}
              >
                {thumbSrc ? (
                  <img
                    src={thumbSrc}
                    alt=""
                    className="w-full h-full object-cover"
                    loading="lazy"
                  />
                ) : (
                  <div className="w-full h-full flex items-center justify-center bg-white/5">
                    {React.createElement(getTypeIcon(fMime), {
                      className: 'w-4 h-4 sm:w-5 sm:h-5 text-white/30',
                    })}
                  </div>
                )}
              </button>
            );
          })}
        </div>
      )}
    </div>
  );
}

// frontend/web/src/components/admin/AdminMediaPreview.vue
<script lang="ts" setup>
import {computed, onBeforeUnmount, onMounted, ref, watch} from 'vue'

import type {MediaItem} from '@/api'
import type {IconName} from '@/lib/icons'
import {ElMessage} from '@/utils/feedback'
import {formatDateTime, formatFileSize} from '@/utils/format'

/**
 * 后台媒体预览（全类型）
 *
 * 对应原 astro 的 `pages/admin/media/AdminMediaPreview.tsx`。原实现依赖
 * `fslightbox-react`（图片画廊）与 `@flyfish-group/file-viewer-react`（其它类型），
 * 这里按 Nuxt 原生方式重写，**不新增任何依赖**：
 *
 *   - image/*       → 原生 `<img>` 全屏 + 底部缩略图导航
 *   - video/* audio/* → 原生 `<video>` / `<audio>`（带 controls）
 *   - application/pdf → 原生 `<iframe>`
 *   - text/*、json   → `$fetch` 取文本后 `<pre>` 展示（>512KB 不拉取）
 *   - 其余           → 下载入口
 *
 * 与前台 `MediaPreview` 的区别：这是后台语境下的版本，额外提供类型图标、
 * 文件元信息（mime / 大小 / 上传时间）、复制链接与「编辑」入口。
 */
const props = withDefaults(
  defineProps<{
    open?: boolean
    /** 当前列表（用于左右切换与缩略图导航） */
    files?: MediaItem[]
    /** 当前项 id；切换由父组件回写 */
    activeId?: number | null
  }>(),
  {open: false, files: () => [], activeId: null},
)

const emit = defineEmits<{
  (e: 'close'): void
  (e: 'navigate', file: MediaItem): void
  (e: 'edit', file: MediaItem): void
}>()

const KIND_ICONS: Record<string, IconName> = {
  image: 'image',
  video: 'video',
  audio: 'music',
  pdf: 'file-text',
  text: 'file-text',
  other: 'file-text',
}

const currentIndex = computed(() => props.files.findIndex((file) => file.id === props.activeId))
const current = computed(() => (currentIndex.value >= 0 ? props.files[currentIndex.value] : null))

const kind = computed(() => {
  const mime = current.value?.mime_type || ''
  if (mime.startsWith('image/')) return 'image'
  if (mime.startsWith('video/')) return 'video'
  if (mime.startsWith('audio/')) return 'audio'
  if (mime === 'application/pdf') return 'pdf'
  if (mime.startsWith('text/') || mime === 'application/json') return 'text'
  return 'other'
})

const typeIcon = computed<IconName>(() => KIND_ICONS[kind.value] ?? 'file-text')

const canPrev = computed(() => currentIndex.value > 0)
const canNext = computed(
  () => currentIndex.value >= 0 && currentIndex.value < props.files.length - 1,
)

/** 文本预览：只在 ≤ 512 KB 时拉取，避免大文件阻塞界面 */
const TEXT_LIMIT = 512 * 1024
const textContent = ref('')

watch(
  () => [props.open, props.activeId, kind.value] as const,
  async () => {
    textContent.value = ''
    const file = current.value
    if (!props.open || !file || kind.value !== 'text' || !file.file_url) return
    if ((file.file_size || 0) > TEXT_LIMIT) return
    try {
      textContent.value = await $fetch<string>(file.file_url, {responseType: 'text'})
    } catch {
      textContent.value = ''
    }
  },
  {immediate: true},
)

function go(delta: number): void {
  const next = props.files[currentIndex.value + delta]
  if (next) emit('navigate', next)
}

async function copyLink(): Promise<void> {
  const url = current.value?.file_url
  if (!url) return
  try {
    await navigator.clipboard.writeText(url)
    ElMessage.success('链接已复制')
  } catch {
    ElMessage.warning('复制失败，请手动复制')
  }
}

function onKeydown(event: KeyboardEvent): void {
  if (!props.open) return
  if (event.key === 'Escape') emit('close')
  else if (event.key === 'ArrowLeft') go(-1)
  else if (event.key === 'ArrowRight') go(1)
}

onMounted(() => window.addEventListener('keydown', onKeydown))
onBeforeUnmount(() => window.removeEventListener('keydown', onKeydown))
</script>

<template>
  <div
    v-if="props.open && current"
    aria-modal="true"
    class="fixed inset-0 z-[100] flex flex-col bg-black/95"
    role="dialog"
  >
    <!-- 顶部信息栏 -->
    <header
      class="flex flex-shrink-0 items-center justify-between gap-3 border-b border-white/10 bg-black/50 px-4 py-2.5 backdrop-blur-sm">
      <div class="flex min-w-0 items-center gap-3">
        <Icon :name="typeIcon" class="h-4 w-4 flex-shrink-0 text-white/50"/>
        <span class="max-w-[12rem] truncate text-sm font-medium text-white/90 sm:max-w-md">
          {{ current.original_filename || current.filename || '(未命名)' }}
        </span>
        <span v-if="props.files.length > 1" class="hidden flex-shrink-0 text-xs text-white/40 sm:inline">
          {{ currentIndex + 1 }} / {{ props.files.length }}
        </span>
        <span class="hidden flex-shrink-0 rounded bg-white/10 px-1.5 py-0.5 text-[10px] text-white/40 sm:inline">
          {{ current.mime_type || '-' }}
        </span>
        <span v-if="current.file_size" class="hidden flex-shrink-0 text-xs text-white/30 md:inline">
          {{ formatFileSize(current.file_size) }}
        </span>
        <span v-if="current.created_at" class="hidden flex-shrink-0 text-xs text-white/30 lg:inline">
          {{ formatDateTime(current.created_at) }}
        </span>
      </div>

      <div class="flex flex-shrink-0 items-center gap-1">
        <button
          v-if="current.file_url"
          class="rounded-lg p-1.5 text-white/50 transition-colors hover:bg-white/10 hover:text-white/90"
          title="复制文件链接"
          type="button"
          @click="copyLink"
        >
          <Icon class="h-4 w-4" name="link"/>
        </button>
        <button
          v-if="kind === 'image'"
          class="rounded-lg p-1.5 text-white/50 transition-colors hover:bg-white/10 hover:text-white/90"
          title="编辑图片信息"
          type="button"
          @click="emit('edit', current)"
        >
          <Icon class="h-4 w-4" name="pencil"/>
        </button>
        <a
          v-if="current.file_url"
          :href="current.file_url"
          class="rounded-lg p-1.5 text-white/50 transition-colors hover:bg-white/10 hover:text-white/90"
          download
          title="下载"
        >
          <Icon class="h-4 w-4" name="download"/>
        </a>
        <button
          class="rounded-lg p-1.5 text-white/60 transition-colors hover:bg-white/10 hover:text-white"
          title="关闭 (Esc)"
          type="button"
          @click="emit('close')"
        >
          <Icon class="h-5 w-5" name="x"/>
        </button>
      </div>
    </header>

    <!-- 预览主体 -->
    <div class="relative flex min-h-0 flex-1 items-center justify-center">
      <button
        v-if="canPrev"
        class="absolute left-2 top-1/2 z-10 -translate-y-1/2 rounded-full bg-black/40 p-2 text-white/70 transition-colors hover:bg-black/70 hover:text-white"
        title="上一个 (←)"
        type="button"
        @click="go(-1)"
      >
        <Icon class="h-6 w-6" name="chevron-left"/>
      </button>

      <img
        v-if="kind === 'image' && current.file_url"
        :alt="current.alt_text || current.original_filename || ''"
        :src="current.file_url"
        class="max-h-full max-w-full object-contain"
      >
      <video
        v-else-if="kind === 'video' && current.file_url"
        :src="current.file_url"
        class="max-h-full max-w-full"
        controls
      />
      <audio
        v-else-if="kind === 'audio' && current.file_url"
        :src="current.file_url"
        class="w-full max-w-xl px-6"
        controls
      />
      <iframe
        v-else-if="kind === 'pdf' && current.file_url"
        :src="current.file_url"
        class="h-full w-full max-w-5xl rounded border border-white/10 bg-white"
        title="PDF 预览"
      />
      <pre
        v-else-if="kind === 'text' && textContent"
        class="h-full w-full max-w-5xl overflow-auto whitespace-pre-wrap break-words bg-black/60 p-4 text-xs leading-relaxed text-white/80"
      >{{ textContent }}</pre>

      <div v-else class="flex flex-col items-center gap-3 text-center text-white/50">
        <Icon class="h-10 w-10" name="file-text"/>
        <p class="text-sm">
          {{ kind === 'text' ? '文件过大或读取失败，暂不支持在线预览' : '该类型暂不支持在线预览' }}
        </p>
        <a v-if="current.file_url" :href="current.file_url" class="text-sm text-blue-400 hover:underline" download>
          下载文件
        </a>
      </div>

      <button
        v-if="canNext"
        class="absolute right-2 top-1/2 z-10 -translate-y-1/2 rounded-full bg-black/40 p-2 text-white/70 transition-colors hover:bg-black/70 hover:text-white"
        title="下一个 (→)"
        type="button"
        @click="go(1)"
      >
        <Icon class="h-6 w-6" name="chevron-right"/>
      </button>
    </div>

    <!-- 底部缩略图导航 -->
    <footer
      v-if="props.files.length > 1"
      class="flex h-20 flex-shrink-0 items-center gap-2 overflow-x-auto border-t border-white/10 bg-black/40 px-3 backdrop-blur-sm"
    >
      <button
        v-for="file in props.files"
        :key="file.id"
        :class="
          file.id === props.activeId
            ? 'border-blue-500 ring-2 ring-blue-500/30'
            : 'border-white/10 opacity-50 hover:border-white/30 hover:opacity-90'
        "
        :title="file.original_filename || file.filename || ''"
        class="h-14 w-16 flex-shrink-0 overflow-hidden rounded-lg border-2 transition-all"
        type="button"
        @click="emit('navigate', file)"
      >
        <img
          v-if="(file.mime_type || '').startsWith('image/') && (file.thumbnail_url || file.file_url)"
          :alt="file.alt_text || ''"
          :src="file.thumbnail_url || file.file_url || ''"
          class="h-full w-full object-cover"
          loading="lazy"
        >
        <span v-else class="flex h-full w-full items-center justify-center bg-white/5">
          <Icon class="h-5 w-5 text-white/30" name="file-text"/>
        </span>
      </button>
    </footer>
  </div>
</template>
