// frontend-astro/src/components/plugins/ThemeConfigPanel.tsx
'use client';

import React, {useState, useEffect} from 'react';
import {useQuery, useMutation, useQueryClient} from '@tanstack/react-query';
import {apiClient} from '@/lib/api/base-client';
import {Palette, Save, RotateCcw, CheckCircle, AlertCircle, Layers} from 'lucide-react';

interface Props {
    pluginSlug: string;
    themeName: string;
    themeDescription?: string;
}

// 组件槽位定义：可供主题覆盖的组件与其可用变体
const SLOT_DEFS: { key: string; label: string; options: { value: string; label: string }[] }[] = [
    {
        key: 'header',
        label: '顶部导航',
        options: [
            {value: 'floating', label: '浮动胶囊（默认）'},
            {value: 'classic', label: '经典顶栏'},
        ],
    },
    {
        key: 'articleCard',
        label: '文章卡片',
        options: [
            {value: 'default', label: '标准卡片（默认）'},
            {value: 'compact', label: '紧凑卡片'},
        ],
    },
    {
        key: 'footer',
        label: '页脚',
        options: [
            {value: 'default', label: '标准（默认）'},
            {value: 'minimal', label: '极简'},
        ],
    },
];

export default function ThemeConfigPanel({pluginSlug, themeName, themeDescription}: Props) {
    const qc = useQueryClient();
    const [settings, setSettings] = useState<any>({});
    const [componentSlots, setComponentSlots] = useState<Record<string, string>>({});
    const [notification, setNotification] = useState<{type: 'success' | 'error'; message: string} | null>(null);

    // 自动清除通知
    useEffect(() => {
        if (notification) {
            const timer = setTimeout(() => setNotification(null), 3000);
            return () => clearTimeout(timer);
        }
    }, [notification]);

    const showSuccess = (msg: string) => setNotification({type: 'success', message: msg});
    const showError = (msg: string) => setNotification({type: 'error', message: msg});

    // 读取主题配置
    const {data: configData, isLoading} = useQuery({
        queryKey: ['theme-config', pluginSlug],
        queryFn: async () => {
            const res = await apiClient.get(`/themes/${pluginSlug}/config`);
            return res.data;
        },
    });

    useEffect(() => {
        if (configData?.settings) {
            setSettings(configData.settings);
        }
        if (configData?.contract?.componentSlots) {
            setComponentSlots({...configData.contract.componentSlots});
        }
    }, [configData]);

    // 保存主题配置
    const saveMut = useMutation({
        mutationFn: (payload: {settings: any; component_slots: Record<string, string>}) =>
            apiClient.put(`/themes/${pluginSlug}/config`, payload),
        onSuccess: () => {
            qc.invalidateQueries({queryKey: ['theme-config', pluginSlug]});
            qc.invalidateQueries({queryKey: ['themes-installed']});
            showSuccess('主题配置已保存！');
        },
        onError: (err: any) => {
            showError(err?.message || '保存失败');
        },
    });

    const handleSave = () => saveMut.mutate({settings, component_slots: componentSlots});
    const handleReset = () => {
        if (configData?.settings) setSettings({...configData.settings});
        if (configData?.contract?.componentSlots) setComponentSlots({...configData.contract.componentSlots});
    };

    if (isLoading) {
        return (
            <div className="flex items-center justify-center py-20">
                <div className="animate-spin w-8 h-8 border-2 border-blue-600 border-t-transparent rounded-full"/>
            </div>
        );
    }

    return (
        <div className="max-w-4xl mx-auto space-y-8">
            {/* 通知 */}
            {notification && (
                <div className={`flex items-center gap-3 px-4 py-3 rounded-xl border ${
                    notification.type === 'success'
                        ? 'bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800 text-green-700 dark:text-green-300'
                        : 'bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800 text-red-700 dark:text-red-300'
                }`}>
                    {notification.type === 'success' ? <CheckCircle className="w-5 h-5"/> : <AlertCircle className="w-5 h-5"/>}
                    <span className="text-sm font-medium">{notification.message}</span>
                </div>
            )}

            {/* 主题信息 */}
            <div className="bg-white dark:bg-gray-900 rounded-xl border p-6">
                <div className="flex items-center gap-4">
                    <div className="w-16 h-16 bg-blue-100 dark:bg-blue-900/30 rounded-xl flex items-center justify-center">
                        <Palette className="w-8 h-8 text-blue-600"/>
                    </div>
                    <div>
                        <h2 className="text-xl font-semibold text-gray-900 dark:text-white">{themeName}</h2>
                        {themeDescription && <p className="text-sm text-gray-500">{themeDescription}</p>}
                    </div>
                </div>
            </div>

            {/* 配置表单 */}
            <div className="bg-white dark:bg-gray-900 rounded-xl border p-6 space-y-6">
                {configData?.settings_schema && Object.entries(configData.settings_schema).map(([groupKey, group]: [string, any]) => (
                    <div key={groupKey}>
                        <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-4">
                            {group.label || groupKey}
                        </h3>
                        <div className="space-y-4 pl-2">
                            {group.fields && Object.entries(group.fields).map(([fieldKey, field]: [string, any]) => (
                                <div key={fieldKey}>
                                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                                        {field.label || fieldKey}
                                    </label>
                                    {renderField(fieldKey, field, settings, setSettings)}
                                </div>
                            ))}
                        </div>
                    </div>
                ))}
            </div>

            {/* 组件槽位 */}
            <div className="bg-white dark:bg-gray-900 rounded-xl border p-6 space-y-6">
                <div className="flex items-center gap-3">
                    <Layers className="w-5 h-5 text-blue-600"/>
                    <h3 className="text-lg font-medium text-gray-900 dark:text-white">组件</h3>
                    <span className="text-xs text-gray-400">选择该主题下各组件使用的变体</span>
                </div>
                <div className="space-y-4 pl-2">
                    {SLOT_DEFS.map((slot) => (
                        <div key={slot.key}>
                            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                                {slot.label}
                            </label>
                            <select
                                value={componentSlots[slot.key] || slot.options[0]?.value || ''}
                                onChange={(e) => setComponentSlots((prev) => ({...prev, [slot.key]: e.target.value}))}
                                className="w-full px-3 py-2 border rounded-lg bg-white dark:bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                            >
                                {slot.options.map((opt) => (
                                    <option key={opt.value} value={opt.value}>{opt.label}</option>
                                ))}
                            </select>
                        </div>
                    ))}
                </div>
            </div>

            {/* 操作按钮 */}
            <div className="flex gap-3 justify-end">
                <button
                    onClick={handleReset}
                    className="px-4 py-2 border rounded-lg text-sm hover:bg-gray-50 dark:hover:bg-gray-800 transition flex items-center gap-2"
                >
                    <RotateCcw className="w-4 h-4"/>重置
                </button>
                <button
                    onClick={handleSave}
                    disabled={saveMut.isPending}
                    className="px-6 py-2 bg-blue-600 text-white rounded-lg text-sm hover:bg-blue-700 transition flex items-center gap-2"
                >
                    <Save className="w-4 h-4"/>
                    {saveMut.isPending ? '保存中...' : '保存配置'}
                </button>
            </div>
        </div>
    );
}

// 渲染单个配置字段
function renderField(
    fieldKey: string,
    field: any,
    settings: any,
    setSettings: (s: any) => void,
) {
    const value = settings[fieldKey] ?? field.default;

    const update = (newVal: any) => {
        setSettings((prev: any) => ({...prev, [fieldKey]: newVal}));
    };

    switch (field.type) {
        case 'color':
            return (
                <div className="flex items-center gap-3">
                    <input type="color" value={value || '#000000'}
                           onChange={(e) => update(e.target.value)}
                           className="w-10 h-10 rounded border cursor-pointer"/>
                    <input type="text" value={value || ''}
                           onChange={(e) => update(e.target.value)}
                           className="flex-1 px-3 py-2 border rounded-lg bg-white dark:bg-gray-800 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-blue-500"/>
                </div>
            );
        case 'select':
            return (
                <select value={value || ''}
                        onChange={(e) => update(e.target.value)}
                        className="w-full px-3 py-2 border rounded-lg bg-white dark:bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500">
                    {(field.options || []).map((opt: any) => (
                        <option key={opt.value} value={opt.value}>{opt.label || opt.value}</option>
                    ))}
                </select>
            );
        case 'boolean':
            return (
                <label className="flex items-center gap-3 cursor-pointer">
                    <input type="checkbox" checked={!!value}
                           onChange={(e) => update(e.target.checked)}
                           className="w-4 h-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500"/>
                    <span className="text-sm text-gray-600 dark:text-gray-400">{field.label || fieldKey}</span>
                </label>
            );
        case 'number':
            return (
                <input type="number" value={value ?? ''}
                       onChange={(e) => update(Number(e.target.value))}
                       className="w-full px-3 py-2 border rounded-lg bg-white dark:bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"/>
            );
        case 'textarea':
            return (
                <textarea value={value || ''}
                          onChange={(e) => update(e.target.value)} rows={3}
                          className="w-full px-3 py-2 border rounded-lg bg-white dark:bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"/>
            );
        default:
            return (
                <input type="text" value={value || ''}
                       onChange={(e) => update(e.target.value)}
                       className="w-full px-3 py-2 border rounded-lg bg-white dark:bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"/>
            );
    }
}

// frontend/web/src/components/admin/ThemeConfigPanel.vue
<script lang="ts" setup>
import {computed, onMounted, ref} from 'vue'

import {ElMessage} from '@/utils/feedback'
import {legacyGet, legacyPut} from '@/utils/legacyApi'

/**
 * 主题配置面板（三个主题插件共用）
 *
 * 对应 astro 的 `components/plugins/ThemeConfigPanel.tsx`：
 * 读主题的 `settings_schema` 渲染表单，再叠加「组件槽位」（header / articleCard / footer）选择，
 * 一并保存到 **`/api/v2/themes/{slug}/config`**（v3 目前没有 settings_schema /
 * component_slots 的等价读写端点，见 `docs/refactor/HANDOVER.md` §12.3）。
 *
 * 原实现自带一个顶部通知条；这里改用与后台其它页一致的 `ElMessage`。
 */
interface FieldDef {
  label?: string
  type?: string
  default?: unknown
  options?: Array<{ value: string; label?: string }>
}

interface GroupDef {
  label?: string
  fields?: Record<string, FieldDef>
}

interface ThemeConfig {
  settings?: Record<string, unknown>
  settings_schema?: Record<string, GroupDef>
  contract?: { componentSlots?: Record<string, string> }
}

const props = defineProps<{
  pluginSlug: string
  themeName: string
  themeDescription?: string
}>()

/** 可供主题覆盖的组件与其变体（与 astro 版一致） */
const SLOT_DEFS = [
  {
    key: 'header',
    label: '顶部导航',
    options: [
      {value: 'floating', label: '浮动胶囊（默认）'},
      {value: 'classic', label: '经典顶栏'},
    ],
  },
  {
    key: 'articleCard',
    label: '文章卡片',
    options: [
      {value: 'default', label: '标准卡片（默认）'},
      {value: 'compact', label: '紧凑卡片'},
    ],
  },
  {
    key: 'footer',
    label: '页脚',
    options: [
      {value: 'default', label: '标准（默认）'},
      {value: 'minimal', label: '极简'},
    ],
  },
]

const loading = ref(true)
const error = ref('')
const saving = ref(false)

const config = ref<ThemeConfig>({})
const settings = ref<Record<string, unknown>>({})
const componentSlots = ref<Record<string, string>>({})

const groups = computed(() => Object.entries(config.value.settings_schema ?? {}))

async function load(): Promise<void> {
  loading.value = true
  error.value = ''
  try {
    const result = await legacyGet<ThemeConfig>(`/themes/${props.pluginSlug}/config`)
    if (!result.success) error.value = result.error || '读取主题配置失败'
    config.value = result.data ?? {}
    settings.value = {...(result.data?.settings ?? {})}
    componentSlots.value = {...(result.data?.contract?.componentSlots ?? {})}
  } finally {
    loading.value = false
  }
}

function fieldValue(key: string, field: FieldDef): unknown {
  return settings.value[key] ?? field.default
}

function updateField(key: string, value: unknown): void {
  settings.value = {...settings.value, [key]: value}
}

function updateSlot(key: string, value: string): void {
  componentSlots.value = {...componentSlots.value, [key]: value}
}

function reset(): void {
  settings.value = {...(config.value.settings ?? {})}
  componentSlots.value = {...(config.value.contract?.componentSlots ?? {})}
}

async function save(): Promise<void> {
  saving.value = true
  try {
    const result = await legacyPut(`/themes/${props.pluginSlug}/config`, {
      settings: settings.value,
      component_slots: componentSlots.value,
    })
    if (result.success) ElMessage.success('主题配置已保存')
    else ElMessage.error(result.error || '保存失败')
  } finally {
    saving.value = false
  }
}

onMounted(load)
</script>

<template>
  <div class="mx-auto max-w-4xl space-y-8">
    <p v-if="error" class="rounded-control bg-danger-soft px-3 py-2 text-sm text-danger">{{ error }}</p>

    <!-- 主题信息 -->
    <div class="rounded-card border border-line bg-surface p-6">
      <div class="flex items-center gap-4">
        <span class="flex h-16 w-16 items-center justify-center rounded-card bg-primary-soft">
          <Icon class="h-8 w-8 text-primary" name="palette"/>
        </span>
        <div>
          <h2 class="text-xl font-semibold text-fg">{{ themeName }}</h2>
          <p v-if="themeDescription" class="text-sm text-fg-muted">{{ themeDescription }}</p>
        </div>
      </div>
    </div>

    <div v-if="loading" class="space-y-3">
      <Skeleton class="h-24 w-full"/>
      <Skeleton class="h-40 w-full"/>
    </div>

    <template v-else>
      <!-- 配置表单（按 settings_schema 渲染） -->
      <div v-if="groups.length" class="space-y-6 rounded-card border border-line bg-surface p-6">
        <div v-for="[groupKey, group] in groups" :key="groupKey">
          <h3 class="mb-4 text-lg font-medium text-fg">{{ group.label || groupKey }}</h3>

          <div class="space-y-4 pl-2">
            <div v-for="[fieldKey, field] in Object.entries(group.fields ?? {})" :key="fieldKey">
              <label class="mb-1 block text-sm font-medium text-fg">{{ field.label || fieldKey }}</label>

              <!-- color -->
              <div v-if="field.type === 'color'" class="flex items-center gap-3">
                <input
                  :value="(fieldValue(fieldKey, field) as string) || '#000000'"
                  class="h-10 w-10 cursor-pointer rounded border border-line"
                  type="color"
                  @input="updateField(fieldKey, ($event.target as HTMLInputElement).value)"
                >
                <el-input
                  :model-value="(fieldValue(fieldKey, field) as string) || ''"
                  class="flex-1"
                  @update:model-value="updateField(fieldKey, $event)"
                />
              </div>

              <!-- select -->
              <el-select
                v-else-if="field.type === 'select'"
                :model-value="(fieldValue(fieldKey, field) as string) || ''"
                class="w-full"
                @update:model-value="updateField(fieldKey, $event)"
              >
                <el-option
                  v-for="option in field.options ?? []"
                  :key="option.value"
                  :label="option.label || option.value"
                  :value="option.value"
                />
              </el-select>

              <!-- boolean -->
              <el-switch
                v-else-if="field.type === 'boolean'"
                :model-value="Boolean(fieldValue(fieldKey, field))"
                @update:model-value="updateField(fieldKey, $event)"
              />

              <!-- number -->
              <el-input
                v-else-if="field.type === 'number'"
                :model-value="String(fieldValue(fieldKey, field) ?? '')"
                type="number"
                @update:model-value="updateField(fieldKey, Number($event))"
              />

              <!-- textarea -->
              <el-input
                v-else-if="field.type === 'textarea'"
                :model-value="(fieldValue(fieldKey, field) as string) || ''"
                :rows="3"
                type="textarea"
                @update:model-value="updateField(fieldKey, $event)"
              />

              <!-- text（默认） -->
              <el-input
                v-else
                :model-value="(fieldValue(fieldKey, field) as string) || ''"
                @update:model-value="updateField(fieldKey, $event)"
              />
            </div>
          </div>
        </div>
      </div>

      <!-- 组件槽位 -->
      <div class="space-y-6 rounded-card border border-line bg-surface p-6">
        <div class="flex items-center gap-3">
          <Icon class="h-5 w-5 text-primary" name="layers"/>
          <h3 class="text-lg font-medium text-fg">组件</h3>
          <span class="text-xs text-fg-subtle">选择该主题下各组件使用的变体</span>
        </div>

        <div class="space-y-4 pl-2">
          <div v-for="slot in SLOT_DEFS" :key="slot.key">
            <label class="mb-1 block text-sm font-medium text-fg">{{ slot.label }}</label>
            <el-select
              :model-value="componentSlots[slot.key] || slot.options[0]?.value || ''"
              class="w-full"
              @update:model-value="updateSlot(slot.key, $event)"
            >
              <el-option
                v-for="option in slot.options"
                :key="option.value"
                :label="option.label"
                :value="option.value"
              />
            </el-select>
          </div>
        </div>
      </div>

      <!-- 操作 -->
      <div class="flex justify-end gap-3">
        <el-button @click="reset">
          <Icon class="mr-1 h-4 w-4" name="rotate-ccw"/>
          重置
        </el-button>
        <el-button :loading="saving" type="primary" @click="save">
          <Icon class="mr-1 h-4 w-4" name="save"/>
          保存配置
        </el-button>
      </div>
    </template>
  </div>
</template>
