// plugins/approval/frontend/admin/Page.vue
<script lang="ts" setup>
import {computed, onMounted, reactive, ref, watch} from 'vue'

import {ElMessage} from '@/utils/feedback'
import {pluginAction} from '@/utils/pluginAction'

/**
 * 内容审批（approval 插件后台页）
 *
 * 对应 `plugins/approval/frontend/admin/Page.tsx`：
 * 三个页签（待审批 / 我的申请 / 统计概览）+ 审批动作弹窗（可填审批意见）。
 */
interface ApprovalItem {
  id: number
  content_id?: number | null
  content_title?: string | null
  content_type?: string | null
  status?: string | null
  created_at?: string | null
}

interface ListResult {
  items: ApprovalItem[]
  total: number
}

interface Stats {
  total_pending?: number
  total_approved?: number
  total_rejected?: number
  total?: number
}

type TabKey = 'pending' | 'my-requests' | 'history'

const TABS: Array<{ key: TabKey; label: string; icon: string }> = [
  {key: 'pending', label: '待审批', icon: 'clock'},
  {key: 'my-requests', label: '我的申请', icon: 'circle-check'},
  {key: 'history', label: '统计概览', icon: 'clipboard-list'},
]

const PER_PAGE = 15

const tab = ref<TabKey>('pending')
const page = ref(1)
const loading = ref(false)
const error = ref('')

const items = ref<ApprovalItem[]>([])
const total = ref(0)
const stats = ref<Stats>({})

const dialog = reactive<{ open: boolean; id: number; action: 'approve' | 'reject' }>({
  open: false,
  id: 0,
  action: 'approve',
})
const notes = ref('')
const submitting = ref(false)

const statCards = computed(() => [
  {label: '待审批', value: stats.value.total_pending ?? '—'},
  {label: '已通过', value: stats.value.total_approved ?? '—'},
  {label: '已拒绝', value: stats.value.total_rejected ?? '—'},
  {label: '总计', value: stats.value.total ?? '—'},
])

async function loadCurrent(): Promise<void> {
  loading.value = true
  error.value = ''
  try {
    if (tab.value === 'history') {
      const result = await pluginAction<Stats>('approval', 'get_stats')
      stats.value = result.data ?? {}
      return
    }

    const action = tab.value === 'pending' ? 'list_pending' : 'list_my_requests'
    const result = await pluginAction<ListResult>('approval', action, {page: page.value, per_page: PER_PAGE})
    items.value = result.data?.items ?? []
    total.value = result.data?.total ?? 0
    if (!result.success) error.value = result.error || '加载失败'
  } finally {
    loading.value = false
  }
}

function switchTab(key: TabKey): void {
  tab.value = key
  page.value = 1
}

function openDialog(item: ApprovalItem, action: 'approve' | 'reject'): void {
  dialog.open = true
  dialog.id = item.id
  dialog.action = action
  notes.value = ''
}

async function submitAction(): Promise<void> {
  submitting.value = true
  try {
    const result = await pluginAction('approval', dialog.action, {
      record_id: dialog.id,
      notes: notes.value,
    })
    if (result.success) {
      ElMessage.success(dialog.action === 'approve' ? '已通过' : '已拒绝')
      dialog.open = false
      await loadCurrent()
    } else {
      ElMessage.error(result.error || '操作失败')
    }
  } finally {
    submitting.value = false
  }
}

function statusLabel(status?: string | null): string {
  if (status === 'approved') return '已通过'
  if (status === 'rejected') return '已拒绝'
  return '待审批'
}

function statusTagType(status?: string | null): 'success' | 'danger' | 'warning' {
  if (status === 'approved') return 'success'
  if (status === 'rejected') return 'danger'
  return 'warning'
}

function formatDate(value?: string | null): string {
  if (!value) return ''
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? '' : date.toLocaleDateString()
}

watch(page, loadCurrent)
onMounted(loadCurrent)
</script>

<template>
  <div class="p-4">
    <!-- 页签 -->
    <div class="mb-4 flex flex-wrap gap-2">
      <button
        v-for="item in TABS"
        :key="item.key"
        :class="
          tab === item.key
            ? 'bg-primary text-primary-fg'
            : 'border border-line bg-surface text-fg-muted hover:bg-surface-soft'
        "
        class="flex items-center gap-1.5 rounded-control px-4 py-2 text-sm font-medium transition-colors"
        type="button"
        @click="switchTab(item.key)"
      >
        <Icon :name="item.icon" class="h-4 w-4"/>
        {{ item.label }}
      </button>
    </div>

    <p v-if="error" class="mb-3 rounded-control bg-danger-soft px-3 py-2 text-sm text-danger">{{ error }}</p>

    <!-- 统计概览 -->
    <div v-if="tab === 'history'" class="mb-6 grid grid-cols-2 gap-4 lg:grid-cols-4">
      <div v-for="card in statCards" :key="card.label" class="rounded-card border border-line bg-surface p-4">
        <p class="mb-1 text-xs text-fg-muted">{{ card.label }}</p>
        <p class="text-2xl font-bold text-fg">{{ card.value }}</p>
      </div>
    </div>

    <!-- 列表 -->
    <template v-else>
      <div v-if="loading" class="space-y-3">
        <Skeleton v-for="i in 5" :key="i" class="h-16 w-full"/>
      </div>

      <EmptyState v-else-if="!items.length" description="有内容提交审批后会出现在这里" title="暂无数据"/>

      <el-table v-else :data="items" border>
        <el-table-column label="内容" min-width="260">
          <template #default="{row}">
            <p class="text-sm font-medium text-fg">{{ row.content_title || `#${row.content_id}` }}</p>
            <p class="text-xs text-fg-subtle">{{ row.content_type }} · {{ formatDate(row.created_at) }}</p>
          </template>
        </el-table-column>

        <el-table-column label="状态" width="120">
          <template #default="{row}">
            <el-tag :type="statusTagType(row.status)" size="small">{{ statusLabel(row.status) }}</el-tag>
          </template>
        </el-table-column>

        <el-table-column align="right" label="操作" width="180">
          <template #default="{row}">
            <template v-if="tab === 'pending' && row.status === 'pending'">
              <el-button link type="success" @click="openDialog(row, 'approve')">通过</el-button>
              <el-button link type="danger" @click="openDialog(row, 'reject')">拒绝</el-button>
            </template>
          </template>
        </el-table-column>
      </el-table>

      <el-pagination
        v-if="total > PER_PAGE"
        v-model:current-page="page"
        :page-size="PER_PAGE"
        :total="total"
        class="mt-3 justify-end"
        layout="total, prev, pager, next"
      />
    </template>

    <!-- 审批弹窗 -->
    <el-dialog v-model="dialog.open" :title="dialog.action === 'approve' ? '审批通过' : '拒绝'" width="440px">
      <el-input v-model="notes" :rows="3" placeholder="审批意见（可选）" type="textarea"/>
      <template #footer>
        <el-button @click="dialog.open = false">取消</el-button>
        <el-button :loading="submitting" :type="dialog.action === 'approve' ? 'success' : 'danger'"
                   @click="submitAction">
          确认
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

// plugins/approval/frontend/admin/Page.tsx
'use client';

import React, {useState} from 'react';
import {useQuery, useMutation, useQueryClient} from '@tanstack/react-query';
import {AdminShell} from '@/components/admin/AdminShell';
import {apiClient} from '@/lib/api/base-client';
import {Clock, CheckCircle, Loader2} from 'lucide-react';

const PLUGIN_SLUG = 'approval';

function call(action: string, params: any = {}) {
  return apiClient.post(`/plugins/${PLUGIN_SLUG}/action`, {action, params});
}

export default function ApprovalPage() {
  const qc = useQueryClient();
  const [tab, setTab] = useState<'pending' | 'my-requests' | 'history'>('pending');
  const [page, setPage] = useState(1);
  const [notes, setNotes] = useState('');
  const [actionTarget, setActionTarget] = useState<{id: number; action: 'approve' | 'reject'} | null>(null);

  const {data: pending, isLoading: loadP} = useQuery({
    queryKey: ['approval-pending', page],
    queryFn: async () => { const r = await call('list_pending', {page, per_page: 15}); return r.data || {items: [], total: 0}; },
    enabled: tab === 'pending',
  });
  const {data: myReqs} = useQuery({
    queryKey: ['approval-my', page],
    queryFn: async () => { const r = await call('list_my_requests', {page, per_page: 15}); return r.data || {items: [], total: 0}; },
    enabled: tab === 'my-requests',
  });
  const {data: stats} = useQuery({
    queryKey: ['approval-stats'],
    queryFn: async () => { const r = await call('get_stats'); return r.data || {}; },
    enabled: tab === 'history',
  });

  const actionMut = useMutation({
    mutationFn: ({id, action, n}: {id: number; action: string; n: string}) => call(action, {record_id: id, notes: n}),
    onSuccess: () => { qc.invalidateQueries({queryKey: ['approval']}); setActionTarget(null); setNotes(''); },
  });

  const items = tab === 'pending' ? pending : tab === 'my-requests' ? myReqs : null;
  const tabs = [
    {key: 'pending' as const, label: '待审批', icon: Clock},
    {key: 'my-requests' as const, label: '我的申请', icon: CheckCircle},
    {key: 'history' as const, label: '统计概览', icon: Loader2},
  ];

  return (
    <AdminShell title="内容审批">
      <div className="flex gap-2 mb-6">
        {tabs.map(t => (
          <button key={t.key} onClick={() => { setTab(t.key); setPage(1); }}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition flex items-center gap-1.5 ${
              tab === t.key ? 'bg-blue-600 text-white' : 'bg-white dark:bg-gray-900 border hover:bg-gray-50 dark:hover:bg-gray-800'
            }`}><t.icon className="w-4 h-4"/>{t.label}</button>
        ))}
      </div>

      {tab === 'history' && stats && (
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
          {[
            {label: '待审批', value: stats.total_pending ?? '—'},
            {label: '已通过', value: stats.total_approved ?? '—'},
            {label: '已拒绝', value: stats.total_rejected ?? '—'},
            {label: '总计', value: stats.total ?? '—'},
          ].map(s => (
            <div key={s.label} className="bg-white dark:bg-gray-900 rounded-xl border p-4">
              <p className="text-xs text-gray-500 dark:text-gray-400 mb-1">{s.label}</p>
              <p className="text-2xl font-bold">{s.value}</p>
            </div>
          ))}
        </div>
      )}

      {loadP ? (
        <div className="flex justify-center py-16"><Loader2 className="w-8 h-8 animate-spin text-blue-500"/></div>
      ) : (
        <div className="bg-white dark:bg-gray-900 rounded-xl border overflow-hidden">
          {(!items?.items || items.items.length === 0) ? (
            <div className="py-16 text-center text-gray-400"><Clock className="w-10 h-10 mx-auto mb-3 opacity-40"/><p className="text-sm">暂无数据</p></div>
          ) : (
            <table className="w-full">
              <thead className="bg-gray-50 dark:bg-gray-800 border-b">
                <tr>
                  <th className="px-5 py-3 text-xs font-semibold text-gray-500 uppercase text-left">内容</th>
                  <th className="px-5 py-3 text-xs font-semibold text-gray-500 uppercase text-left hidden sm:table-cell">状态</th>
                  <th className="px-5 py-3 text-xs font-semibold text-gray-500 uppercase text-right">操作</th>
                </tr>
              </thead>
              <tbody className="divide-y dark:divide-gray-800">
                {items.items.map((item: any, i: number) => (
                  <tr key={item.id || i} className="hover:bg-gray-50 dark:hover:bg-gray-800/50">
                    <td className="px-5 py-4">
                      <p className="text-sm font-medium text-gray-900 dark:text-white">{item.content_title || `#${item.content_id}`}</p>
                      <p className="text-xs text-gray-400">{item.content_type} · {item.created_at ? new Date(item.created_at).toLocaleDateString() : ''}</p>
                    </td>
                    <td className="px-5 py-4 hidden sm:table-cell">
                      <span className={`px-2 py-0.5 text-xs rounded-full ${
                        item.status === 'approved' ? 'bg-green-100 text-green-700' :
                        item.status === 'rejected' ? 'bg-red-100 text-red-700' : 'bg-yellow-100 text-yellow-700'
                      }`}>{item.status === 'pending' ? '待审批' : item.status === 'approved' ? '已通过' : '已拒绝'}</span>
                    </td>
                    <td className="px-5 py-4 text-right">
                      {tab === 'pending' && item.status === 'pending' && (
                        <div className="flex gap-2 justify-end">
                          <button onClick={() => setActionTarget({id: item.id, action: 'approve'})}
                            className="px-3 py-1.5 bg-green-600 text-white text-xs rounded-lg hover:bg-green-700">通过</button>
                          <button onClick={() => setActionTarget({id: item.id, action: 'reject'})}
                            className="px-3 py-1.5 bg-red-600 text-white text-xs rounded-lg hover:bg-red-700">拒绝</button>
                        </div>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}

      {actionTarget && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white dark:bg-gray-900 rounded-2xl max-w-md w-full p-6">
            <h3 className="font-semibold text-lg mb-3">{actionTarget.action === 'approve' ? '审批通过' : '拒绝'}</h3>
            <textarea value={notes} onChange={e => setNotes(e.target.value)} placeholder="审批意见（可选）" rows={3}
              className="w-full px-3 py-2 border rounded-lg text-sm mb-4 bg-white dark:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500"/>
            <div className="flex gap-3 justify-end">
              <button onClick={() => setActionTarget(null)} className="px-4 py-2 border rounded-lg text-sm hover:bg-gray-50 dark:hover:bg-gray-800">取消</button>
              <button onClick={() => actionMut.mutate({id: actionTarget.id, action: actionTarget.action, n: notes})}
                disabled={actionMut.isPending}
                className={`px-4 py-2 text-sm text-white rounded-lg ${actionTarget.action === 'approve' ? 'bg-green-600 hover:bg-green-700' : 'bg-red-600 hover:bg-red-700'}`}>
                {actionMut.isPending ? '处理中...' : '确认'}
              </button>
            </div>
          </div>
        </div>
      )}
    </AdminShell>
  );
}
