// frontend/web/src/components/site/audio/AudioLayer.vue
<script lang="ts" setup>
import {computed, onBeforeUnmount, onMounted, ref} from 'vue'

import {useAudioMetadata} from '@/composables/useAudioMetadata'

import {calcKaraokeProgress} from './helpers'

/**
 * 全屏音频播放器（持久音频层）
 *
 * 对应 astro 版 `AudioPlayer/AudioLayer.tsx`：本组件**始终持有同一个 `<audio>` 元素**
 * 与全部播放状态，全屏视图与迷你播放器只是它的两种呈现，因此最小化/展开不会
 * 中断播放（这也是原实现把 audio 放在条件分支之外的原因）。
 *
 * 与 astro 版的差异（行为等价、结构更干净）：
 *  - 原实现 `AudioLayer` / `PlayerView` / `MiniPlayerWrapper` **各请求了一次**
 *    `/api/v2/media/{id}/metadata`；这里统一由 `useAudioMetadata` 加载一次后下传。
 *  - 音量状态上提到本层，最小化再展开后音量不会丢。
 *  - Esc 切换最小化（与原来一致）。
 */
const props = defineProps<{
  /** 当前音轨（由 /media 列表映射而来） */
  track: { id: number; name: string; url: string }
}>()

const emit = defineEmits<{ (e: 'close'): void }>()

const audioEl = ref<HTMLAudioElement | null>(null)

const isPlaying = ref(false)
const currentTime = ref(0)
const duration = ref(0)
const volume = ref(1)

/** 最小化 → 迷你播放器 */
const minimized = ref(false)
/** 桌面歌词默认关闭，由用户主动开启（与 astro 版一致，不读 localStorage 的 visible） */
const showDesktopLyrics = ref(false)

const {coverImage, lyrics, loading: loadingMetadata} = useAudioMetadata(
  computed(() => props.track.id),
)

/** 当前高亮行索引 */
const activeLineIndex = computed(() => {
  if (!lyrics.value.length) return -1
  return lyrics.value.findIndex((line, index) => {
    const next = lyrics.value[index + 1]
    return currentTime.value >= line.time && (!next || currentTime.value < next.time)
  })
})

/** 当前行的逐字高亮进度 */
const karaokeProgress = computed(() => {
  const index = activeLineIndex.value
  if (index < 0) return 0
  const line = lyrics.value[index]
  if (!line) return 0
  return calcKaraokeProgress(currentTime.value, line.time, lyrics.value[index + 1]?.time ?? null)
})

function togglePlay(): void {
  const audio = audioEl.value
  if (!audio) return
  if (isPlaying.value) audio.pause()
  else void audio.play().catch(() => {
    // 浏览器自动播放策略拦截时忽略（用户再点一次即可）
  })
}

function seek(time: number): void {
  const audio = audioEl.value
  if (audio) audio.currentTime = time
}

function changeVolume(value: number): void {
  volume.value = value
  const audio = audioEl.value
  if (audio) audio.volume = value
}

function onTimeUpdate(event: Event): void {
  currentTime.value = (event.target as HTMLAudioElement).currentTime
}

function onLoadedMetadata(event: Event): void {
  const value = (event.target as HTMLAudioElement).duration
  duration.value = Number.isFinite(value) ? value : 0
}

function onKeydown(event: KeyboardEvent): void {
  if (event.key === 'Escape') minimized.value = !minimized.value
}

onMounted(() => window.addEventListener('keydown', onKeydown))
onBeforeUnmount(() => window.removeEventListener('keydown', onKeydown))
</script>

<template>
  <div>
    <!-- audio 固定在此处，不被任何条件分支卸载（保证切换视图不打断播放） -->
    <audio
      ref="audioEl"
      :src="props.track.url"
      preload="auto"
      @ended="isPlaying = false"
      @loadedmetadata="onLoadedMetadata"
      @pause="isPlaying = false"
      @play="isPlaying = true"
      @timeupdate="onTimeUpdate"
    />

    <template v-if="minimized">
      <!-- 桌面歌词开关（阻止冒泡，避免误触迷你播放器的播放/暂停） -->
      <button
        v-if="lyrics.length"
        :title="showDesktopLyrics ? '关闭桌面歌词' : '打开桌面歌词'"
        aria-label="桌面歌词"
        class="fixed bottom-24 right-4 z-[66] flex h-9 w-9 items-center justify-center rounded-full border border-white/10 bg-black/60 backdrop-blur transition-colors hover:bg-white/10"
        type="button"
        @click.stop="showDesktopLyrics = !showDesktopLyrics"
        @pointerdown.stop
      >
        <Icon
          :class="showDesktopLyrics ? 'text-purple-500' : 'text-white/70'"
          class="h-4 w-4"
          name="mic-vocal"
        />
      </button>

      <DesktopLyrics
        :active-line-index="activeLineIndex"
        :karaoke-progress="karaokeProgress"
        :lyrics="lyrics"
        :visible="showDesktopLyrics"
        @visibility-change="showDesktopLyrics = $event"
      />

      <MiniPlayer
        :cover-image="coverImage"
        :current-time="currentTime"
        :duration="duration"
        :is-playing="isPlaying"
        :name="props.track.name"
        @close="emit('close')"
        @restore="minimized = false"
        @toggle-play="togglePlay"
      />
    </template>

    <div v-else class="fixed inset-0 z-50 flex flex-col bg-black">
      <PlayerView
        :active-line-index="activeLineIndex"
        :cover-image="coverImage"
        :current-time="currentTime"
        :duration="duration"
        :is-playing="isPlaying"
        :karaoke-progress="karaokeProgress"
        :loading-metadata="loadingMetadata"
        :lyrics="lyrics"
        :name="props.track.name"
        :volume="volume"
        @minimize="minimized = true"
        @seek="seek"
        @toggle-play="togglePlay"
        @volume-change="changeVolume"
      />
    </div>
  </div>
</template>

// frontend-astro/src/components/pages/media/AudioPlayer/AudioLayer.tsx
import React, {useRef, useState, useEffect} from 'react';
import type {MediaFile} from '@/lib/api';
import {getConfig} from '@/lib/config';
import {getFullMediaUrl} from '@/lib/utils';
import {LyricLine} from './helpers';
import PlayerView from './PlayerView';
import {MiniPlayerWrapper} from './MiniPlayer';
import DesktopLyrics from '@/components/audio/DesktopLyrics';

/* ========== AudioLayer (持久音频层) ========== */

const AudioLayer: React.FC<{ media: MediaFile; onClose: () => void }> = ({media, onClose}) => {
  const fullUrl = getFullMediaUrl(media.url);
  const [minimized, setMinimized] = useState(false);

  // 共享 audio 元素 — 全程由 AudioLayer 持有
  const audioRef = useRef<HTMLAudioElement>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [lyrics, setLyrics] = useState<LyricLine[]>([]);

  // 歌词高亮状态
  const [activeLineIndex, setActiveLineIndex] = useState(-1);
  const [karaokeProgress, setKaraokeProgress] = useState(0);

  // 桌面歌词设置
  const [showDesktopLyrics, setShowDesktopLyrics] = useState(false);

  // audio 事件监听
  useEffect(() => {
    const a = audioRef.current;
    if (!a) return;
    const onTime = () => setCurrentTime(a.currentTime);
    const onDur = () => setDuration(a.duration);
    const onPlay = () => setIsPlaying(true);
    const onPause = () => setIsPlaying(false);
    const onEnd = () => setIsPlaying(false);
    a.addEventListener('timeupdate', onTime);
    a.addEventListener('loadedmetadata', onDur);
    a.addEventListener('play', onPlay);
    a.addEventListener('pause', onPause);
    a.addEventListener('ended', onEnd);
    return () => {
      a.removeEventListener('timeupdate', onTime);
      a.removeEventListener('loadedmetadata', onDur);
      a.removeEventListener('play', onPlay);
      a.removeEventListener('pause', onPause);
      a.removeEventListener('ended', onEnd);
    };
  }, []);

  const togglePlay = () => {
    const a = audioRef.current;
    if (!a) return;
    if (isPlaying) a.pause(); else a.play();
  };

  const handleSeek = (time: number) => {
    const a = audioRef.current;
    if (a) a.currentTime = time;
  };

  // 加载元数据
  useEffect(() => {
    fetch(`${getConfig().API_BASE_URL}/api/v2/media/${media.id}/metadata`, {credentials: 'include'})
      .then(r => r.json())
      .then(result => {
        if (result.success && result.data) {
          if (result.data.lyrics?.length) setLyrics(result.data.lyrics);
        }
      })
      .catch(() => {});
  }, [media.id]);

  // 桌面歌词默认关闭，用户通过按钮开启
  useEffect(() => {
    // 不再从 localStorage 读取 visible 状态，由用户主动触发
  }, [lyrics]);

  // 更新歌词高亮
  useEffect(() => {
    if (!lyrics.length) return;
    const idx = lyrics.findIndex((l, i) => {
      const next = lyrics[i + 1];
      return currentTime >= l.time && (!next || currentTime < next.time);
    });
    setActiveLineIndex(idx);
    if (idx >= 0) {
      const line = lyrics[idx];
      const nextTime = lyrics[idx + 1]?.time ?? line.time + 3;
      const progress = Math.max(0, Math.min(1, (currentTime - line.time) / (nextTime - line.time)));
      setKaraokeProgress(progress);
    }
  }, [currentTime, lyrics]);

  // ESC 切换最小化
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setMinimized(m => !m);
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, []);

  // 共享给子组件
  const sharedAudioProps = {
    audioRef,
    isPlaying,
    currentTime,
    duration,
    togglePlay,
    handleSeek,
  };

  return (
    <>
      {/* audio 永远在这个位置，不被条件分支卸载 */}
      <audio ref={audioRef} src={fullUrl} preload="auto"/>

      {minimized ? (
        <>
          <DesktopLyrics
            lyrics={lyrics}
            activeLineIndex={activeLineIndex}
            karaokeProgress={karaokeProgress}
            visible={showDesktopLyrics}
            onVisibilityChange={setShowDesktopLyrics}
          />
          {/* 桌面歌词开关（stopPropagation 防止误触 MiniPlayer 的 togglePlay） */}
          {lyrics.length > 0 && (
            <button
              onClick={(e) => { e.stopPropagation(); setShowDesktopLyrics(v => !v); }}
              onPointerDown={(e) => e.stopPropagation()}
              className="fixed bottom-24 right-4 z-[66] w-9 h-9 rounded-full bg-black/60 backdrop-blur border border-white/10 flex items-center justify-center hover:bg-white/10 transition-colors"
              aria-label="桌面歌词"
              title="桌面歌词"
            >
              <svg className="w-4 h-4 text-white/70" fill="none" viewBox="0 0 24 24" stroke={showDesktopLyrics ? '#a855f7' : 'currentColor'} strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 19V6l12-3v13M9 19c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zm12-3c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zM9 10l12-3"/>
              </svg>
            </button>
          )}
          <MiniPlayerWrapper
            media={media}
            fullUrl={fullUrl}
            onRestore={() => setMinimized(false)}
            onClose={onClose}
            {...sharedAudioProps}
          />
        </>
      ) : (
        <div className="fixed inset-0 z-50 flex flex-col bg-black">
          <PlayerView
            media={media}
            fullUrl={fullUrl}
            onMinimize={() => setMinimized(true)}
            {...sharedAudioProps}
          />
        </div>
      )}
    </>
  );
};

export default AudioLayer;
