// frontend/web/src/components/site/audio/MiniPlayer.vue
<script lang="ts" setup>
import {computed, onBeforeUnmount, ref, watch} from 'vue'

/**
 * 迷你播放器（播放器最小化后的形态）
 *
 * 对应 astro 版 `AudioPlayer/MiniPlayer.tsx`：
 * - 桌面（≥sm）：左下角卡片，含封面 / 歌名 / 进度条 / 播放暂停 / 关闭
 * - 移动端（<sm）：右上角黑胶圆片，**长按 500ms** 弹出菜单（展开播放器 / 关闭播放）
 *
 * 原实现里 `MiniPlayerWrapper` 又单独拉了一次音频封面（与 `AudioLayer`、
 * `PlayerView` 重复，3 次请求），这里封面由 `AudioLayer` 统一传入。
 */
const props = withDefaults(
  defineProps<{
    name?: string
    coverImage?: string | null
    isPlaying?: boolean
    currentTime?: number
    duration?: number
  }>(),
  {name: '', coverImage: null, isPlaying: false, currentTime: 0, duration: 0},
)

const emit = defineEmits<{
  (e: 'toggle-play'): void
  (e: 'restore'): void
  (e: 'close'): void
}>()

const showMenu = ref(false)
let pressTimer: ReturnType<typeof setTimeout> | undefined

const progressPercent = computed(() =>
  props.duration ? (props.currentTime / props.duration) * 100 : 0,
)

function closeMenu(): void {
  showMenu.value = false
}

function onTouchStart(): void {
  pressTimer = setTimeout(() => {
    showMenu.value = true
  }, 500)
}

function onTouchEnd(): void {
  if (pressTimer) clearTimeout(pressTimer)
}

/** 菜单打开时点空白处关闭 */
watch(showMenu, (open) => {
  if (open) window.addEventListener('click', closeMenu)
  else window.removeEventListener('click', closeMenu)
})

onBeforeUnmount(() => {
  window.removeEventListener('click', closeMenu)
  if (pressTimer) clearTimeout(pressTimer)
})
</script>

<template>
  <div>
    <!-- 桌面：左下角迷你卡片 -->
    <div
      class="fixed bottom-4 left-4 z-[60] hidden overflow-hidden rounded-2xl border border-white/10 bg-black/90 shadow-2xl backdrop-blur-2xl sm:flex"
      style="padding-bottom: env(safe-area-inset-bottom, 0px)"
    >
      <div class="flex min-w-[260px] max-w-[320px] items-center gap-3 p-3">
        <button
          class="h-12 w-12 shrink-0 cursor-pointer overflow-hidden rounded-xl active:scale-90"
          title="展开播放器"
          type="button"
          @click="emit('restore')"
        >
          <img v-if="coverImage" :alt="''" :src="coverImage" class="h-full w-full object-cover">
          <span v-else
                class="flex h-full w-full items-center justify-center bg-gradient-to-br from-purple-600 to-pink-600">
            <Icon class="h-6 w-6 text-white/70" name="music"/>
          </span>
        </button>

        <div class="min-w-0 flex-1">
          <button
            class="block w-full truncate text-left text-sm font-medium text-white"
            type="button"
            @click="emit('restore')"
          >{{ name }}
          </button>
          <div class="mt-1.5 h-0.5 w-full overflow-hidden rounded-full bg-white/10">
            <div
              :style="{width: `${progressPercent}%`}"
              class="h-full rounded-full bg-gradient-to-r from-purple-500 to-pink-500 transition-all duration-200"
            />
          </div>
        </div>

        <div class="flex items-center gap-1">
          <button
            :aria-label="isPlaying ? '暂停' : '播放'"
            class="flex h-9 w-9 items-center justify-center rounded-full bg-white/10 transition-colors hover:bg-white/20 active:scale-90"
            type="button"
            @click="emit('toggle-play')"
          >
            <Icon :name="isPlaying ? 'pause' : 'play'" class="h-4 w-4 text-white"/>
          </button>
          <button
            aria-label="关闭"
            class="flex h-9 w-9 items-center justify-center rounded-full bg-white/5 transition-colors hover:bg-white/15 active:scale-90"
            type="button"
            @click="emit('close')"
          >
            <Icon class="h-4 w-4 text-white/60" name="x"/>
          </button>
        </div>
      </div>
    </div>

    <!-- 移动端：右上角黑胶 -->
    <div
      class="fixed right-4 top-4 z-[60] sm:hidden"
      @click="emit('toggle-play')"
      @touchend="onTouchEnd"
      @touchstart="onTouchStart"
    >
      <div
        :class="{ 'is-playing': isPlaying }"
        class="vinyl-mini-disc relative h-16 w-16 cursor-pointer overflow-hidden rounded-full border-2 border-white/20 shadow-2xl"
      >
        <img v-if="coverImage" :alt="''" :src="coverImage" class="h-full w-full object-cover">
        <span v-else
              class="flex h-full w-full items-center justify-center bg-gradient-to-br from-purple-600 to-pink-600">
          <Icon class="h-8 w-8 text-white/80" name="music"/>
        </span>
        <span class="absolute inset-x-0 bottom-0 flex h-5 items-center justify-center bg-black/50 px-1 backdrop-blur">
          <span class="truncate text-[9px] font-medium leading-none text-white">{{ name }}</span>
        </span>
      </div>
    </div>

    <!-- 移动端长按菜单 -->
    <div
      v-if="showMenu"
      class="fixed inset-0 z-[70] flex items-end justify-center bg-black/40 pb-20 sm:hidden"
      @click="closeMenu"
    >
      <div
        class="w-64 rounded-2xl border border-white/10 bg-neutral-900/95 p-4 shadow-2xl backdrop-blur-2xl"
        @click.stop
      >
        <p class="mb-4 truncate text-center font-semibold text-white">{{ name }}</p>
        <div class="space-y-2">
          <button
            class="flex w-full items-center gap-3 rounded-xl bg-white/10 px-4 py-3 text-sm font-medium text-white transition-colors hover:bg-white/20"
            type="button"
            @click="closeMenu(); emit('restore')"
          >
            <Icon class="h-5 w-5" name="expand"/>
            展开播放器
          </button>
          <button
            class="flex w-full items-center gap-3 rounded-xl bg-red-500/20 px-4 py-3 text-sm font-medium text-red-400 transition-colors hover:bg-red-500/30"
            type="button"
            @click="closeMenu(); emit('close')"
          >
            <Icon class="h-5 w-5" name="x"/>
            关闭播放
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.vinyl-mini-disc.is-playing {
  animation: mini-spin 8s linear infinite;
}

@keyframes mini-spin {
  to {
    transform: rotate(360deg);
  }
}

@media (prefers-reduced-motion: reduce) {
  .vinyl-mini-disc.is-playing {
    animation: none;
  }
}
</style>

// frontend-astro/src/components/pages/media/AudioPlayer/MiniPlayer.tsx
import React, {useState, useEffect, useRef} from 'react';
import {motion} from 'framer-motion';
import {Music} from 'lucide-react';
import type {MediaFile} from '@/lib/api';
import {getConfig} from '@/lib/config';
import {formatTime} from './helpers';

/* ========== MiniPlayer (最小化播放) ========== */

interface MiniPlayerProps {
  media: MediaFile;
  fullUrl: string;
  isPlaying: boolean;
  onTogglePlay: () => void;
  onRestore: () => void;
  onClose: () => void;
  coverImage: string | null;
  currentTime: number;
  duration: number;
  formatTimeFn: (t: number) => string;
  audioRef: React.RefObject<HTMLAudioElement | null>;
}

const MiniPlayer: React.FC<MiniPlayerProps> = ({
  media, coverImage, isPlaying, onTogglePlay, onRestore, onClose,
  currentTime, duration, audioRef,
}) => {
  const [showMenu, setShowMenu] = useState(false);
  const longPressTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);

  const handleTouchStart = () => {
    longPressTimer.current = setTimeout(() => setShowMenu(true), 500);
  };
  const handleTouchEnd = () => {
    if (longPressTimer.current) clearTimeout(longPressTimer.current);
  };

  // 点击外部关闭菜单
  useEffect(() => {
    if (!showMenu) return;
    const handler = () => setShowMenu(false);
    window.addEventListener('click', handler);
    return () => window.removeEventListener('click', handler);
  }, [showMenu]);

  return (
    <>
      {/* 桌面端：左下角迷你卡片 */}
      <motion.div
        initial={{x: -100, opacity: 0}}
        animate={{x: 0, opacity: 1}}
        exit={{x: -100, opacity: 0}}
        className="hidden sm:flex fixed bottom-4 left-4 z-[60] bg-black/90 backdrop-blur-2xl rounded-2xl border border-white/10 shadow-2xl overflow-hidden"
        style={{paddingBottom: 'env(safe-area-inset-bottom, 0px)'}}
      >
        <div className="flex items-center gap-3 p-3 min-w-[260px] max-w-[320px]">
          {/* 封面 */}
          <motion.div
            className="w-12 h-12 rounded-xl overflow-hidden shrink-0 cursor-pointer"
            whileTap={{scale: 0.9}}
            onClick={onRestore}
            animate={isPlaying ? {rotate: 360} : {rotate: 0}}
            transition={isPlaying ? {duration: 8, ease: 'linear', repeat: Infinity} : {duration: 0.4}}
          >
            {coverImage ? (
              <img src={coverImage} alt="" className="w-full h-full object-cover"/>
            ) : (
              <div className="w-full h-full bg-gradient-to-br from-purple-600 to-pink-600 flex items-center justify-center">
                <Music className="w-6 h-6 text-white/70"/>
              </div>
            )}
          </motion.div>

          {/* 歌名 + 进度条 */}
          <div className="flex-1 min-w-0">
            <p className="text-white text-sm font-medium truncate cursor-pointer" onClick={onRestore}>{media.original_filename}</p>
            <div className="w-full h-0.5 rounded-full bg-white/10 mt-1.5 overflow-hidden">
              <div className="h-full bg-gradient-to-r from-purple-500 to-pink-500 rounded-full transition-all duration-200"
                style={{width: `${duration ? (currentTime / duration) * 100 : 0}%`}}
              />
            </div>
          </div>

          {/* 控制按钮 */}
          <div className="flex items-center gap-1">
            <motion.button whileTap={{scale: 0.85}} onClick={onTogglePlay}
              className="w-9 h-9 bg-white/10 hover:bg-white/20 rounded-full flex items-center justify-center transition-colors"
              aria-label={isPlaying ? '暂停' : '播放'}>
              {isPlaying ? (
                <svg className="w-4 h-4 text-white" fill="currentColor" viewBox="0 0 24 24"><path d="M6 19h4V5H6v14zm8-14v14h4V5h-4z"/></svg>
              ) : (
                <svg className="w-4 h-4 text-white ml-0.5" fill="currentColor" viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg>
              )}
            </motion.button>
            <motion.button whileTap={{scale: 0.85}} onClick={onClose}
              className="w-9 h-9 bg-white/5 hover:bg-white/15 rounded-full flex items-center justify-center transition-colors"
              aria-label="关闭">
              <svg className="w-4 h-4 text-white/60" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12"/>
              </svg>
            </motion.button>
          </div>
        </div>
      </motion.div>

      {/* 移动端：右上角黑胶迷你播放器 */}
      <motion.div
        initial={{y: -80, opacity: 0}}
        animate={{y: 0, opacity: 1}}
        exit={{y: -80, opacity: 0}}
        className="sm:hidden fixed top-4 right-4 z-[60]"
        onTouchStart={handleTouchStart}
        onTouchEnd={handleTouchEnd}
        onClick={onTogglePlay}
      >
        <motion.div
          className="w-16 h-16 rounded-full overflow-hidden shadow-2xl border-2 border-white/20 cursor-pointer relative"
          animate={isPlaying ? {rotate: 360} : {rotate: 0}}
          transition={isPlaying ? {duration: 8, ease: 'linear', repeat: Infinity} : {duration: 0.4}}
        >
          {coverImage ? (
            <img src={coverImage} alt="" className="w-full h-full object-cover"/>
          ) : (
            <div className="w-full h-full bg-gradient-to-br from-purple-600 to-pink-600 flex items-center justify-center">
              <Music className="w-8 h-8 text-white/80"/>
            </div>
          )}
          {/* 底部半透明条显示歌名 */}
          <div className="absolute inset-x-0 bottom-0 h-5 bg-black/50 backdrop-blur flex items-center justify-center px-1">
            <p className="text-[9px] text-white font-medium truncate leading-none">{media.original_filename}</p>
          </div>
        </motion.div>
      </motion.div>

      {/* 长按菜单 (移动端) */}
      {showMenu && (
        <div className="sm:hidden fixed z-[70] inset-0 bg-black/40 flex items-end justify-center pb-20"
          onClick={() => setShowMenu(false)}>
          <motion.div
            initial={{y: 100, opacity: 0}}
            animate={{y: 0, opacity: 1}}
            className="bg-neutral-900/95 backdrop-blur-2xl rounded-2xl w-64 p-4 border border-white/10 shadow-2xl"
            onClick={e => e.stopPropagation()}
          >
            <p className="text-white font-semibold text-center mb-4 truncate">{media.original_filename}</p>
            <div className="space-y-2">
              <button onClick={() => { setShowMenu(false); onRestore(); }}
                className="w-full py-3 px-4 bg-white/10 hover:bg-white/20 rounded-xl text-white text-sm font-medium transition-colors flex items-center gap-3">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4"/>
                </svg>
                展开播放器
              </button>
              <button onClick={() => { setShowMenu(false); onClose(); }}
                className="w-full py-3 px-4 bg-red-500/20 hover:bg-red-500/30 rounded-xl text-red-400 text-sm font-medium transition-colors flex items-center gap-3">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12"/>
                </svg>
                关闭播放
              </button>
            </div>
          </motion.div>
        </div>
      )}
    </>
  );
};

/* ========== MiniPlayerWrapper (使用共享 audioRef) ========== */

interface MiniPlayerWrapperProps {
  media: MediaFile;
  fullUrl: string;
  onRestore: () => void;
  onClose: () => void;
  audioRef: React.RefObject<HTMLAudioElement | null>;
  isPlaying: boolean;
  currentTime: number;
  duration: number;
  togglePlay: () => void;
  handleSeek?: (t: number) => void;
}

const MiniPlayerWrapper: React.FC<MiniPlayerWrapperProps> = ({
  media, fullUrl, onRestore, onClose, audioRef, isPlaying, currentTime, duration, togglePlay,
}) => {
  const [coverImage, setCoverImage] = useState<string | null>(null);

  useEffect(() => {
    fetch(`${getConfig().API_BASE_URL}/api/v2/media/${media.id}/metadata`, {credentials: 'include'})
      .then(r => r.json())
      .then(result => {
        if (result.success && result.data?.cover_image) setCoverImage(result.data.cover_image);
      })
      .catch(() => {});
  }, [media.id]);

  return (
    <MiniPlayer
      media={media}
      fullUrl={fullUrl}
      isPlaying={isPlaying}
      onTogglePlay={togglePlay}
      onRestore={onRestore}
      onClose={onClose}
      coverImage={coverImage}
      currentTime={currentTime}
      duration={duration}
      formatTimeFn={formatTime}
      audioRef={audioRef}
    />
  );
};

export {MiniPlayer, MiniPlayerWrapper};
