// frontend-astro/src/components/MobileBottomNav.tsx
/**
 * 移动端底部导航栏 - React 岛屿
 * 适配 Astro：使用 <a> 替代 next/link, window.location 替代 usePathname
 * 性能优化：React.memo, 触摸适配, 安全区域
 */

'use client';

import {memo, useEffect, useState} from 'react';
import {Compass, Home, MessageSquare, PlusSquare, User} from 'lucide-react';

const navItems = [
  {name: '首页', href: '/', icon: Home},
  {name: '探索', href: '/articles', icon: Compass},
  {name: '消息', href: '/messages', icon: MessageSquare},
  {name: '创建', href: '/admin/editor', icon: PlusSquare},
  {name: '我的', href: '/profile', icon: User},
];

const NavItem = memo(({item, isActive}: { item: typeof navItems[0]; isActive: boolean }) => {
  const Icon = item.icon;
  return (
    <a
      href={item.href}
      aria-current={isActive ? 'page' : undefined}
      className={`flex flex-col items-center justify-center px-3 py-2 text-xs transition-colors touch-manipulation ${
        isActive ? 'text-blue-600 dark:text-blue-400' : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'
      }`}
    >
      <Icon className="w-6 h-6 mb-1" strokeWidth={isActive ? 2.5 : 2}/>
      <span>{item.name}</span>
    </a>
  );
});

NavItem.displayName = 'NavItem';

const MobileBottomNav = () => {
  const [pathname, setPathname] = useState(() => typeof window !== 'undefined' ? window.location.pathname : '/');
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const checkMobile = () => setIsMobile(window.innerWidth < 768);
    checkMobile();
    window.addEventListener('resize', checkMobile);
    return () => window.removeEventListener('resize', checkMobile);
  }, []);

  if (!isMobile) return null;

  return (
    <nav
      className="fixed bottom-0 left-0 right-0 z-50 bg-white dark:bg-gray-900 border-t border-gray-200 dark:border-gray-800 md:hidden mobile-bottom-nav touch-manipulation"
      role="navigation"
      aria-label="移动端导航"
    >
      <div className="flex items-center justify-around h-16 safe-pb">
        {navItems.map((item) => (
          <NavItem key={item.href} item={item} isActive={pathname === item.href}/>
        ))}
            </div>
        </nav>
    );
};

export default memo(MobileBottomNav);

// frontend/web/src/components/site/MobileBottomNav.vue
<script lang="ts" setup>
import type {IconName} from '@/lib/icons'

/**
 * 移动端底部导航
 *
 * 对应 astro 版 `components/MobileBottomNav.tsx`（React 岛）。
 *
 * **入口是与用户确认后重设的**：原版 5 个入口里，`/messages`（站内信，v3 无接口）
 * 与 `/admin/editor`（Nuxt 侧不存在）都不可用，所以改为 3 个实际存在的：
 * 首页 / 关于 / 我的。
 *
 * 与原实现的两点差异：
 *  1. 原版用 JS 判断 `window.innerWidth < 768` 决定是否渲染 —— 首屏会闪一下；
 *     这里改用 CSS `md:hidden`，SSR 直接不输出，更稳。
 *  2. 原版写死灰阶色（`text-gray-500` / `text-blue-600`），这里用语义令牌，
 *     跟随主题与用户自选配色。
 */
const navItems: Array<{ name: string; href: string; icon: IconName }> = [
  {name: '首页', href: '/', icon: 'house'},
  {name: '关于', href: '/about', icon: 'info'},
  {name: '我的', href: '/profile', icon: 'user'},
]

const route = useRoute()

/** 首页精确匹配，其余按前缀匹配（如 /about 的子路径也算选中） */
function isActive(href: string): boolean {
  return href === '/' ? route.path === '/' : route.path.startsWith(href)
}
</script>

<template>
  <nav aria-label="移动端导航" class="fixed inset-x-0 bottom-0 z-50 border-t border-line bg-surface md:hidden">
    <div
      class="flex h-16 items-center justify-around"
      style="padding-bottom: env(safe-area-inset-bottom, 0px)"
    >
      <NuxtLink
        v-for="item in navItems"
        :key="item.href"
        :aria-current="isActive(item.href) ? 'page' : undefined"
        :class="isActive(item.href) ? 'text-primary' : 'text-fg-muted'"
        :to="item.href"
        class="flex flex-1 flex-col items-center justify-center py-2 text-xs transition-colors"
      >
        <Icon :name="item.icon" class="mb-1 h-6 w-6"/>
        <span>{{ item.name }}</span>
      </NuxtLink>
    </div>
  </nav>
</template>
