// frontend-astro/src/components/theme/ThemeArticleCard.tsx
'use client';

/**
 * ArticleCard 槽位组件 — 由主题契约 componentSlots.articleCard 决定卡片样式：
 * - "default"：标准卡片（grid=大图卡片 / list=横向条目），与默认渲染一致
 * - "compact"：紧凑卡片（更小封面、更少信息层级）
 *
 * 用于文章列表页（ArticleList）等公共列表。
 */
import React from 'react';
import {motion} from 'framer-motion';
import {BookOpen, Clock, Eye, Heart, Hash} from 'lucide-react';
import {getFullMediaUrl} from '@/lib/utils';
import {useThemeSlots} from '@/lib/theme-components';

interface Props {
  article: any;
  layout?: 'grid' | 'list';
  index?: number;
}

export default function ThemeArticleCard({article, layout = 'grid', index = 0}: Props) {
  const {articleCard} = useThemeSlots();
  const cover = article.cover_image ? getFullMediaUrl(article.cover_image) : '';
  const date = article.created_at ? new Date(article.created_at).toLocaleDateString('zh-CN') : '';
  const tag = article.tags?.[0];
  const href = `/view?slug=${article.slug}`;

  if (articleCard === 'compact') {
    // ── 紧凑变体 ──
    return (
      <motion.a key={article.id} initial={{opacity: 0, y: 12}} animate={{opacity: 1, y: 0}}
                transition={{delay: index * 0.04, duration: 0.35}}
                href={href}
                className="group flex items-center gap-4 p-3 rounded-xl border theme-border card-hover">
        {cover ? (
          <img src={cover} alt="" loading="lazy"
               className="w-20 h-16 rounded-lg object-cover flex-shrink-0"/>
        ) : (
          <div className="w-20 h-16 rounded-lg bg-gray-100 dark:bg-gray-800 flex items-center justify-center flex-shrink-0">
            <BookOpen className="w-5 h-5 text-gray-300 dark:text-gray-600"/>
          </div>
        )}
        <div className="min-w-0 flex-1">
          <h3 className="text-sm font-medium text-gray-900 dark:text-white line-clamp-2 group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">
            {article.title}
          </h3>
          <p className="mt-1 text-xs text-gray-400 flex items-center gap-2">
            <span className="flex items-center gap-1"><Clock className="w-3 h-3"/>{date}</span>
            {article.views !== undefined && (
              <span className="flex items-center gap-1"><Eye className="w-3 h-3"/>{article.views}</span>
            )}
          </p>
        </div>
      </motion.a>
    );
  }

  if (layout === 'list') {
    // ── 默认：横向条目（列表视图）──
    return (
      <motion.a key={article.id} initial={{opacity: 0, x: -20}} animate={{opacity: 1, x: 0}}
                transition={{delay: index * 0.03, duration: 0.4}}
                href={href}
                className="group flex gap-5 p-5 theme-bg rounded-2xl border theme-border card-hover">
        <div className="w-40 h-28 rounded-xl overflow-hidden bg-gray-50 dark:bg-gray-800 flex-shrink-0 hidden sm:block">
          {cover ? (
            <img src={cover} alt="" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" loading="lazy"/>
          ) : (
            <div className="w-full h-full flex items-center justify-center">
              <BookOpen className="w-6 h-6 text-gray-200 dark:text-gray-700"/>
            </div>
          )}
        </div>
        <div className="flex-1 min-w-0 flex flex-col justify-center">
          <div className="flex items-center gap-2 text-xs text-gray-400 mb-1.5">
            {tag && <span className="text-blue-600 dark:text-blue-400 font-medium">{tag}</span>}
            {tag && <span>·</span>}
            <span>{date}</span>
          </div>
          <h3 className="font-semibold text-gray-900 dark:text-white line-clamp-1 group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors mb-1">
            {article.title}
          </h3>
          <p className="text-sm text-gray-500 dark:text-gray-400 line-clamp-2">{article.excerpt || article.summary || ''}</p>
          <div className="flex items-center gap-4 text-xs text-gray-400 mt-2">
            <span className="flex items-center gap-1"><Eye className="w-3 h-3"/>{article.views || 0}</span>
            <span className="flex items-center gap-1"><Heart className="w-3 h-3"/>{article.likes || 0}</span>
          </div>
        </div>
      </motion.a>
    );
  }

  // ── 默认：网格卡片 ──
  return (
    <motion.a key={article.id} initial={{opacity: 0, y: 20}} animate={{opacity: 1, y: 0}}
              transition={{delay: index * 0.05, duration: 0.4}}
              href={href}
              className="group theme-bg rounded-2xl border theme-border overflow-hidden card-hover">
      <div className="aspect-[16/10] bg-gray-50 dark:bg-gray-800 overflow-hidden relative">
        {cover ? (
          <img src={cover} alt={article.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" loading="lazy"/>
        ) : (
          <div className="w-full h-full flex items-center justify-center">
            <BookOpen className="w-8 h-8 text-gray-200 dark:text-gray-700"/>
          </div>
        )}
        {article.category?.name && (
          <div className="absolute top-3 left-3">
            <span className="badge bg-white/90 dark:bg-gray-900/90 text-gray-700 dark:text-gray-300 backdrop-blur-sm text-[10px]">
              {article.category.name}
            </span>
          </div>
        )}
      </div>
      <div className="p-5">
        <div className="flex items-center gap-2 text-xs text-gray-400 mb-2.5">
          {tag && <span className="text-blue-600 dark:text-blue-400 font-medium flex items-center gap-0.5"><Hash className="w-3 h-3"/>{tag}</span>}
          {tag && <span>·</span>}
          <span className="flex items-center gap-1"><Clock className="w-3 h-3"/>{date}</span>
        </div>
        <h3 className="font-semibold text-gray-900 dark:text-white text-sm line-clamp-2 group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors leading-relaxed mb-2">
          {article.title}
        </h3>
        <p className="text-xs text-gray-400 line-clamp-2 mb-3">{article.excerpt || article.summary || ''}</p>
        <div className="flex items-center gap-3 text-xs text-gray-400">
          <span className="flex items-center gap-1"><Eye className="w-3 h-3"/>{article.views || 0}</span>
          <span className="flex items-center gap-1"><Heart className="w-3 h-3"/>{article.likes || 0}</span>
        </div>
      </div>
    </motion.a>
  );
}

// frontend/web/src/components/site/ThemeArticleCard.vue
<script lang="ts" setup>
/**
 * 主题化文章卡片
 *
 * 对应原 astro 的 `theme/ThemeArticleCard.tsx`：卡片样式由主题的
 * `componentSlots.articleCard` 决定（`default` 标准 / `compact` 紧凑），
 * 并支持 `grid`（竖向卡片）与 `list`（横向条目）两种布局。
 *
 * 与 `ArticleCard` 的关系：后者是固定样式的通用卡片；本组件在它之上增加了
 * 「主题可切换变体」这一层。默认变体下渲染效果与 `ArticleCard` 一致。
 */

import {useThemeSlots} from '@/composables/useThemeSlots'
import type {ArticleItem} from '@/types/content'
import {formatDate} from '@/utils/format'

const props = withDefaults(
  defineProps<{
    article: ArticleItem
    layout?: 'grid' | 'list'
    index?: number
  }>(),
  {layout: 'grid', index: 0},
)

const {slot} = useThemeSlots()

const variant = computed(() => slot('articleCard', 'default'))

const to = computed(() =>
  props.article.slug ? `/articles/${props.article.slug}` : `/articles/id/${props.article.id}`,
)
</script>

<template>
  <!-- 紧凑变体：小封面 + 横向信息，适合侧栏或密度高的列表 -->
  <article v-if="variant === 'compact'" class="group relative">
    <NuxtLink :to="to"
              class="flex items-center gap-3 rounded-card border border-line bg-surface p-3 transition-colors hover:border-line-strong">
      <DeferredImage
        v-if="props.article.cover_image"
        :alt="props.article.title"
        :src="props.article.cover_image"
        aspect="4/3"
        class="w-20 flex-shrink-0 rounded-control"
      />
      <div v-else class="flex h-16 w-20 flex-shrink-0 items-center justify-center rounded-control bg-surface-soft">
        <Icon class="h-5 w-5 text-fg-subtle" name="file-text"/>
      </div>

      <div class="min-w-0 flex-1">
        <h3 class="line-clamp-2 text-sm font-medium leading-snug text-fg transition-colors group-hover:text-primary">
          {{ props.article.title }}
        </h3>
        <div class="mt-1 flex items-center gap-3 text-xs text-fg-subtle">
          <span>{{ formatDate(props.article.published_at || props.article.created_at) }}</span>
          <span v-if="props.article.views" class="inline-flex items-center gap-1">
            <Icon class="h-3 w-3" name="eye"/>{{ props.article.views }}
          </span>
        </div>
      </div>
    </NuxtLink>
  </article>

  <!-- 标准变体 · 横向条目 -->
  <article v-else-if="props.layout === 'list'" class="group">
    <NuxtLink :to="to" class="flex gap-4">
      <DeferredImage
        v-if="props.article.cover_image"
        :alt="props.article.title"
        :src="props.article.cover_image"
        aspect="16/9"
        class="w-40 flex-shrink-0 rounded-card"
      />
      <div class="min-w-0 flex-1">
        <h3 class="text-base font-semibold leading-snug text-fg transition-colors group-hover:text-primary">
          {{ props.article.title }}
        </h3>
        <p v-if="props.article.summary" class="mt-1.5 line-clamp-2 text-sm leading-relaxed text-fg-muted">
          {{ props.article.summary }}
        </p>
        <div class="mt-2 flex items-center gap-4 text-xs text-fg-subtle">
          <span class="inline-flex items-center gap-1">
            <Icon class="h-3.5 w-3.5" name="calendar-days"/>
            {{ formatDate(props.article.published_at || props.article.created_at) }}
          </span>
          <Badge v-for="tag in (props.article.tags || []).slice(0, 2)" :key="tag" variant="secondary">{{ tag }}</Badge>
        </div>
      </div>
    </NuxtLink>
  </article>

  <!-- 标准变体 · 竖向卡片（默认） -->
  <article v-else class="group">
    <NuxtLink :to="to" class="block">
      <DeferredImage
        v-if="props.article.cover_image"
        :alt="props.article.title"
        :src="props.article.cover_image"
        class="mb-3 rounded-card"
      />
      <h3 class="text-base font-semibold leading-snug text-fg transition-colors group-hover:text-primary">
        {{ props.article.title }}
      </h3>
    </NuxtLink>

    <p v-if="props.article.summary" class="mt-1.5 line-clamp-2 text-sm leading-relaxed text-fg-muted">
      {{ props.article.summary }}
    </p>

    <div class="mt-2.5 flex items-center gap-4 text-xs text-fg-subtle">
      <span class="inline-flex items-center gap-1">
        <Icon class="h-3.5 w-3.5" name="calendar-days"/>
        {{ formatDate(props.article.published_at || props.article.created_at) }}
      </span>
      <span v-if="props.article.views" class="inline-flex items-center gap-1">
        <Icon class="h-3.5 w-3.5" name="eye"/>{{ props.article.views }}
      </span>
      <Badge v-for="tag in (props.article.tags || []).slice(0, 2)" :key="tag" variant="secondary">{{ tag }}</Badge>
    </div>
  </article>
</template>
