// plugins/sms-provider/frontend/admin/Page.vue
<script lang="ts" setup>
import {computed, onMounted, ref} from 'vue'

import {pluginAction} from '@/utils/pluginAction'

/**
 * 短信服务（sms-provider 插件后台页）
 *
 * 对应 `plugins/sms-provider/frontend/admin/Page.tsx`：
 * 服务商 / 签名 / 配置状态三张卡 + 测试发送 + 已配置凭据列表。
 */
interface Settings {
  provider?: string | null
  aliyun_sign_name?: string | null
  tencent_sign_name?: string | null
  aliyun_access_key_id?: string | null
  tencent_secret_id?: string | null
  twilio_account_sid?: string | null
}

const settings = ref<Settings>({})
const loading = ref(true)
const error = ref('')

const phone = ref('')
const code = ref('')
const sending = ref(false)
const sendResult = ref<{ success?: boolean; error?: string } | null>(null)

const providerLabel = computed(() => {
  switch (settings.value.provider) {
    case 'aliyun':
      return '阿里云'
    case 'tencent':
      return '腾讯云'
    case 'twilio':
      return 'Twilio'
    default:
      return '未配置'
  }
})

const signName = computed(
  () => settings.value.aliyun_sign_name || settings.value.tencent_sign_name || '—',
)

async function load(): Promise<void> {
  loading.value = true
  error.value = ''
  try {
    const response = await pluginAction<Settings>('sms-provider', 'get_settings')
    settings.value = response.data ?? {}
    if (!response.success) error.value = response.error || '加载配置失败'
  } finally {
    loading.value = false
  }
}

async function sendTest(): Promise<void> {
  if (!phone.value) return
  sending.value = true
  sendResult.value = null
  try {
    const response = await pluginAction<{ success?: boolean; error?: string }>('sms-provider', 'send_sms', {
      phone: phone.value,
      code: code.value || '123456',
    })
    sendResult.value = response.data ?? {success: response.success, error: response.error}
  } finally {
    sending.value = false
  }
}

onMounted(load)
</script>

<template>
  <div class="p-4">
    <div class="mb-3 flex justify-end">
      <el-button :loading="loading" size="small" @click="load">
        <Icon class="mr-1 h-3.5 w-3.5" name="refresh-cw"/>
        刷新
      </el-button>
    </div>

    <p v-if="error" class="mb-3 rounded-control bg-danger-soft px-3 py-2 text-sm text-danger">{{ error }}</p>

    <!-- 状态卡片 -->
    <div class="mb-6 grid grid-cols-1 gap-4 md:grid-cols-3">
      <div class="rounded-card border border-line bg-surface p-5">
        <div class="flex items-center gap-3">
          <span class="flex h-10 w-10 items-center justify-center rounded-control bg-primary-soft">
            <Icon class="h-5 w-5 text-primary" name="message-square"/>
          </span>
          <div>
            <p class="text-sm text-fg-muted">当前服务商</p>
            <p class="text-lg font-semibold text-fg">{{ providerLabel }}</p>
          </div>
        </div>
      </div>

      <div class="rounded-card border border-line bg-surface p-5">
        <div class="flex items-center gap-3">
          <span class="flex h-10 w-10 items-center justify-center rounded-control bg-success-soft">
            <Icon class="h-5 w-5 text-success" name="smartphone"/>
          </span>
          <div>
            <p class="text-sm text-fg-muted">签名</p>
            <p class="text-lg font-semibold text-fg">{{ signName }}</p>
          </div>
        </div>
      </div>

      <div class="rounded-card border border-line bg-surface p-5">
        <div class="flex items-center gap-3">
          <span class="flex h-10 w-10 items-center justify-center rounded-control bg-surface-soft">
            <Icon
              :class="settings.provider ? 'text-success' : 'text-fg-subtle'"
              :name="settings.provider ? 'circle-check' : 'circle-x'"
              class="h-5 w-5"
            />
          </span>
          <div>
            <p class="text-sm text-fg-muted">状态</p>
            <p class="text-lg font-semibold text-fg">{{ settings.provider ? '已配置' : '未配置' }}</p>
          </div>
        </div>
      </div>
    </div>

    <!-- 测试发送 -->
    <div class="mb-6 rounded-card border border-line bg-surface p-5">
      <h3 class="mb-4 text-sm font-semibold text-fg">测试短信发送</h3>
      <div class="flex flex-wrap gap-3">
        <el-input v-model="phone" class="min-w-[200px] flex-1" placeholder="手机号"/>
        <el-input v-model="code" class="w-40" placeholder="验证码（默认 123456）"/>
        <el-button :disabled="!phone" :loading="sending" type="primary" @click="sendTest">
          <Icon class="mr-1 h-4 w-4" name="send"/>
          发送测试
        </el-button>
      </div>

      <p
        v-if="sendResult"
        :class="sendResult.success ? 'bg-success-soft text-success' : 'bg-danger-soft text-danger'"
        class="mt-3 rounded-control p-3 text-xs"
      >
        {{ sendResult.success ? '✓ 发送成功' : `✗ 发送失败：${sendResult.error || '未知错误'}` }}
      </p>
    </div>

    <!-- 配置信息 -->
    <div class="rounded-card border border-line bg-surface p-5">
      <h3 class="mb-3 text-sm font-semibold text-fg">短信配置</h3>

      <div v-if="loading" class="space-y-3">
        <Skeleton class="h-5 w-52"/>
        <Skeleton class="h-5 w-40"/>
      </div>

      <div v-else class="space-y-2 text-sm text-fg-muted">
        <p v-if="settings.aliyun_access_key_id">阿里云：<code class="text-fg">已配置</code></p>
        <p v-if="settings.tencent_secret_id">腾讯云：<code class="text-fg">已配置</code></p>
        <p v-if="settings.twilio_account_sid">Twilio：<code class="text-fg">已配置</code></p>
        <p v-if="!settings.aliyun_access_key_id && !settings.tencent_secret_id && !settings.twilio_account_sid">
          暂未配置短信参数，请在插件设置中配置
        </p>
      </div>
    </div>
  </div>
</template>

// plugins/sms-provider/frontend/admin/Page.tsx
'use client';

import React, {useState} from 'react';
import {useMutation, useQuery} from '@tanstack/react-query';
import {AdminShell} from '@/components/admin/AdminShell';
import {apiClient} from '@/lib/api/base-client';
import {CheckCircle2, Loader2, MessageSquare, RefreshCw, Send, Smartphone, XCircle} from 'lucide-react';

const PLUGIN_SLUG = 'sms-provider';

function call(action: string, params: any = {}) {
  return apiClient.post(`/plugins/${PLUGIN_SLUG}/action`, {action, params});
}

function SmsProviderDashboard() {
  const [phone, setPhone] = useState('');
  const [code, setCode] = useState('');

  const {data: settings, isLoading: loadSettings, refetch} = useQuery({
    queryKey: ['sms-provider-settings'],
    queryFn: async () => {
      const r = await call('get_settings');
      return r.data || {};
    },
  });

  const sendTestMut = useMutation({
    mutationFn: () => call('send_sms', {phone, code: code || '123456'}),
  });

  const providerLabel = (p: string) => {
    switch (p) {
      case 'aliyun':
        return '阿里云';
      case 'tencent':
        return '腾讯云';
      case 'twilio':
        return 'Twilio';
      default:
        return '未配置';
    }
  };

  return (
    <AdminShell title="短信服务" actions={
      <button onClick={() => refetch()} disabled={loadSettings}
              className="flex items-center gap-1.5 px-4 py-2 border rounded-lg text-sm hover:bg-gray-50 dark:hover:bg-gray-800 disabled:opacity-50">
        <RefreshCw className={`w-4 h-4 ${loadSettings ? 'animate-spin' : ''}`}/> 刷新
      </button>
    }>
      {/* 当前服务商状态 */}
      <div className="mb-6 grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-white dark:bg-gray-900 rounded-xl border p-5">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-blue-100 dark:bg-blue-900/30 rounded-lg flex items-center justify-center">
              <MessageSquare className="w-5 h-5 text-blue-600 dark:text-blue-400"/>
            </div>
            <div>
              <p className="text-sm text-gray-500">当前服务商</p>
              <p className="text-lg font-semibold">{providerLabel(settings?.provider)}</p>
            </div>
          </div>
        </div>
        <div className="bg-white dark:bg-gray-900 rounded-xl border p-5">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-green-100 dark:bg-green-900/30 rounded-lg flex items-center justify-center">
              <Smartphone className="w-5 h-5 text-green-600 dark:text-green-400"/>
            </div>
            <div>
              <p className="text-sm text-gray-500">签名</p>
              <p
                className="text-lg font-semibold">{settings?.aliyun_sign_name || settings?.tencent_sign_name || '—'}</p>
            </div>
          </div>
        </div>
        <div className="bg-white dark:bg-gray-900 rounded-xl border p-5">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-purple-100 dark:bg-purple-900/30 rounded-lg flex items-center justify-center">
              {settings?.provider ? <CheckCircle2 className="w-5 h-5 text-green-600 dark:text-green-400"/> :
                <XCircle className="w-5 h-5 text-gray-400"/>}
            </div>
            <div>
              <p className="text-sm text-gray-500">状态</p>
              <p className="text-lg font-semibold">{settings?.provider ? '已配置' : '未配置'}</p>
            </div>
          </div>
        </div>
      </div>

      {/* 测试发送 */}
      <div className="bg-white dark:bg-gray-900 rounded-xl border p-5 mb-6">
        <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-4">测试短信发送</h3>
        <div className="flex flex-wrap gap-3">
          <input value={phone} onChange={e => setPhone(e.target.value)}
                 placeholder="手机号"
                 className="flex-1 min-w-[200px] px-3 py-2 border rounded-lg text-sm bg-white dark:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500"/>
          <input value={code} onChange={e => setCode(e.target.value)}
                 placeholder="验证码（默认 123456）"
                 className="w-40 px-3 py-2 border rounded-lg text-sm bg-white dark:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500"/>
          <button onClick={() => sendTestMut.mutate()} disabled={sendTestMut.isPending || !phone}
                  className="flex items-center gap-1.5 px-4 py-2 bg-blue-600 text-white text-sm rounded-lg hover:bg-blue-700 disabled:opacity-50">
            {sendTestMut.isPending ? '发送中...' : <><Send className="w-4 h-4"/> 发送测试</>}
          </button>
        </div>
        {sendTestMut.data && (
          <div
            className={`mt-3 p-3 rounded-lg text-xs ${sendTestMut.data.success ? 'bg-green-50 dark:bg-green-900/10 text-green-700 dark:text-green-400' : 'bg-red-50 dark:bg-red-900/10 text-red-700 dark:text-red-400'}`}>
            {sendTestMut.data.success ? '✓ 发送成功' : `✗ 发送失败: ${sendTestMut.data.error || '未知错误'}`}
          </div>
        )}
      </div>

      {/* 配置信息 */}
      <div className="bg-white dark:bg-gray-900 rounded-xl border p-5">
        <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">短信配置</h3>
        {loadSettings ? (
          <div className="flex justify-center py-8"><Loader2 className="w-6 h-6 animate-spin text-blue-500"/></div>
        ) : (
          <div className="text-sm text-gray-500 space-y-2">
            {settings?.aliyun_access_key_id &&
              <p>阿里云: <code className="text-gray-700 dark:text-gray-300">已配置</code></p>}
            {settings?.tencent_secret_id &&
              <p>腾讯云: <code className="text-gray-700 dark:text-gray-300">已配置</code></p>}
            {settings?.twilio_account_sid &&
              <p>Twilio: <code className="text-gray-700 dark:text-gray-300">已配置</code></p>}
            {!settings?.aliyun_access_key_id && !settings?.tencent_secret_id && !settings?.twilio_account_sid &&
              <p>暂未配置短信参数，请在插件设置中配置</p>}
          </div>
        )}
      </div>
    </AdminShell>
  );
}

export default function SmsProviderPage() {
  return <SmsProviderDashboard/>;
}
