// frontend-astro/src/components/pages/media/AudioPlayer/PlayerView.tsx
import React, {useState, useEffect} from 'react';
import {motion} from 'framer-motion';
import type {MediaFile} from '@/lib/api';
import {getConfig} from '@/lib/config';
import {LyricLine, calcKaraokeProgress} from './helpers';
import VinylRecord from './VinylRecord';
import LyricsPanel from './LyricsPanel';
import ControlsBar from './ControlsBar';

interface PlayerViewProps {
  media: MediaFile;
  fullUrl: string;
  audioRef: React.RefObject<HTMLAudioElement | null>;
  isPlaying: boolean;
  currentTime: number;
  duration: number;
  togglePlay: () => void;
  handleSeek: (t: number) => void;
  onMinimize?: () => void;
}

const PlayerView: React.FC<PlayerViewProps> = ({
  media, fullUrl, audioRef, isPlaying, currentTime, duration,
  togglePlay, handleSeek, onMinimize,
}) => {
  const [volume, setVolume] = useState(1);
  const [showLyrics, setShowLyrics] = useState(false);

  // 音频元数据
  const [coverImage, setCoverImage] = useState<string | null>(null);
  const [lyrics, setLyrics] = useState<LyricLine[]>([]);
  const [loadingMetadata, setLoadingMetadata] = useState(true);

  // 当前高亮行索引
  const activeLineIndex = lyrics.findIndex((l, i) => {
    const next = lyrics[i + 1];
    return currentTime >= l.time && (!next || currentTime < next.time);
  });

  // 当前行的逐字进度
  const activeLine = activeLineIndex !== -1 ? lyrics[activeLineIndex] : null;
  const karaokeProgress = activeLine
    ? calcKaraokeProgress(
        currentTime,
        activeLine.time,
        lyrics[activeLineIndex + 1]?.time ?? null,
      )
    : 0;

  // 加载音频元数据
  useEffect(() => {
    const loadMetadata = async () => {
      try {
        setLoadingMetadata(true);
        const response = await fetch(`${getConfig().API_BASE_URL}/api/v2/media/${media.id}/metadata`, {
          credentials: 'include'
        });

        if (response.ok) {
          const result = await response.json();
          if (result.success && result.data) {
            if (result.data.cover_image) {
              setCoverImage(result.data.cover_image);
            }
            if (result.data.lyrics && result.data.lyrics.length > 0) {
              setLyrics(result.data.lyrics);
              setShowLyrics(true);
            }
          }
        }
      } catch (error) {
        console.error('加载音频元数据失败:', error);
      } finally {
        setLoadingMetadata(false);
      }
    };

    loadMetadata();
  }, [media.id]);

  const handleVolumeChange = (vol: number) => {
    const audio = audioRef.current;
    if (!audio) return;
    audio.volume = vol;
    setVolume(vol);
  };

  return (
    <div className="flex flex-col h-full bg-black select-none">
      {/* ====== Main Content Area ====== */}
      <div className="flex-1 flex flex-col lg:flex-row min-h-0 overflow-hidden">
        {/* 最小化按钮 (桌面左上角) */}
        <button
          onClick={onMinimize}
          className="absolute top-4 left-4 z-20 w-8 h-8 rounded-full bg-white/5 hover:bg-white/15 backdrop-blur flex items-center justify-center transition-colors hidden lg:flex"
          aria-label="最小化播放"
          title="最小化 (Esc)"
        >
          <svg className="w-4 h-4 text-white/70" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7"/>
          </svg>
        </button>

        {/* Left: Vinyl */}
        <VinylRecord
          coverImage={coverImage}
          loadingMetadata={loadingMetadata}
          isPlaying={isPlaying}
          onMinimize={onMinimize}
        />

        {/* Right: Lyrics */}
        <LyricsPanel
          media={media}
          coverImage={coverImage}
          lyrics={lyrics}
          showLyrics={showLyrics}
          onToggleLyrics={() => setShowLyrics(v => !v)}
          activeLineIndex={activeLineIndex}
          karaokeProgress={karaokeProgress}
          onMinimize={onMinimize}
        />
      </div>

      {/* ====== Bottom Controls Bar ====== */}
      <ControlsBar
        media={media}
        coverImage={coverImage}
        currentTime={currentTime}
        duration={duration}
        volume={volume}
        isPlaying={isPlaying}
        onSeek={handleSeek}
        onTogglePlay={togglePlay}
        onVolumeChange={handleVolumeChange}
        onMinimize={onMinimize}
      />
    </div>
  );
};

export default PlayerView;

// frontend/web/src/components/site/audio/PlayerView.vue
<script lang="ts" setup>
import {ref, watch} from 'vue'

import type {LyricLine} from './helpers'

/**
 * 全屏播放器视图：左黑胶 + 右歌词 + 底部控制条
 *
 * 对应 astro 版 `AudioPlayer/PlayerView.tsx`。
 * **一处结构改进**：原实现自己在 `PlayerView` 里又请求了一次音频元数据
 * （`AudioLayer` 和 `MiniPlayerWrapper` 也各请求一次，共 3 次）；
 * 现在由 `AudioLayer` 统一加载后向下传递，行为不变但少两次请求。
 */
const props = withDefaults(
  defineProps<{
    name?: string
    coverImage?: string | null
    loadingMetadata?: boolean
    lyrics?: LyricLine[]
    isPlaying?: boolean
    currentTime?: number
    duration?: number
    volume?: number
    activeLineIndex?: number
    karaokeProgress?: number
  }>(),
  {
    name: '',
    coverImage: null,
    loadingMetadata: false,
    lyrics: () => [],
    isPlaying: false,
    currentTime: 0,
    duration: 0,
    volume: 1,
    activeLineIndex: -1,
    karaokeProgress: 0,
  },
)

const emit = defineEmits<{
  (e: 'seek', time: number): void
  (e: 'toggle-play'): void
  (e: 'volume-change', volume: number): void
  (e: 'minimize'): void
}>()

const showLyrics = ref(false)

/** 歌词一就位就自动展开（与 astro 版一致） */
watch(
  () => props.lyrics.length,
  (length) => {
    if (length > 0) showLyrics.value = true
  },
)

function toggleLyrics(): void {
  showLyrics.value = !showLyrics.value
}
</script>

<template>
  <div class="flex h-full flex-col bg-black select-none">
    <!-- 主体：黑胶 + 歌词 -->
    <div class="flex min-h-0 flex-1 flex-col overflow-hidden lg:flex-row">
      <!-- 最小化（桌面左上角） -->
      <button
        aria-label="最小化播放"
        class="absolute left-4 top-4 z-20 hidden h-8 w-8 items-center justify-center rounded-full bg-white/5 backdrop-blur transition-colors hover:bg-white/15 lg:flex"
        title="最小化 (Esc)"
        type="button"
        @click="emit('minimize')"
      >
        <Icon class="h-4 w-4 text-white/70" name="chevron-down"/>
      </button>

      <VinylRecord
        :cover-image="coverImage"
        :is-playing="isPlaying"
        :loading="loadingMetadata"
        @minimize="emit('minimize')"
      />

      <LyricsPanel
        :active-line-index="activeLineIndex"
        :cover-image="coverImage"
        :karaoke-progress="karaokeProgress"
        :lyrics="lyrics"
        :name="name"
        :show-lyrics="showLyrics"
        @minimize="emit('minimize')"
        @toggle-lyrics="toggleLyrics"
      />
    </div>

    <!-- 底部控制条 -->
    <ControlsBar
      :cover-image="coverImage"
      :current-time="currentTime"
      :duration="duration"
      :is-playing="isPlaying"
      :name="name"
      :volume="volume"
      @minimize="emit('minimize')"
      @seek="emit('seek', $event)"
      @toggle-play="emit('toggle-play')"
      @volume-change="emit('volume-change', $event)"
    />
  </div>
</template>
