// plugins/popular-articles/frontend/admin/Page.vue
<script lang="ts" setup>
import {onMounted, ref, watch} from 'vue'

import {pluginAction} from '@/utils/pluginAction'

/**
 * 阅读排行（popular-articles 插件后台页）
 *
 * 对应 `plugins/popular-articles/frontend/admin/Page.tsx`。
 * 原实现的 `AuthGuard` / `QueryProvider` / `AdminShell` 在 Nuxt 侧由宿主页的
 * `middleware: 'auth'`、Vue 响应式、admin 布局承担，这里只实现内容。
 */
interface PopularArticle {
  id: number
  title?: string | null
  slug?: string | null
  views?: number | null
}

const MAX_OPTIONS = [5, 10, 15, 20]
const DAY_OPTIONS = [7, 14, 30, 90]

const maxItems = ref(5)
const days = ref(30)

const loading = ref(true)
const error = ref('')
const items = ref<PopularArticle[]>([])

async function load(): Promise<void> {
  loading.value = true
  error.value = ''
  try {
    const result = await pluginAction<PopularArticle[]>('popular-articles', 'get_popular', {
      max_items: maxItems.value,
      days: days.value,
    })
    items.value = Array.isArray(result.data) ? result.data : []
    if (!result.success) error.value = result.error || '加载失败'
  } finally {
    loading.value = false
  }
}

watch([maxItems, days], load)
onMounted(load)

/** 前三名高亮（与 astro 版一致） */
function rankClass(index: number): string {
  if (index === 0) return 'bg-amber-100 text-amber-700'
  if (index === 1) return 'bg-surface-soft text-fg-muted'
  if (index === 2) return 'bg-orange-100 text-orange-700'
  return 'text-fg-subtle'
}

function articleLink(item: PopularArticle): string {
  return item.slug ? `/articles/${item.slug}` : `/articles/id/${item.id}`
}
</script>

<template>
  <div class="p-4">
    <!-- 筛选 -->
    <div class="mb-3 flex flex-wrap items-center gap-4 text-sm text-fg-muted">
      <label class="flex items-center gap-1.5">
        <span>显示</span>
        <el-select v-model="maxItems" class="w-24" size="small">
          <el-option v-for="n in MAX_OPTIONS" :key="n" :label="String(n)" :value="n"/>
        </el-select>
      </label>
      <label class="flex items-center gap-1.5">
        <span>近</span>
        <el-select v-model="days" class="w-24" size="small">
          <el-option v-for="n in DAY_OPTIONS" :key="n" :label="`${n} 天`" :value="n"/>
        </el-select>
      </label>
      <el-button :loading="loading" link type="primary" @click="load">
        <Icon class="mr-1 h-3.5 w-3.5" name="refresh-cw"/>
        刷新
      </el-button>
    </div>

    <div v-if="loading" class="space-y-3">
      <Skeleton v-for="i in 5" :key="i" class="h-16 w-full"/>
    </div>

    <p v-else-if="error" class="rounded-control bg-danger-soft px-3 py-2 text-sm text-danger">{{ error }}</p>

    <EmptyState
      v-else-if="!items.length"
      description="文章需要有一定浏览量才会出现在这里"
      title="暂无热门文章"
    />

    <div v-else class="overflow-hidden rounded-card border border-line bg-surface">
      <div class="divide-y divide-line">
        <div
          v-for="(item, index) in items"
          :key="item.id"
          class="flex items-center gap-4 px-5 py-4 transition-colors hover:bg-surface-soft"
        >
          <span
            :class="rankClass(index)"
            class="flex h-8 w-8 items-center justify-center rounded-full text-sm font-bold"
          >{{ index + 1 }}</span>

          <div class="min-w-0 flex-1">
            <p class="truncate text-sm font-medium text-fg">{{ item.title || `#${item.id}` }}</p>
            <p class="text-xs text-fg-subtle">{{ item.views ?? 0 }} 次浏览</p>
          </div>

          <NuxtLink
            :to="articleLink(item)"
            class="whitespace-nowrap rounded-control px-3 py-1.5 text-xs text-primary transition-colors hover:bg-primary-soft"
            target="_blank"
          >查看
          </NuxtLink>
        </div>
      </div>
    </div>
  </div>
</template>

// plugins/popular-articles/frontend/admin/Page.tsx
import React, {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {AuthGuard} from '@/components/AuthGuard';
import {QueryProvider} from '@/components/QueryProvider';
import {AdminShell} from '@/components/admin/AdminShell';
import {apiClient} from '@/lib/api/base-client';
import {Flame, Loader2} from 'lucide-react';

const PLUGIN_SLUG = 'popular-articles';

function call(action: string, params: any = {}) {
  return apiClient.post(`/plugins/${PLUGIN_SLUG}/action`, {action, params});
}

/**
 * Popular Articles — 阅读排行管理页面
 */
function PopularRanking() {
  const [maxItems, setMaxItems] = useState(5);
  const [days, setDays] = useState(30);

  const {data: articles = [], isLoading} = useQuery({
    queryKey: ['popular-articles', maxItems, days],
    queryFn: async () => {
      const r = await call('get_popular', {max_items: maxItems, days});
      return r.data || [];
    },
    placeholderData: (prev: any) => prev || [],
  });

  return (
    <AdminShell title="阅读排行" actions={
      <div className="flex items-center gap-4 text-sm">
        <label className="flex items-center gap-1.5 text-gray-500">
          <span>显示</span>
          <select value={maxItems} onChange={e => setMaxItems(Number(e.target.value))}
                  className="border rounded-lg px-2 py-1 text-xs bg-white dark:bg-gray-800">
            {[5, 10, 15, 20].map(n => <option key={n} value={n}>{n}</option>)}
          </select>
        </label>
        <label className="flex items-center gap-1.5 text-gray-500">
          <span>近</span>
          <select value={days} onChange={e => setDays(Number(e.target.value))}
                  className="border rounded-lg px-2 py-1 text-xs bg-white dark:bg-gray-800">
            {[7, 14, 30, 90].map(n => <option key={n} value={n}>{n}天</option>)}
          </select>
        </label>
      </div>
    }>
      {isLoading ? (
        <div className="flex justify-center py-16"><Loader2 className="w-8 h-8 animate-spin text-blue-500"/></div>
      ) : articles.length === 0 ? (
        <div className="text-center py-16 text-gray-400">
          <Flame className="w-12 h-12 mx-auto mb-4 opacity-50"/>
          <p className="text-lg font-medium text-gray-500 dark:text-gray-400 mb-1">暂无热门文章</p>
          <p className="text-sm">文章需要有一定的浏览量才会出现在这里</p>
        </div>
      ) : (
        <div className="bg-white dark:bg-gray-900 rounded-xl border overflow-hidden">
          <div className="divide-y dark:divide-gray-800">
            {articles.map((a: any, i: number) => (
              <div key={a.id}
                   className="flex items-center gap-4 px-5 py-4 hover:bg-gray-50 dark:hover:bg-gray-800/30 transition-colors">
                <span className={`w-8 h-8 flex items-center justify-center rounded-full text-sm font-bold ${
                  i === 0 ? 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400' :
                    i === 1 ? 'bg-gray-100 text-gray-600 dark:bg-gray-700 dark:text-gray-300' :
                      i === 2 ? 'bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400' :
                        'text-gray-400'
                }`}>{i + 1}</span>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-gray-900 dark:text-white truncate">{a.title || `#${a.id}`}</p>
                  <p className="text-xs text-gray-400">{a.views ?? 0} 次浏览</p>
                </div>
                <a href={`/article/${a.slug || a.id}`} target="_blank" rel="noopener noreferrer"
                   className="px-3 py-1.5 text-xs text-blue-600 hover:bg-blue-50 dark:hover:bg-blue-900/20 rounded-lg transition-colors whitespace-nowrap">
                  查看
                </a>
              </div>
            ))}
          </div>
        </div>
      )}
    </AdminShell>
  );
}

export default function PopularArticlesPage() {
  return <AuthGuard><QueryProvider><PopularRanking/></QueryProvider></AuthGuard>;
}
