// plugins/enterprise/frontend/admin/Page.vue
<script lang="ts" setup>
import {computed, onMounted, ref, watch} from 'vue'

import {pluginAction} from '@/utils/pluginAction'

/**
 * 企业管理（enterprise 插件后台页）
 *
 * 对应 `plugins/enterprise/frontend/admin/Page.tsx`：
 * 6 个页签 —— 概览（8 个统计）+ 许可证 / 工单 / 脚本 / 日志 / 告警 五张列表（各 20 条/页）。
 * 列表用原生表格而不是 `el-table`：五个页签的列与徽标样式各不相同，
 * 配置驱动反而比模板更啰嗦（原实现也是这么写的）。
 */
interface EnterpriseItem {
  id?: number
  license_key?: string | null
  is_active?: boolean
  title?: string | null
  status?: string | null
  name?: string | null
  version?: string | null
  script_name?: string | null
  script_id?: number
  message?: string | null
  severity?: string | null
}

interface ListResult {
  items: EnterpriseItem[]
  total: number
}

interface Overview {
  total_licenses?: number
  active_licenses?: number
  open_tickets?: number
  in_progress_tickets?: number
  total_scripts?: number
  total_deployments?: number
  failed_deployments?: number
  unresolved_alerts?: number
}

type TabKey = 'overview' | 'licenses' | 'tickets' | 'scripts' | 'logs' | 'alerts'

const TABS: Array<{ key: TabKey; label: string; icon: string; action?: string }> = [
  {key: 'overview', label: '概览', icon: 'trending-up'},
  {key: 'licenses', label: '许可证', icon: 'shield', action: 'list_licenses'},
  {key: 'tickets', label: '工单', icon: 'clipboard-list', action: 'list_tickets'},
  {key: 'scripts', label: '脚本', icon: 'code-2', action: 'list_scripts'},
  {key: 'logs', label: '日志', icon: 'file-text', action: 'list_logs'},
  {key: 'alerts', label: '告警', icon: 'shield-alert', action: 'list_alerts'},
]

const PER_PAGE = 20

const tab = ref<TabKey>('overview')
const page = ref(1)
const loading = ref(false)
const error = ref('')

const overview = ref<Overview>({})
const items = ref<EnterpriseItem[]>([])
const total = ref(0)

const overviewCards = computed(() => [
  {label: '总许可证', value: overview.value.total_licenses},
  {label: '活跃许可证', value: overview.value.active_licenses},
  {label: '待处理工单', value: overview.value.open_tickets},
  {label: '进行中', value: overview.value.in_progress_tickets},
  {label: '部署脚本', value: overview.value.total_scripts},
  {label: '部署次数', value: overview.value.total_deployments},
  {label: '失败部署', value: overview.value.failed_deployments},
  {label: '未解决告警', value: overview.value.unresolved_alerts},
])

async function loadCurrent(): Promise<void> {
  loading.value = true
  error.value = ''
  try {
    if (tab.value === 'overview') {
      const result = await pluginAction<Overview>('enterprise', 'get_overview')
      overview.value = result.data ?? {}
      return
    }

    const entry = TABS.find((item) => item.key === tab.value)
    if (!entry?.action) return

    const result = await pluginAction<ListResult>('enterprise', entry.action, {
      page: page.value,
      per_page: PER_PAGE,
    })
    items.value = result.data?.items ?? []
    total.value = result.data?.total ?? 0
    if (!result.success) error.value = result.error || '加载失败'
  } finally {
    loading.value = false
  }
}

function switchTab(key: TabKey): void {
  tab.value = key
  page.value = 1
}

function tagClass(kind: 'success' | 'warning' | 'danger' | 'muted'): string {
  if (kind === 'success') return 'bg-success-soft text-success'
  if (kind === 'warning') return 'bg-warning-soft text-warning'
  if (kind === 'danger') return 'bg-danger-soft text-danger'
  return 'bg-surface-soft text-fg-muted'
}

watch(page, loadCurrent)
onMounted(loadCurrent)
</script>

<template>
  <div class="p-4">
    <!-- 页签 -->
    <div class="mb-6 flex flex-wrap gap-2">
      <button
        v-for="item in TABS"
        :key="item.key"
        :class="
          tab === item.key
            ? 'bg-primary text-primary-fg'
            : 'border border-line bg-surface text-fg-muted hover:bg-surface-soft'
        "
        class="flex items-center gap-1.5 rounded-control px-4 py-2 text-sm font-medium transition-colors"
        type="button"
        @click="switchTab(item.key)"
      >
        <Icon :name="item.icon" class="h-4 w-4"/>
        {{ item.label }}
      </button>
    </div>

    <p v-if="error" class="mb-3 rounded-control bg-danger-soft px-3 py-2 text-sm text-danger">{{ error }}</p>

    <!-- 概览 -->
    <div v-if="tab === 'overview'" class="grid grid-cols-2 gap-4 md:grid-cols-4">
      <div v-for="card in overviewCards" :key="card.label" class="rounded-card border border-line bg-surface p-4">
        <p class="mb-1 text-xs text-fg-muted">{{ card.label }}</p>
        <p class="text-2xl font-bold text-fg">{{ card.value ?? '—' }}</p>
      </div>
    </div>

    <!-- 列表 -->
    <template v-else>
      <div v-if="loading" class="space-y-3">
        <Skeleton v-for="i in 5" :key="i" class="h-14 w-full"/>
      </div>

      <EmptyState v-else-if="!items.length" title="暂无数据"/>

      <div v-else class="overflow-hidden rounded-card border border-line bg-surface">
        <table class="w-full text-sm">
          <thead class="bg-surface-soft text-xs uppercase text-fg-muted">
          <tr>
            <template v-if="tab === 'licenses'">
              <th class="px-5 py-3 text-left font-semibold">Key</th>
              <th class="px-5 py-3 text-right font-semibold">状态</th>
            </template>
            <template v-else-if="tab === 'tickets'">
              <th class="px-5 py-3 text-left font-semibold">标题</th>
              <th class="px-5 py-3 text-left font-semibold">状态</th>
            </template>
            <template v-else-if="tab === 'scripts'">
              <th class="px-5 py-3 text-left font-semibold">名称</th>
              <th class="px-5 py-3 text-right font-semibold">版本</th>
            </template>
            <template v-else-if="tab === 'logs'">
              <th class="px-5 py-3 text-left font-semibold">脚本</th>
              <th class="px-5 py-3 text-left font-semibold">状态</th>
            </template>
            <template v-else>
              <th class="px-5 py-3 text-left font-semibold">消息</th>
              <th class="px-5 py-3 text-left font-semibold">级别</th>
            </template>
          </tr>
          </thead>
          <tbody class="divide-y divide-line">
          <tr v-for="(item, index) in items" :key="item.id ?? index" class="hover:bg-surface-soft">
            <template v-if="tab === 'licenses'">
              <td class="max-w-[320px] truncate px-5 py-4 font-mono text-fg">{{
                  item.license_key || `#${item.id}`
                }}
              </td>
              <td class="px-5 py-4 text-right">
                  <span :class="tagClass(item.is_active ? 'success' : 'muted')"
                        class="rounded-pill px-2 py-0.5 text-xs">
                    {{ item.is_active ? '活跃' : '停用' }}
                  </span>
              </td>
            </template>

            <template v-else-if="tab === 'tickets'">
              <td class="px-5 py-4 font-medium text-fg">{{ item.title || `#${item.id}` }}</td>
              <td class="px-5 py-4">
                  <span
                    :class="tagClass(item.status === 'open' ? 'warning' : item.status === 'resolved' ? 'success' : 'muted')"
                    class="rounded-pill px-2 py-0.5 text-xs"
                  >{{ item.status || '—' }}</span>
              </td>
            </template>

            <template v-else-if="tab === 'scripts'">
              <td class="px-5 py-4 font-medium text-fg">{{ item.name || `#${item.id}` }}</td>
              <td class="px-5 py-4 text-right text-fg-muted">{{ item.version || '1.0' }}</td>
            </template>

            <template v-else-if="tab === 'logs'">
              <td class="px-5 py-4 text-fg">{{ item.script_name || `#${item.script_id}` }}</td>
              <td class="px-5 py-4">
                  <span
                    :class="tagClass(item.status === 'success' ? 'success' : 'danger')"
                    class="rounded-pill px-2 py-0.5 text-xs"
                  >{{ item.status || '—' }}</span>
              </td>
            </template>

            <template v-else>
              <td class="max-w-xs truncate px-5 py-4 text-fg">{{ item.message || `#${item.id}` }}</td>
              <td class="px-5 py-4">
                  <span
                    :class="tagClass(item.severity === 'critical' ? 'danger' : 'warning')"
                    class="rounded-pill px-2 py-0.5 text-xs"
                  >{{ item.severity || 'info' }}</span>
              </td>
            </template>
          </tr>
          </tbody>
        </table>
      </div>

      <el-pagination
        v-if="total > PER_PAGE"
        v-model:current-page="page"
        :page-size="PER_PAGE"
        :total="total"
        class="mt-3 justify-end"
        layout="total, prev, pager, next"
      />
    </template>
  </div>
</template>

// plugins/enterprise/frontend/admin/Page.tsx
'use client';

import React, {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {AdminShell} from '@/components/admin/AdminShell';
import {apiClient} from '@/lib/api/base-client';
import {BarChart3, Shield, Ticket, Terminal, ScrollText, Bell, Loader2} from 'lucide-react';

const PLUGIN_SLUG = 'enterprise';

function call(action: string, params: any = {}) {
  return apiClient.post(`/plugins/${PLUGIN_SLUG}/action`, {action, params});
}

const TABS = [
  {key: 'overview', label: '概览', icon: BarChart3},
  {key: 'licenses', label: '许可证', icon: Shield},
  {key: 'tickets', label: '工单', icon: Ticket},
  {key: 'scripts', label: '脚本', icon: Terminal},
  {key: 'logs', label: '日志', icon: ScrollText},
  {key: 'alerts', label: '告警', icon: Bell},
];

export default function EnterprisePage() {
  const [tab, setTab] = useState('overview');
  const [page, setPage] = useState(1);

  const {data: overview} = useQuery({
    queryKey: ['ent-overview'],
    queryFn: async () => { const r = await call('get_overview'); return r.data || {}; },
    enabled: tab === 'overview',
  });

  const listQuery = (key: string, action: string) => useQuery({
    queryKey: [key, page],
    queryFn: async () => { const r = await call(action, {page, per_page: 20}); return r.data || {items: [], total: 0}; },
    enabled: tab === key,
  });

  const licenses = listQuery('licenses', 'list_licenses');
  const tickets = listQuery('tickets', 'list_tickets');
  const scripts = listQuery('scripts', 'list_scripts');
  const logs = listQuery('logs', 'list_logs');
  const alerts = listQuery('alerts', 'list_alerts');

  const dataMap: Record<string, any> = {overview, licenses: licenses.data, tickets: tickets.data, scripts: scripts.data, logs: logs.data, alerts: alerts.data};
  const loadingMap: Record<string, boolean> = {licenses: licenses.isLoading, tickets: tickets.isLoading, scripts: scripts.isLoading, logs: logs.isLoading, alerts: alerts.isLoading};
  const cur = dataMap[tab];
  const loading = loadingMap[tab] || false;

  return (
    <AdminShell title="企业管理">
      <div className="flex gap-2 mb-6 flex-wrap">
        {TABS.map(t => (
          <button key={t.key} onClick={() => { setTab(t.key); setPage(1); }}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition flex items-center gap-1.5 ${
              tab === t.key ? 'bg-blue-600 text-white' : 'bg-white dark:bg-gray-900 border hover:bg-gray-50 dark:hover:bg-gray-800'
            }`}><t.icon className="w-4 h-4"/>{t.label}</button>
        ))}
      </div>

      {tab === 'overview' && overview && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            {label: '总许可证', value: overview.total_licenses}, {label: '活跃许可证', value: overview.active_licenses},
            {label: '待处理工单', value: overview.open_tickets}, {label: '进行中', value: overview.in_progress_tickets},
            {label: '部署脚本', value: overview.total_scripts}, {label: '部署次数', value: overview.total_deployments},
            {label: '失败部署', value: overview.failed_deployments}, {label: '未解决告警', value: overview.unresolved_alerts},
          ].map(s => (
            <div key={s.label} className="bg-white dark:bg-gray-900 rounded-xl border p-4">
              <p className="text-xs text-gray-500 dark:text-gray-400 mb-1">{s.label}</p>
              <p className="text-2xl font-bold">{s.value ?? '—'}</p>
            </div>
          ))}
        </div>
      )}

      {tab !== 'overview' && (loading ? (
        <div className="flex justify-center py-16"><Loader2 className="w-8 h-8 animate-spin text-blue-500"/></div>
      ) : !cur?.items?.length ? (
        <div className="bg-white dark:bg-gray-900 rounded-xl border py-16 text-center text-gray-400">
          <Shield className="w-10 h-10 mx-auto mb-3 opacity-40"/><p className="text-sm">暂无数据</p>
        </div>
      ) : (
        <div className="bg-white dark:bg-gray-900 rounded-xl border overflow-hidden">
          <table className="w-full">
            <thead className="bg-gray-50 dark:bg-gray-800 border-b">
              <tr>
                {tab === 'licenses' && <><th className="px-5 py-3 text-xs font-semibold text-gray-500 uppercase text-left">KEY</th><th className="px-5 py-3 text-xs font-semibold text-gray-500 uppercase text-right">状态</th></>}
                {tab === 'tickets' && <><th className="px-5 py-3 text-xs font-semibold text-gray-500 uppercase text-left">标题</th><th className="px-5 py-3 text-xs font-semibold text-gray-500 uppercase text-left hidden sm:table-cell">状态</th></>}
                {tab === 'scripts' && <><th className="px-5 py-3 text-xs font-semibold text-gray-500 uppercase text-left">名称</th><th className="px-5 py-3 text-xs font-semibold text-gray-500 uppercase text-right">版本</th></>}
                {tab === 'logs' && <><th className="px-5 py-3 text-xs font-semibold text-gray-500 uppercase text-left">脚本</th><th className="px-5 py-3 text-xs font-semibold text-gray-500 uppercase text-left hidden sm:table-cell">状态</th></>}
                {tab === 'alerts' && <><th className="px-5 py-3 text-xs font-semibold text-gray-500 uppercase text-left">消息</th><th className="px-5 py-3 text-xs font-semibold text-gray-500 uppercase text-left hidden sm:table-cell">级别</th></>}
              </tr>
            </thead>
            <tbody className="divide-y dark:divide-gray-800">
              {(cur.items || []).map((item: any, i: number) => (
                <tr key={item.id || i} className="hover:bg-gray-50 dark:hover:bg-gray-800/50">
                  {tab === 'licenses' && <><td className="px-5 py-4 text-sm font-mono text-gray-900 dark:text-white truncate max-w-[300px]">{item.license_key || `#${item.id}`}</td><td className="px-5 py-4 text-right"><span className={`px-2 py-0.5 text-xs rounded-full ${item.is_active ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-500'}`}>{item.is_active ? '活跃' : '停用'}</span></td></>}
                  {tab === 'tickets' && <><td className="px-5 py-4 text-sm font-medium text-gray-900 dark:text-white">{item.title || `#${item.id}`}</td><td className="px-5 py-4 hidden sm:table-cell"><span className={`px-2 py-0.5 text-xs rounded-full ${item.status === 'open' ? 'bg-yellow-100 text-yellow-700' : item.status === 'resolved' ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-500'}`}>{item.status || '—'}</span></td></>}
                  {tab === 'scripts' && <><td className="px-5 py-4 text-sm font-medium text-gray-900 dark:text-white">{item.name || `#${item.id}`}</td><td className="px-5 py-4 text-sm text-gray-500 text-right">{item.version || '1.0'}</td></>}
                  {tab === 'logs' && <><td className="px-5 py-4 text-sm text-gray-900 dark:text-white">{item.script_name || `#${item.script_id}`}</td><td className="px-5 py-4 hidden sm:table-cell"><span className={`px-2 py-0.5 text-xs rounded-full ${item.status === 'success' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>{item.status || '—'}</span></td></>}
                  {tab === 'alerts' && <><td className="px-5 py-4 text-sm text-gray-900 dark:text-white truncate max-w-xs">{item.message || `#${item.id}`}</td><td className="px-5 py-4 hidden sm:table-cell"><span className={`px-2 py-0.5 text-xs rounded-full ${item.severity === 'critical' ? 'bg-red-100 text-red-700' : 'bg-yellow-100 text-yellow-700'}`}>{item.severity || 'info'}</span></td></>}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ))}
    </AdminShell>
  );
}
